---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: Sie können Ihr SolidFire Element-Speichersystem nach der Bereitstellung auf dem neuesten Stand halten, indem Sie alle NetApp -Speicherkomponenten aktualisieren. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Übersicht der Upgrade-Sequenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können Ihr SolidFire Element-Speichersystem nach der Bereitstellung auf dem neuesten Stand halten, indem Sie alle NetApp -Speicherkomponenten nacheinander aktualisieren.

Zu diesen Komponenten gehören Management-Services, NetApp Hybrid Cloud Control, die Element-Software, der Management-Knoten und (je nach Installation) das Element-Plug-in für vCenter Server.

[NOTE]
====
* Ab November 2023 können Sie kein Komponenten-Upgrade mehr über NetApp Hybrid Cloud Control oder die REST-API starten, da die Signaturschlüsselzertifikate (privat und öffentlich) am 5. November 2023 abgelaufen sind.  Dieses Problem lässt sich umgehen, indem manlink:task_hcc_upgrade_management_node.html["Durchführung eines In-Place-Upgrades des Management-Knotens"] Vor der Verwendung der NetApp Hybrid Cloud Control oder REST-API zum Aktualisieren der Management-Services, der Element-Software und der Speicher-Firmware muss auf Version 12.8 aktualisiert werden.
+
Wenn Sie einen neuen Management-Knoten mit Version 12.8 bereitstellen, können Sie die NetApp Hybrid Cloud Control oder die REST-API verwenden, um Komponenten-Upgrades in der in der Dokumentation aufgeführten Reihenfolge durchzuführen.<<sys_upgrade,System-Upgrade-Sequenz>> Die

* Die folgenden Knoten werden nicht unterstützt.  Wenn Sie versuchen, einen dieser Knoten auf eine nicht unterstützte Element-Version zu aktualisieren, wird eine Fehlermeldung angezeigt, die besagt, dass der Knoten von Element 12.x nicht unterstützt wird:
+
** Beginnend mit den Speicherknoten Element 12.8, SF4805, SF9605, SF19210 und SF38410.
** Beginnend mit Element 12.7, den Speicherknoten SF2405 und SF9608 sowie den FC-Knoten FC0025 und SF-FCN-01.


* Ab Element 12.5 wird NetApp HealthTools für Element-Software-Upgrades nicht mehr unterstützt.  Wenn Sie Element 11.0 oder 11.1 verwenden, müssen Sie zuerst https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Aktualisieren Sie Element 12.3 mit HealthTools"^] und anschließend mit NetApp Hybrid Cloud Control auf Element 12.5 oder höher aktualisieren.


====
Der<<sys_upgrade,System-Upgrade-Sequenz>> Der Inhalt beschreibt die Aufgaben, die für ein Upgrade eines SolidFire All-Flash-Speichersystems erforderlich sind.  Idealerweise werden diese Verfahren im Rahmen der umfassenderen Modernisierungssequenz und nicht isoliert durchgeführt.  Falls ein komponentenbasiertes Upgrade oder Update erforderlich ist, beachten Sie die Verfahrensvoraussetzungen, um sicherzustellen, dass zusätzliche Komplexitäten berücksichtigt werden.

Derlink:task_sf_upgrade_all_vsphere.html["vSphere-Upgrade-Sequenz"] einschließlich der Inhalte zum Element-Plug-in für vCenter Server, die zusätzliche Schritte vor und nach dem Upgrade beschreiben, die für die Neuinstallation des Element-Plug-ins für vCenter Server erforderlich sind.

.Bevor Sie beginnen
* Sie verwenden Management Node 11.3 oder höher.  Neuere Versionen des Management-Knotens verfügen über eine modulare Architektur, die individuelle Dienste bereitstellt.
+

TIP: Um die Version zu überprüfen, melden Sie sich an Ihrem Verwaltungsknoten an und sehen Sie sich die Element-Versionsnummer im Anmeldebanner an.  Falls Sie nicht Version 11.3 haben, siehelink:task_hcc_upgrade_management_node.html["Aktualisieren Sie Ihren Verwaltungsknoten."] Die

* Sie haben Ihre Management-Services auf mindestens Version 2.1.326 aktualisiert.
+
Upgrades mit NetApp Hybrid Cloud Control sind in früheren Service-Bundle-Versionen nicht verfügbar.

* Sie haben sichergestellt, dass die Systemzeit auf allen Knoten synchronisiert ist und dass NTP für den Speichercluster und die Knoten korrekt konfiguriert ist.  Jeder Knoten muss in der webbasierten Benutzeroberfläche des jeweiligen Knotens mit einem DNS-Nameserver konfiguriert werden.(`https://[IP address]:442` ) ohne ungelöste Clusterfehler im Zusammenhang mit Zeitverzerrungen.
* Sie haben ausreichend Zeit für Ihrelink:task_hcc_upgrade_element_software.html#element-upgrade-time["Element Software"] Undlink:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["Speicher-Firmware"] Upgrades.  Wenn Sie auf die Element-Software Version 12.5 oder höher aktualisieren, variiert die Dauer des Aktualisierungsprozesses je nach Element-Softwareversion und Firmware-Updates.




== [[sys_upgrade]]System-Upgrade-Sequenz

Sie können die folgende Sequenz verwenden, um Ihr NetApp SolidFire All-Flash-Speichersystem auf Element 12.5 oder höher zu aktualisieren.

.Schritte
. link:task_hcc_upgrade_element_prechecks.html["Führen Sie vor dem Upgrade des Speichers Integritätsprüfungen des Element-Speichers durch"].
. link:task_hcc_upgrade_management_node.html["(Optional) Aktualisieren Sie Ihren Verwaltungsknoten"].
+

NOTE: Sie müssen das Betriebssystem des Management-Knotens nicht mehr aktualisieren, um die Element-Software auf dem Speichercluster zu aktualisieren. Wenn der Management-Knoten die Version 11.3 oder höher aufweist, können Sie die Management-Dienste einfach auf die neueste Version aktualisieren, um Element-Upgrades mit NetApp Hybrid Cloud Control durchzuführen. Falls Sie das Betriebssystem des Management-Knotens aus anderen Gründen, wie z. B. zur Behebung von Sicherheitslücken, aktualisieren müssen, befolgen Sie die für Ihr Szenario vorgesehene Vorgehensweise zur Aktualisierung des Management-Knotens.

. link:task_hcc_update_management_services.html["Aktualisierungsverwaltungsdienste von Hybrid Cloud Control"].
+
[IMPORTANT]
====
** Das Management Services 2.27-Paket enthält das Element Plug-in für vCenter Server 5.5, das nur mit dem Management Node 12.8 kompatibel ist. Wenn Sie auf Management Services 2.27 aktualisieren, müssen Sie die Upgrade-Reihenfolge ändern und das Management Services-Paket _nach_ dem Upgrade auf Element 12.8 aktualisieren, um Kompatibilität zwischen dem Management-Knoten und den Management Services zu gewährleisten.
** Wenn Sie auf die Verwaltungsdienste 2.21.61 bis 2.26.40 aktualisieren, müssen Sie das Verwaltungsdienstpaket _vor_ dem Upgrade auf Element 12.8 aktualisieren.


====
+

IMPORTANT: Wenn Sie die Verwaltungsdienste auf Version 2.16 oder höher aktualisieren und einen Verwaltungsknoten 11.3 bis 11.8 ausführen, müssen Sie den RAM Ihrer Verwaltungsknoten-VM erhöhen, bevor Sie die Verwaltungsdienste aktualisieren.

. link:task_hcc_upgrade_element_software.html["Aktualisieren Sie Ihre Element-Software und Speicher-Firmware."].
. link:task_hcc_upgrade_storage_firmware.html["(Optional) Aktualisieren Sie nur Ihre Element-Speicher-Firmware."].
+

NOTE: Sie könnten diese Aufgabe ausführen, wenn ein neues Firmware-Upgrade für den Speicher außerhalb einer Hauptversion verfügbar wird.

. link:task_vcp_upgrade_plugin.html["Aktualisieren Sie Ihr Element-Plug-in für vCenter Server"].


[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]

