---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_element_software.html 
summary: Im Rahmen eines NetApp SolidFire -System-Upgrades aktualisieren Sie die NetApp Element -Software. 
keywords: netapp, solidfire, cluster, element, H610S upgrade, hcc, upgrade role 
---
= Upgrade Element Software
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Zum Aktualisieren der NetApp Element -Software können Sie die NetApp Hybrid Cloud Control-Benutzeroberfläche oder die REST-API verwenden.  Bestimmte Operationen werden während eines Element-Software-Upgrades unterdrückt, wie beispielsweise das Hinzufügen und Entfernen von Knoten, das Hinzufügen und Entfernen von Laufwerken sowie Befehle, die mit Initiatoren, Volume-Zugriffsgruppen und virtuellen Netzwerken verbunden sind.

[CAUTION]
====
Das Management Services 2.27-Paket enthält das Element Plug-in für vCenter Server 5.5, das nur mit dem Management Node 12.8 kompatibel ist. Wenn Sie auf Management Services 2.27 aktualisieren, müssen Sie die Upgrade-Reihenfolge ändern und das Management Services-Paket _nach_ dem Upgrade auf Element 12.8 aktualisieren, um Kompatibilität zwischen dem Management-Knoten und den Management Services zu gewährleisten.

Wenn Sie auf die Verwaltungsdienste 2.21.61 bis 2.26.40 aktualisieren, müssen Sie das Verwaltungsdienstpaket _vor_ dem Upgrade auf Element 12.8 aktualisieren.

====
.Bevor Sie beginnen
* *Administratorrechte*: Sie verfügen über Administratorrechte für den Speichercluster, um das Upgrade durchzuführen.
* *Gültiger Upgrade-Pfad*: Sie haben die Informationen zum Upgrade-Pfad für die Element-Version, auf die Sie aktualisieren, geprüft und bestätigt, dass der Upgrade-Pfad gültig ist.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp KB: Upgrade-Matrix für Speichercluster mit NetApp Element Software"^]
+
Ab Element 12.5 wird NetApp HealthTools für Element-Software-Upgrades nicht mehr unterstützt.  Wenn Sie Element 11.0 oder 11.1 verwenden, müssen Sie zuerstlink:https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Aktualisieren Sie Element 12.3.x mit HealthTools."^] und anschließend mit NetApp Hybrid Cloud Control auf Element 12.5 oder höher aktualisieren.

* *Systemzeitsynchronisierung*: Sie haben sichergestellt, dass die Systemzeit auf allen Knoten synchronisiert ist und dass NTP für den Speichercluster und die Knoten korrekt konfiguriert ist.  Jeder Knoten muss in der webbasierten Benutzeroberfläche des jeweiligen Knotens mit einem DNS-Nameserver konfiguriert werden.(`https://[IP address]:442` ) ohne ungelöste Clusterfehler im Zusammenhang mit Zeitverzerrungen.
* *Systemports*: Wenn Sie NetApp Hybrid Cloud Control für Upgrades verwenden, haben Sie sichergestellt, dass die erforderlichen Ports geöffnet sind. Sehenlink:../storage/reference_prereq_network_port_requirements.html["Netzwerkanschlüsse"] für weitere Informationen.
* *Management-Knoten*: Für die NetApp Hybrid Cloud Control UI und API läuft auf dem Management-Knoten in Ihrer Umgebung die Version 11.3.
* *Clusterzustand*: Sie haben bestätigt, dass der Cluster für ein Upgrade bereit ist. Sehenlink:task_hcc_upgrade_element_prechecks.html["Führen Sie vor dem Speicher-Upgrade Integritätsprüfungen des Element-Speichers durch."] .
* *Aktualisierter Baseboard Management Controller (BMC) für H610S-Speicherknoten*: Sie haben die BMC Version für Ihre H610S-Knoten aktualisiert. Siehe dielink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["Versionshinweise und Upgrade-Anweisungen"^] .


[[element-upgrade-tim]]
* *Dauer des Upgrade-Prozesses*: Sie haben ausreichend Zeit für die Durchführung Ihres Upgrades eingeplant.  Wenn Sie auf die Element-Software Version 12.5 oder höher aktualisieren, variiert die Dauer des Aktualisierungsprozesses je nach Ihrer aktuellen Element-Softwareversion und den Firmware-Updates.
+
[cols="20,20,20,20,20"]
|===
| Speicherknoten | Aktuelle Element-Softwareversion | Ungefähre Installationszeit für Software und Firmware pro Knoten^1^ | Ungefähre Datensynchronisationszeit pro Knoten² | Ungefähre Gesamtaktualisierungszeit pro Knoten 


| Alle SolidFire und NetApp -Knoten der H-Serie mit aktueller Firmware^3^ | 12.x | 15 Minuten | 10 bis 15 Minuten | 20 bis 30 Minuten 


| H610S und H410S | 12.x und 11.8 | 60 Minuten | 30 bis 60 Minuten | 90 bis 120 Minuten 


| H610S | 11.7 und früher | 90 Minuten | 40 bis 70 Minuten | 130 bis 160 Minuten. Sie müssen außerdem https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Führen Sie eine vollständige Abschaltung des Knotens und eine Stromunterbrechung durch."^] für jeden H610S-Knoten. 
|===
+
^1^Eine vollständige Übersicht der Firmware und Treiber-Firmware für Ihre Hardware finden Sie hier:link:../hardware/fw_storage_nodes.html["Unterstützte Firmware-Versionen für SolidFire -Speicherknoten"] Die

+
^2^Wenn man einen Cluster mit hoher Schreib-IOPS-Last mit einer längeren Firmware-Aktualisierungszeit kombiniert, erhöht sich die Datensynchronisierungszeit.

+
^3^ Die folgenden Knoten werden nicht unterstützt.  Wenn Sie versuchen, einen dieser Knoten auf eine nicht unterstützte Element-Version zu aktualisieren, wird eine Fehlermeldung angezeigt, die besagt, dass der Knoten von Element 12.x nicht unterstützt wird:

+
** Beginnend mit den Speicherknoten Element 12.8, SF4805, SF9605, SF19210 und SF38410.
** Beginnend mit Element 12.7, den Speicherknoten SF2405 und SF9608 sowie den FC-Knoten FC0025 und SF-FCN-01.


* *Endbenutzer-Lizenzvereinbarung (EULA)*: Ab Management Services Version 2.20.69 müssen Sie die EULA akzeptieren und speichern, bevor Sie die NetApp Hybrid Cloud Control-Benutzeroberfläche oder -API verwenden, um die Element-Software zu aktualisieren:
+
.. Öffnen Sie die IP-Adresse des Management-Knotens in einem Webbrowser:
+
[listing]
----
https://<ManagementNodeIP>
----
.. Melden Sie sich bei NetApp Hybrid Cloud Control an, indem Sie die Anmeldeinformationen des Speichercluster-Administrators angeben.
.. Wählen Sie oben rechts in der Benutzeroberfläche die Option *Upgrade*.
.. Die Endbenutzer-Lizenzvereinbarung (EULA) erscheint.  Scrollen Sie nach unten, wählen Sie *Ich akzeptiere aktuelle und alle zukünftigen Updates* und wählen Sie *Speichern*.




.Upgrade-Optionen
Wählen Sie eine der folgenden Element-Software-Upgrade-Optionen:

* <<Verwenden Sie die NetApp Hybrid Cloud Control-Benutzeroberfläche, um den Element-Speicher zu aktualisieren.>>
* <<Verwenden Sie die NetApp Hybrid Cloud Control API, um den Element-Speicher zu aktualisieren.>>



IMPORTANT: Wenn Sie einen Knoten der H610S-Serie auf Element 12.5 oder höher aktualisieren und auf dem Knoten eine Element-Version vor 11.8 ausgeführt wird, müssen Sie die zusätzlichen Aktualisierungsschritte in diesem Dokument durchführen. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB-Artikel"^] für jeden Speicherknoten.  Wenn Sie Element 11.8 oder eine neuere Version verwenden, sind die zusätzlichen Upgrade-Schritte nicht erforderlich.



== Verwenden Sie die NetApp Hybrid Cloud Control-Benutzeroberfläche, um den Element-Speicher zu aktualisieren.

Mit der NetApp Hybrid Cloud Control-Benutzeroberfläche können Sie einen Speichercluster aktualisieren.


CAUTION: Informationen zu möglichen Problemen beim Upgrade von Speicherclustern mit NetApp Hybrid Cloud Control und deren Umgehungsmöglichkeiten finden Sie hier. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["KB-Artikel"^] Die

.Schritte
. Öffnen Sie die IP-Adresse des Management-Knotens in einem Webbrowser:
+
[listing]
----
https://<ManagementNodeIP>
----
. Melden Sie sich bei NetApp Hybrid Cloud Control an, indem Sie die Anmeldeinformationen des Speichercluster-Administrators angeben.
. Wählen Sie oben rechts in der Benutzeroberfläche die Option *Upgrade*.
. Auf der Seite *Upgrades* wählen Sie *Speicher* aus.
+
Auf der Registerkarte *Speicher* werden die Speichercluster aufgelistet, die Teil Ihrer Installation sind.  Wenn ein Cluster für NetApp Hybrid Cloud Control nicht erreichbar ist, wird er nicht auf der Seite *Upgrades* angezeigt.

. Wählen Sie aus den folgenden Optionen die für Ihren Cluster zutreffenden Schritte aus:
+
[cols="2*"]
|===
| Option | Schritte 


| Alle Cluster, auf denen Element 11.8 oder höher ausgeführt wird  a| 
.. Wählen Sie *Durchsuchen*, um das heruntergeladene Upgrade-Paket hochzuladen.
.. Warten Sie, bis der Upload abgeschlossen ist.  Ein Fortschrittsbalken zeigt den Status des Uploads an.
+

CAUTION: Der Dateiupload geht verloren, wenn Sie das Browserfenster verlassen.

+
Nach erfolgreichem Hochladen und Validieren der Datei wird eine Meldung auf dem Bildschirm angezeigt.  Die Validierung kann einige Minuten dauern.  Wenn Sie in diesem Schritt das Browserfenster verlassen, bleibt der Datei-Upload erhalten.

.. Wählen Sie *Upgrade starten*.
+

TIP: Der *Upgrade-Status* ändert sich während des Upgrades, um den Status des Prozesses widerzuspiegeln.  Es ändert sich auch als Reaktion auf Aktionen, die Sie durchführen, wie z. B. das Anhalten des Upgrades oder wenn beim Upgrade ein Fehler auftritt. Sehen<<Statusänderungen beim Upgrade>> .

+

NOTE: Während die Aktualisierung läuft, können Sie die Seite verlassen und später zurückkehren, um den Fortschritt weiter zu verfolgen.  Die Seite aktualisiert Status und aktuelle Version nicht dynamisch, wenn die Clusterzeile ausgeblendet ist.  Die Clusterzeile muss erweitert werden, um die Tabelle zu aktualisieren, oder Sie können die Seite neu laden.

+
Die Protokolle können nach Abschluss des Upgrades heruntergeladen werden.





| Sie führen ein Upgrade eines H610S-Clusters durch, auf dem eine Element-Version vor 11.8 ausgeführt wird.  a| 
.. Klicken Sie auf den Dropdown-Pfeil neben dem Cluster, den Sie aktualisieren möchten, und wählen Sie die gewünschte Aktualisierungsversion aus.
.. Wählen Sie *Upgrade starten*.  Nach Abschluss des Upgrades werden Sie von der Benutzeroberfläche aufgefordert, weitere Upgrade-Schritte durchzuführen.
.. Führen Sie die zusätzlich erforderlichen Schritte im folgenden Abschnitt durch: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB-Artikel"^] und bestätigen Sie in der Benutzeroberfläche, dass Sie Phase 2 abgeschlossen haben.


Die Protokolle können nach Abschluss des Upgrades heruntergeladen werden.  Informationen zu den verschiedenen Statusänderungen beim Upgrade finden Sie unter<<Statusänderungen beim Upgrade>> Die

|===




=== Statusänderungen beim Upgrade

Hier sind die verschiedenen Zustände, die die Spalte *Upgrade-Status* in der Benutzeroberfläche vor, während und nach dem Upgrade-Prozess anzeigt:

[cols="2*"]
|===
| Upgrade-Status | Beschreibung 


| Aktuell | Der Cluster wurde auf die neueste verfügbare Element-Version aktualisiert. 


| Verfügbare Versionen | Neuere Versionen der Element- und/oder Speicher-Firmware stehen zum Upgrade zur Verfügung. 


| Im Gange | Die Aktualisierung ist im Gange.  Ein Fortschrittsbalken zeigt den Aktualisierungsstatus an.  Auf dem Bildschirm werden außerdem Fehler auf Knotenebene angezeigt und die Knoten-ID jedes Knotens im Cluster während des Upgrade-Vorgangs dargestellt.  Sie können den Status jedes Knotens über die Element-Benutzeroberfläche oder das NetApp Element Plug-in für die vCenter Server-Benutzeroberfläche überwachen. 


| Upgrade pausiert | Sie können das Upgrade pausieren.  Je nach Status des Aktualisierungsprozesses kann die Pausenoperation erfolgreich sein oder fehlschlagen.  Es erscheint eine Benutzeroberfläche, auf der Sie aufgefordert werden, die Pausenoperation zu bestätigen.  Um sicherzustellen, dass sich der Cluster vor dem Anhalten eines Upgrades in einem sicheren Zustand befindet, kann es bis zu zwei Stunden dauern, bis der Upgrade-Vorgang vollständig angehalten ist.  Um das Upgrade fortzusetzen, wählen Sie *Fortsetzen*. 


| Angehalten | Sie haben das Upgrade pausiert.  Wählen Sie *Fortsetzen*, um den Vorgang fortzusetzen. 


| Fehler | Während des Upgrades ist ein Fehler aufgetreten.  Sie können das Fehlerprotokoll herunterladen und an den NetApp -Support senden.  Nachdem Sie den Fehler behoben haben, können Sie zur Seite zurückkehren und *Fortsetzen* auswählen.  Wenn Sie das Upgrade fortsetzen, läuft der Fortschrittsbalken einige Minuten lang rückwärts, während das System den Integritätscheck durchführt und den aktuellen Status des Upgrades überprüft. 


| Mit Nachbereitung abschließen | Nur für H610S-Knoten, die von einer Element-Version vor 11.8 aktualisiert werden.  Nach Abschluss der ersten Phase des Upgrade-Prozesses werden Sie in diesem Status aufgefordert, weitere Upgrade-Schritte durchzuführen (siehe …). https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB-Artikel"^] ).  Sobald Sie Phase 2 abgeschlossen und dies bestätigt haben, ändert sich der Status zu *Aktuell*. 
|===


== Verwenden Sie die NetApp Hybrid Cloud Control API, um den Element-Speicher zu aktualisieren.

Mithilfe von APIs können Sie Speicherknoten in einem Cluster auf die neueste Element-Softwareversion aktualisieren.  Sie können ein Automatisierungstool Ihrer Wahl verwenden, um die APIs auszuführen.  Der hier dokumentierte API-Workflow verwendet die auf dem Management-Knoten verfügbare REST-API-Benutzeroberfläche als Beispiel.

.Schritte
. Laden Sie das Speicher-Upgrade-Paket auf ein Gerät herunter, das für den Management-Knoten zugänglich ist.
+
Wechseln Sie zur Element-Software https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["Downloadseite"^] und laden Sie das neueste Speicherknoten-Image herunter.

. Laden Sie das Speicher-Upgrade-Paket auf den Verwaltungsknoten hoch:
+
.. Öffnen Sie die REST-API-Benutzeroberfläche des Management-Knotens auf dem Management-Knoten:
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Wählen Sie *Autorisieren* und führen Sie die folgenden Schritte aus:
+
... Geben Sie den Cluster-Benutzernamen und das Passwort ein.
... Geben Sie die Client-ID ein als `mnode-client` Die
... Wählen Sie *Autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Autorisierungsfenster.


.. Wählen Sie in der REST-API-Benutzeroberfläche *POST /packages* aus.
.. Wählen Sie *Ausprobieren*.
.. Wählen Sie *Durchsuchen* und anschließend das gewünschte Upgrade-Paket aus.
.. Wählen Sie *Ausführen*, um den Upload zu starten.
.. Kopieren und speichern Sie die Paket-ID aus der Antwort.(`"id"` ) zur Verwendung in einem späteren Schritt.


. Überprüfen Sie den Status des Uploads.
+
.. Wählen Sie in der REST-API-Benutzeroberfläche *GET​ /packages​/{id}​/status* aus.
.. Wählen Sie *Ausprobieren*.
.. Geben Sie die im vorherigen Schritt kopierte Paket-ID in *id* ein.
.. Wählen Sie *Ausführen*, um die Statusabfrage zu starten.
+
Die Antwort deutet darauf hin, dass `state` als `SUCCESS` wenn fertig.



. Ermitteln Sie die Speichercluster-ID:
+
.. Öffnen Sie die REST-API-Benutzeroberfläche des Management-Knotens auf dem Management-Knoten:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Wählen Sie *Autorisieren* und führen Sie die folgenden Schritte aus:
+
... Geben Sie den Cluster-Benutzernamen und das Passwort ein.
... Geben Sie die Client-ID ein als `mnode-client` Die
... Wählen Sie *Autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Autorisierungsfenster.


.. Wählen Sie in der REST-API-Benutzeroberfläche *GET /installations* aus.
.. Wählen Sie *Ausprobieren*.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus der Antwort die Installations-Asset-ID.(`"id"` ).
.. Wählen Sie in der REST-API-Benutzeroberfläche *GET /installations/{id}* aus.
.. Wählen Sie *Ausprobieren*.
.. Fügen Sie die Installations-Asset-ID in das Feld *id* ein.
.. Wählen Sie *Ausführen*.
.. Kopieren und speichern Sie aus der Antwort die Speichercluster-ID.(`"id"` des Clusters, den Sie für die Verwendung in einem späteren Schritt aktualisieren möchten.


. Führen Sie das Speicher-Upgrade durch:
+
.. Öffnen Sie die Benutzeroberfläche der Storage-REST-API auf dem Verwaltungsknoten:
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Wählen Sie *Autorisieren* und führen Sie die folgenden Schritte aus:
+
... Geben Sie den Cluster-Benutzernamen und das Passwort ein.
... Geben Sie die Client-ID ein als `mnode-client` Die
... Wählen Sie *Autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Autorisierungsfenster.


.. Wählen Sie *POST /upgrades*.
.. Wählen Sie *Ausprobieren*.
.. Geben Sie die Upgrade-Paket-ID im Parameterfeld ein.
.. Geben Sie die Speichercluster-ID im Parameterfeld ein.
+
Die Nutzlast sollte in etwa so aussehen wie im folgenden Beispiel:

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Wählen Sie *Ausführen*, um das Upgrade zu starten.
+
Die Antwort sollte den Status angeben als `initializing` :

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Kopieren Sie die Upgrade-ID.(`"upgradeId"` ) das ist Teil der Antwort.


. Überprüfen Sie den Fortschritt und die Ergebnisse des Upgrades:
+
.. Wählen Sie *GET ​/upgrades/{upgradeId}*.
.. Wählen Sie *Ausprobieren*.
.. Geben Sie die Upgrade-ID aus dem vorherigen Schritt in *upgradeId* ein.
.. Wählen Sie *Ausführen*.
.. Führen Sie einen der folgenden Schritte aus, falls während des Upgrades Probleme auftreten oder besondere Anforderungen bestehen:
+
[cols="2*"]
|===
| Option | Schritte 


| Sie müssen die Cluster-Integritätsprobleme aufgrund von `failedHealthChecks` Nachricht im Antworttext.  a| 
... Rufen Sie den für jedes Problem aufgeführten spezifischen KB-Artikel auf oder führen Sie die angegebene Abhilfemaßnahme durch.
... Falls ein Knowledge Base-Artikel angegeben ist, führen Sie die im entsprechenden Knowledge Base-Artikel beschriebenen Schritte durch.
... Nachdem Sie die Clusterprobleme behoben haben, authentifizieren Sie sich gegebenenfalls erneut und wählen Sie *PUT ​/upgrades/{upgradeId}*.
... Wählen Sie *Ausprobieren*.
... Geben Sie die Upgrade-ID aus dem vorherigen Schritt in *upgradeId* ein.
... Eingeben `"action":"resume"` im Anfragetext.
+
[listing]
----
{
  "action": "resume"
}
----
... Wählen Sie *Ausführen*.




| Sie müssen das Upgrade pausieren, weil das Wartungsfenster abläuft oder aus einem anderen Grund.  a| 
... Bei Bedarf erneut authentifizieren und *PUT ​/upgrades/{upgradeId}* auswählen.
... Wählen Sie *Ausprobieren*.
... Geben Sie die Upgrade-ID aus dem vorherigen Schritt in *upgradeId* ein.
... Eingeben `"action":"pause"` im Anfragetext.
+
[listing]
----
{
  "action": "pause"
}
----
... Wählen Sie *Ausführen*.




| Wenn Sie einen H610S-Cluster aktualisieren, auf dem eine Element-Version vor 11.8 ausgeführt wird, sehen Sie den Status `finishedNeedsAck` im Antworttext. Sie müssen für jeden H610S-Speicherknoten zusätzliche Upgrade-Schritte durchführen.  a| 
... Führen Sie die zusätzlichen Upgrade-Schritte in diesem Abschnitt durch. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB-Artikel"^] für jeden Knoten.
... Bei Bedarf erneut authentifizieren und *PUT ​/upgrades/{upgradeId}* auswählen.
... Wählen Sie *Ausprobieren*.
... Geben Sie die Upgrade-ID aus dem vorherigen Schritt in *upgradeId* ein.
... Eingeben `"action":"acknowledge"` im Anfragetext.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Wählen Sie *Ausführen*.


|===
.. Führen Sie die *GET ​/upgrades/{upgradeId}*-API bei Bedarf mehrmals aus, bis der Vorgang abgeschlossen ist.
+
Während des Upgrades `status` zeigt an `running` Wenn keine Fehler auftreten.  Mit jedem Upgrade eines Knotens wird die `step` Wertänderungen auf `NodeFinished` Die

+
Das Upgrade wurde erfolgreich abgeschlossen, als `percent` Wert ist `100` und die `state` zeigt an `finished` Die







== Was passiert, wenn ein Upgrade mit NetApp Hybrid Cloud Control fehlschlägt?

Wenn während eines Upgrades ein Laufwerk oder ein Knoten ausfällt, zeigt die Element-Benutzeroberfläche Clusterfehler an.  Der Upgrade-Prozess wird nicht zum nächsten Knoten fortgesetzt, sondern wartet, bis die Clusterfehler behoben sind.  Die Fortschrittsanzeige in der Benutzeroberfläche zeigt an, dass das Upgrade auf die Behebung der Clusterfehler wartet.  In dieser Phase funktioniert die Auswahl von *Pause* in der Benutzeroberfläche nicht, da das Upgrade wartet, bis der Cluster fehlerfrei läuft.  Sie müssen den NetApp -Support hinzuziehen, um Unterstützung bei der Fehleranalyse zu erhalten.

NetApp Hybrid Cloud Control verfügt über eine voreingestellte Wartezeit von drei Stunden, während der eines der folgenden Szenarien eintreten kann:

* Die Clusterfehler werden innerhalb des dreistündigen Zeitfensters behoben, und das Upgrade wird fortgesetzt.  In diesem Fall müssen Sie keine Maßnahmen ergreifen.
* Das Problem besteht auch nach drei Stunden noch, und der Upgrade-Status zeigt *Fehler* mit einem roten Banner an.  Sie können das Upgrade fortsetzen, indem Sie nach Behebung des Problems *Fortsetzen* auswählen.
* Der NetApp Support hat festgestellt, dass das Upgrade vorübergehend abgebrochen werden muss, um vor Ablauf des dreistündigen Zeitfensters Korrekturmaßnahmen zu ergreifen.  Der Support wird die API nutzen, um das Upgrade abzubrechen.



CAUTION: Wird das Cluster-Upgrade während der Aktualisierung eines Knotens abgebrochen, kann dies dazu führen, dass die Laufwerke unsachgemäß aus dem Knoten entfernt werden.  Wenn die Laufwerke unsachgemäß entfernt werden, ist für das Wiedereinfügen der Laufwerke während eines Upgrades ein manuelles Eingreifen des NetApp -Supports erforderlich.  Möglicherweise benötigt der Knoten länger für Firmware-Updates oder Synchronisierungsaktivitäten nach dem Update.  Sollte der Upgrade-Prozess ins Stocken geraten, wenden Sie sich bitte an den NetApp Support.

[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

