---
sidebar: sidebar 
permalink: mnode/task_mnode_install_add_storage_NIC.html 
summary: Wenn Sie eine zusätzliche Netzwerkkarte für die Datenspeicherung verwenden, sollten Sie eine ungetaggte oder getaggte Netzwerkschnittstelle einrichten. 
keywords: netapp, element, management node, mnode, network, nic, storage nic 
---
= Konfigurieren eines Speichernetzwerkschnittstellencontrollers (NIC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Wenn Sie eine zusätzliche Netzwerkkarte für die Speicherung verwenden, können Sie sich per SSH mit dem Management-Knoten verbinden oder die vCenter-Konsole verwenden und einen curl-Befehl ausführen, um eine getaggte oder ungetaggte Netzwerkschnittstelle einzurichten.

.Bevor Sie beginnen
* Sie kennen Ihre eth0-IP-Adresse.
* Auf Ihrem Cluster läuft die NetApp Element Software 11.3 oder höher.
* Sie haben einen Management-Knoten der Version 11.3 oder höher bereitgestellt.


.Konfigurationsoptionen
Wählen Sie die Option, die für Ihre Umgebung relevant ist:

* <<Konfigurieren Sie einen Storage-Netzwerkschnittstellencontroller (NIC) für eine ungetaggte Netzwerkschnittstelle>>
* <<Konfigurieren Sie einen Speichernetzwerkschnittstellencontroller (NIC) für eine getaggte Netzwerkschnittstelle>>




== Konfigurieren Sie einen Storage-Netzwerkschnittstellencontroller (NIC) für eine ungetaggte Netzwerkschnittstelle

.Schritte
. Öffnen Sie eine SSH- oder vCenter-Konsole.
. Ersetzen Sie die Werte in der folgenden Befehlsvorlage und führen Sie den Befehl aus:
+

NOTE: Werte werden dargestellt durch `$` für jeden der erforderlichen Parameter Ihrer neuen Speichernetzwerkschnittstelle.  Der `cluster` Das Objekt in der folgenden Vorlage ist erforderlich und kann zur Umbenennung des Hostnamens des Management-Knotens verwendet werden. `--insecure` oder `-k` Optionen sollten nicht in Produktionsumgebungen verwendet werden.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name"
                         }
             },
    "method": "SetConfig"
}
'
----




== Konfigurieren Sie einen Speichernetzwerkschnittstellencontroller (NIC) für eine getaggte Netzwerkschnittstelle

.Schritte
. Öffnen Sie eine SSH- oder vCenter-Konsole.
. Ersetzen Sie die Werte in der folgenden Befehlsvorlage und führen Sie den Befehl aus:
+

NOTE: Werte werden dargestellt durch `$` für jeden der erforderlichen Parameter Ihrer neuen Speichernetzwerkschnittstelle.  Der `cluster` Das Objekt in der folgenden Vorlage ist erforderlich und kann zur Umbenennung des Hostnamens des Management-Knotens verwendet werden. `--insecure` oder `-k` Optionen sollten nicht in Produktionsumgebungen verwendet werden.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up",
                                   "virtualNetworkTag" : "$vlan_id"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name",
                         "cipi": "$eth1.$vlan_id",
                         "sipi": "$eth1.$vlan_id"
                         }
             },
    "method": "SetConfig"
}
'
----


[discrete]
== Weitere Informationen finden Sie hier.

* link:task_mnode_add_assets.html["Fügen Sie dem Verwaltungsknoten ein Controller-Asset hinzu."]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]

