---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_remote_support_connections.html 
summary: Über den Management-Knoten können Sie den Zugriff auf den NetApp -Support für die Fehlerbehebung aktivieren. 
keywords: netapp, mnode, management node, connect to support, support tunnel, rst 
---
= Starten Sie eine NetApp Remote-Supportsitzung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Falls Sie technischen Support für Ihr SolidFire All-Flash-Speichersystem benötigen, kann sich der NetApp Support per Fernzugriff mit Ihrem System verbinden.  Um eine Sitzung zu starten und Fernzugriff zu erhalten, kann der NetApp Support eine Reverse-Secure-Shell-Verbindung (SSH) zu Ihrer Umgebung öffnen.

Sie können einen TCP-Port für eine SSH-Reverse-Tunnel-Verbindung mit dem NetApp -Support öffnen.  Diese Verbindung ermöglicht es dem NetApp -Support, sich in Ihren Management-Knoten einzuloggen.

.Bevor Sie beginnen
* Bei Managementdiensten ab Version 2.18 ist die Möglichkeit des Fernzugriffs auf dem Managementknoten standardmäßig deaktiviert.  Informationen zur Aktivierung der Fernzugriffsfunktionalität finden Sie unter https://docs.netapp.com/us-en/element-software/mnode/task_mnode_ssh_management.html["SSH-Funktionalität auf dem Management-Knoten verwalten"] Die
* Wenn sich Ihr Management-Knoten hinter einem Proxy-Server befindet, sind die folgenden TCP-Ports in der sshd.config-Datei erforderlich:
+
[cols="15,25,60"]
|===
| TCP-Port | Beschreibung | Verbindungsrichtung 


| 443 | API-Aufrufe/HTTPS für Reverse-Port-Weiterleitung über einen offenen Support-Tunnel zur Web-UI | Managementknoten zu Speicherknoten 


| 22 | SSH-Anmeldezugriff | Managementknoten zu Speicherknoten oder von Speicherknoten zu Managementknoten 
|===


.Schritte
* Melden Sie sich an Ihrem Management-Knoten an und öffnen Sie eine Terminal-Sitzung.
* Geben Sie auf Aufforderung Folgendes ein:
+
`rst -r  sfsupport.solidfire.com -u element -p <port_number>`

* Um den Remote-Support-Tunnel zu schließen, geben Sie Folgendes ein:
+
`rst --killall`

* (Optional) Deaktivieren https://docs.netapp.com/us-en/element-software/mnode/task_mnode_ssh_management.html["Fernzugriffsfunktionalität"] wieder.
+

NOTE: SSH bleibt auf dem Management-Knoten aktiviert, solange Sie es nicht deaktivieren.  Die SSH-fähige Konfiguration bleibt auf dem Management-Knoten auch nach Updates und Upgrades erhalten, bis sie manuell deaktiviert wird.





== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]

