---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: 'Sie können den Management-Knoten (mNode) verwenden, um Active IQ für SolidFire All-Flash-Speicher zu aktivieren.' 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Aktivieren Sie Active IQ und die NetApp Überwachung.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Active IQ Speicherüberwachung aktivieren, falls Sie dies nicht bereits während der Installation oder des Upgrades getan haben.  Möglicherweise müssen Sie dieses Verfahren anwenden, wenn Sie SolidFire Active IQ nicht während der Installation eines SolidFire All-Flash-Speichersystems eingerichtet haben.

Der Active IQ Collector-Dienst leitet Konfigurationsdaten und auf der Element-Software basierende Cluster-Leistungsmetriken an SolidFire Active IQ zur Erstellung von historischen Berichten und zur nahezu Echtzeit-Leistungsüberwachung weiter.  Der NetApp Überwachungsdienst ermöglicht die Weiterleitung von Fehlern im Speichercluster an vCenter zur Benachrichtigung.

.Bevor Sie beginnen
* Einige Funktionen in Active IQ, beispielsweise Quality of Service (QoS), benötigen Element 11.3 oder höher, um korrekt zu funktionieren.  Um sicherzustellen, dass Sie alle Active IQ -Funktionen nutzen können, empfiehlt NetApp Folgendes:
+
** Auf Ihrem Speichercluster läuft die NetApp Element Software 11.3 oder höher.
** Sie haben einen Management-Knoten mit Version 11.3 oder höher bereitgestellt.


* Sie haben Internetzugang.  Der Active IQ Collector-Dienst kann nicht von Dark-Sites aus genutzt werden, die keine externe Verbindung haben.


.Schritte
. Ermitteln Sie die Basis-Asset-ID für die Installation:
+
.. Öffnen Sie die REST-API-Benutzeroberfläche des Inventardienstes auf dem Verwaltungsknoten:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Wählen Sie *Autorisieren* und führen Sie die folgenden Schritte aus:
+
... Geben Sie den Cluster-Benutzernamen und das Passwort ein.
... Geben Sie die Client-ID ein als `mnode-client` Die
... Wählen Sie *Autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Wählen Sie in der REST-API-Benutzeroberfläche *GET /installations* aus.
.. Wählen Sie *Ausprobieren*.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus dem Antworttext des Codes 200 den `id` für die Installation.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Ihre Installation verfügt über eine Basis-Asset-Konfiguration, die während der Installation oder des Upgrades erstellt wurde.



. Telemetrie aktivieren:
+
.. Greifen Sie auf die API-Benutzeroberfläche des mnode-Dienstes auf dem Management-Knoten zu, indem Sie die IP-Adresse des Management-Knotens gefolgt von eingeben. `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Wählen Sie *Autorisieren* oder ein beliebiges Schlosssymbol und führen Sie die folgenden Schritte aus:
+
... Geben Sie den Cluster-Benutzernamen und das Passwort ein.
... Geben Sie die Client-ID ein als `mnode-client` Die
... Wählen Sie *Autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Basis-Asset konfigurieren:
+
... Wählen Sie *PUT /assets/{asset_id}*.
... Wählen Sie *Ausprobieren*.
... Geben Sie Folgendes in die JSON-Nutzlast ein:
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... Geben Sie die Basis-ID aus dem vorherigen Schritt in *asset_ID* ein.
... Wählen Sie *Ausführen*.
+
Der Active IQ Dienst wird automatisch neu gestartet, sobald Assets geändert werden.  Das Ändern von Assets führt zu einer kurzen Verzögerung, bevor die Einstellungen angewendet werden.





. Falls noch nicht geschehen, fügen Sie ein vCenter-Controller-Asset für NetApp Hybrid Cloud Control zu den bekannten Assets des Management-Knotens hinzu:
+

NOTE: Für die Überwachungsdienste von NetApp wird ein Controller benötigt.

+
.. Wählen Sie *POST /assets/{asset_id}/controllers*, um ein Controller-Sub-Asset hinzuzufügen.
.. Wählen Sie *Ausprobieren*.
.. Geben Sie die übergeordnete Basis-Asset-ID, die Sie in Ihre Zwischenablage kopiert haben, in das Feld *asset_id* ein.
.. Geben Sie die erforderlichen Nutzlastwerte ein mit `type` als `vCenter` und vCenter-Anmeldeinformationen.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip`ist die vCenter IP-Adresse.

.. Wählen Sie *Ausführen*.




[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]

