---
permalink: concepts/concept_intro_management_node.html 
sidebar: sidebar 
keywords: what is, element mnode, management node, mnode 
summary: 'Der Management-Knoten \(mNode\) ist eine virtuelle Maschine, die parallel zu einem oder mehreren Element-Software-basierten Speicherclustern läuft.  Es dient der Aktualisierung und Bereitstellung von Systemdiensten, einschließlich Überwachung und Telemetrie, der Verwaltung von Clusterressourcen und -einstellungen, der Ausführung von Systemtests und -dienstprogrammen sowie der Ermöglichung des NetApp Supportzugriffs zur Fehlerbehebung.' 
---
= Verwaltungsknoten für die Element-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Derlink:../mnode/task_mnode_work_overview.html["Managementknoten (mNode)"] ist eine virtuelle Maschine, die parallel zu einem oder mehreren Element-Software-basierten Speicherclustern läuft.  Es dient der Aktualisierung und Bereitstellung von Systemdiensten, einschließlich Überwachung und Telemetrie, der Verwaltung von Clusterressourcen und -einstellungen, der Ausführung von Systemtests und -dienstprogrammen sowie der Ermöglichung des NetApp Supportzugriffs zur Fehlerbehebung.

Der Management-Knoten interagiert mit einem Speichercluster, um Managementaktionen durchzuführen, ist aber kein Mitglied des Speicherclusters.  Die Management-Knoten sammeln regelmäßig Informationen über den Cluster mittels API-Aufrufen und melden diese Informationen an Active IQ zur Fernüberwachung (sofern aktiviert).  Die Management-Knoten sind außerdem für die Koordinierung von Software-Upgrades der Cluster-Knoten zuständig.

Ab der Element-Version 11.3 fungiert der Management-Knoten als Microservice-Host, was schnellere Aktualisierungen ausgewählter Softwaredienste außerhalb von Hauptversionen ermöglicht.  Diese Mikrodienste oderlink:../concepts/concept_intro_management_services_for_afa.html["Managementdienstleistungen"] werden regelmäßig als Servicepakete aktualisiert.
