---
permalink: storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html 
sidebar: sidebar 
keywords: volume access groups, initiators, working with, chap, fc, iscsi 
summary: Sie können iSCSI-Initiatoren oder Fibre-Channel-Initiatoren verwenden, um auf die in Volume-Zugriffsgruppen definierten Volumes zuzugreifen. 
---
= Arbeiten mit Volumenzugriffsgruppen und Initiatoren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können iSCSI-Initiatoren oder Fibre-Channel-Initiatoren verwenden, um auf die in Volume-Zugriffsgruppen definierten Volumes zuzugreifen.

Sie können Zugriffsgruppen erstellen, indem Sie iSCSI-Initiator-IQNs oder Fibre-Channel-WWPNs in einer Sammlung von Volumes zuordnen.  Jeder IQN, den Sie einer Zugriffsgruppe hinzufügen, kann auf jedes Volume in der Gruppe zugreifen, ohne dass eine CHAP-Authentifizierung erforderlich ist.

Es gibt zwei Arten von CHAP-Authentifizierungsmethoden:

* CHAP-Authentifizierung auf Kontoebene: Sie können die CHAP-Authentifizierung für das Konto zuweisen.
* CHAP-Authentifizierung auf Initiatorebene: Sie können eindeutige CHAP-Ziele und Geheimnisse für bestimmte Initiatoren zuweisen, ohne an einen einzigen CHAP über ein einzelnes Konto gebunden zu sein.  Diese CHAP-Authentifizierung auf Initiatorebene ersetzt die Anmeldeinformationen auf Kontoebene.


Optional können Sie mit pro-Initiator CHAP die Autorisierung des Initiators und die CHAP-Authentifizierung pro Initiator erzwingen.  Diese Optionen können pro Initiator definiert werden, und eine Zugriffsgruppe kann eine Mischung von Initiatoren mit unterschiedlichen Optionen enthalten.

Jeder WWPN, den Sie einer Zugriffsgruppe hinzufügen, ermöglicht den Zugriff auf das Fibre Channel-Netzwerk für die Volumes in der Zugriffsgruppe.


NOTE: Zugriffsgruppen für Datenträger unterliegen folgenden Beschränkungen:

* In einer Zugriffsgruppe sind maximal 64 IQNs oder WWPNs zulässig.
* Eine Zugriffsgruppe kann aus maximal 2000 Datenträgern bestehen.
* Ein IQN oder WWPN kann nur einer Zugriffsgruppe angehören.
* Ein einzelner Band kann maximal vier Zugriffsgruppen angehören.




== Weitere Informationen

* xref:task_data_manage_vol_access_group_create_a_volume_access_group.adoc[Erstellen einer Volume-Zugriffsgruppe]
* xref:task_data_manage_vol_access_group_add_volumes.adoc[Fügen Sie einer Zugriffsgruppe Volumes hinzu.]
* xref:task_data_manage_vol_access_group_remove_volumes.adoc[Volumes aus einer Zugriffsgruppe entfernen]
* xref:task_data_manage_vol_access_group_create_an_initiator.adoc[Einen Initiator erstellen]
* xref:task_data_manage_vol_access_group_edit_an_initiator.adoc[Bearbeiten Sie einen Initiator]
* xref:task_data_manage_vol_access_group_add_a_single_initiator.adoc[Fügen Sie einer Volume-Zugriffsgruppe einen einzelnen Initiator hinzu.]
* xref:task_data_manage_vol_access_group_add_multiple_initiators.adoc[Fügen Sie einer Volume-Zugriffsgruppe mehrere Initiatoren hinzu]
* xref:task_data_manage_vol_access_group_remove_initiators_from_an_access_group.adoc[Initiatoren aus einer Zugriffsgruppe entfernen]
* xref:task_data_manage_vol_access_group_delete.adoc[Eine Zugriffsgruppe löschen]
* xref:task_data_manage_vol_access_group_delete_an_initiator.adoc[Initiator löschen]

