---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: Virtuelle Netzwerke in SolidFire -Speichern ermöglichen es, den Datenverkehr zwischen mehreren Clients, die sich in separaten logischen Netzwerken befinden, mit einem Cluster zu verbinden.  Die Verbindungen zum Cluster werden im Netzwerk-Stack durch VLAN-Tagging getrennt. 
---
= Virtuelle Netzwerke verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtuelle Netzwerke in SolidFire -Speichern ermöglichen es, den Datenverkehr zwischen mehreren Clients, die sich in separaten logischen Netzwerken befinden, mit einem Cluster zu verbinden.  Die Verbindungen zum Cluster werden im Netzwerk-Stack durch VLAN-Tagging getrennt.



== Weitere Informationen

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Fügen Sie ein virtuelles Netzwerk hinzu]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Virtuelles Routing und Weiterleitung aktivieren]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Bearbeiten eines virtuellen Netzwerks]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[VRF-VLANs bearbeiten]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Löschen eines virtuellen Netzwerks]

