---
permalink: storage/concept_data_protection_volume_snapshot_backup_operations.html 
sidebar: sidebar 
keywords: volume snapshot, backup operations, back up volume snapshot, cluster, object store 
summary: Sie können die integrierte Backup-Funktion verwenden, um einen Volume-Snapshot zu sichern.  Sie können Snapshots von einem SolidFire -Cluster in einem externen Objektspeicher oder in einem anderen SolidFire -Cluster sichern.  Wenn Sie einen Snapshot in einem externen Objektspeicher sichern, benötigen Sie eine Verbindung zum Objektspeicher, die Lese-/Schreibvorgänge ermöglicht. 
---
= Sichern Sie einen Volume-Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die integrierte Backup-Funktion verwenden, um einen Volume-Snapshot zu sichern.  Sie können Snapshots von einem SolidFire -Cluster in einem externen Objektspeicher oder in einem anderen SolidFire -Cluster sichern.  Wenn Sie einen Snapshot in einem externen Objektspeicher sichern, benötigen Sie eine Verbindung zum Objektspeicher, die Lese-/Schreibvorgänge ermöglicht.

* link:task_data_protection_back_up_a_volume_snapshot_to_an_amazon_s3_object_store["Sichern eines Volume-Snapshots in einem Amazon S3-Objektspeicher"]
* link:task_data_protection_back_up_a_volume_snapshot_to_openstack_swift["Sichern eines Volume-Snapshots in einem OpenStack Swift-Objektspeicher"]
* link:task_data_protection_back_up_volume_to_solidfire["Sichern eines Volume-Snapshots auf einem SolidFire -Cluster"]

