---
permalink: storage/concept_prereq_switch_configuration_for_solidfire_clusters.html 
sidebar: sidebar 
keywords: cluster switch configuration, best practices for switch configuration, optimal storage performance, node hardware, traffic, cluster, Element software, best practices, switches, switch requirements, storage, performance, storage performance 
summary: Das NetApp Element Softwaresystem stellt bestimmte Anforderungen an die Switches und empfiehlt Best Practices für eine optimale Speicherleistung. 
---
= Switch-Konfiguration für Cluster, auf denen die Element-Software läuft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das NetApp Element Softwaresystem stellt bestimmte Anforderungen an die Switches und empfiehlt Best Practices für eine optimale Speicherleistung.

Speicherknoten benötigen je nach spezifischer Knotenhardware 10- oder 25-GbE-Ethernet-Switches für iSCSI-Speicherdienste und die Kommunikation zwischen Knoten innerhalb des Clusters.  Für diese Arten von Datenverkehr können 1-GbE-Switches verwendet werden:

* Verwaltung des Clusters und der Knoten
* Intra-Cluster-Management-Datenverkehr zwischen den Knoten
* Datenverkehr zwischen den Clusterknoten und der virtuellen Maschine des Managementknotens


|===


 a| 
*Bewährte Vorgehensweise:* Bei der Konfiguration von Ethernet-Switches für Cluster-Datenverkehr sollten Sie die folgenden bewährten Vorgehensweisen beachten:

* Für den Datenverkehr außerhalb des Speicherbereichs im Cluster sollten zwei 1GbE-Switches eingesetzt werden, um hohe Verfügbarkeit und Lastverteilung zu gewährleisten.
* Bei den Speichernetzwerk-Switches sollten die Switches paarweise eingesetzt und Jumbo-Frames (MTU-Größe von 9216 Bytes) konfiguriert und verwendet werden.  Dies gewährleistet eine erfolgreiche Installation und beseitigt Speichernetzwerkfehler aufgrund fragmentierter Pakete.


|===
Für die Bereitstellung von Element werden mindestens zwei Netzwerksegmente benötigt, eines für jede der folgenden Datenverkehrsarten:

* Management
* Speicherung/Daten


Je nach NetApp H-Series Storage-Node-Modell und der geplanten Verkabelungskonfiguration können Sie diese Netzwerke physisch mit separaten Switches oder logisch mit VLANs trennen.  Für die meisten Implementierungen ist es jedoch erforderlich, diese Netzwerke mithilfe von VLANs logisch zu trennen.

Speicherknoten müssen vor, während und nach der Bereitstellung miteinander kommunizieren können.

Wenn Sie separate Managementnetzwerke für Speicherknoten implementieren, stellen Sie sicher, dass zwischen diesen Managementnetzwerken Netzwerkrouten bestehen.  Diesen Netzwerken müssen Gateways zugewiesen sein, und es muss eine Route zwischen den Gateways geben.  Stellen Sie sicher, dass jedem neuen Knoten ein Gateway zugewiesen wird, um die Kommunikation zwischen den Knoten und den Managementnetzwerken zu ermöglichen.

NetApp Element benötigt Folgendes:

* Alle Switch-Ports, die mit NetApp H-Series-Speicherknoten verbunden sind, müssen als Spanning-Tree-Edge-Ports konfiguriert werden.
+
** Bei Cisco -Switches können Sie dies je nach Switch-Modell, Softwareversion und Porttyp mit einem der folgenden Befehle tun:
+
*** `spanning-tree port type edge`
*** `spanning-tree port type edge trunk`
*** `spanning-tree portfast`
*** `spanning-tree portfast trunk`


** Bei Mellanox-Switches können Sie dies mit folgendem tun: `spanning-tree port type edge` Befehl.


* Die Switches, die den Speicherdatenverkehr verarbeiten, müssen Geschwindigkeiten von mindestens 10 GbE pro Port unterstützen (bis zu 25 GbE pro Port werden unterstützt).
* Die Switches, die den Management-Datenverkehr verarbeiten, müssen Geschwindigkeiten von mindestens 1 Gbit/s pro Port unterstützen.
* Sie müssen Jumbo-Frames auf den Switch-Ports konfigurieren, die den Speicherdatenverkehr verarbeiten.  Für eine erfolgreiche Installation müssen die Hosts in der Lage sein, 9000 Byte große Pakete durchgängig zu senden.
* Die Roundtrip-Netzwerklatenz zwischen allen Speicherknoten sollte 2 ms nicht überschreiten.


Einige Knoten bieten zusätzliche Out-of-Band-Managementfunktionen über einen dedizierten Management-Port.  Die NetApp Knoten H300S, H500S und H700S ermöglichen auch den IPMI-Zugriff über Port A. Als Best Practice empfiehlt es sich, die Fernverwaltung zu vereinfachen, indem Sie die Out-of-Band-Verwaltung für alle Knoten in Ihrer Umgebung konfigurieren.



== Weitere Informationen

* https://docs.netapp.com/us-en/hci/docs/hci_prereqs_network_switch.html["Anforderungen an das NetApp HCI Netzwerk und die Switches"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

