---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: SSL-Verschlüsselungsalgorithmen werden von Hosts verwendet, um eine sichere Kommunikation herzustellen.  Die Element-Software unterstützt Standard-Verschlüsselungsverfahren sowie nicht standardmäßige Verfahren, wenn der FIPS 140-2-Modus aktiviert ist. 
---
= SSL-Verschlüsselungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL-Verschlüsselungsalgorithmen werden von Hosts verwendet, um eine sichere Kommunikation herzustellen.  Die Element-Software unterstützt Standard-Verschlüsselungsverfahren sowie nicht standardmäßige Verfahren, wenn der FIPS 140-2-Modus aktiviert ist.

Die folgenden Listen enthalten die von der Element-Software unterstützten Standard-SSL-Verschlüsselungsverfahren (Secure Socket Layer) sowie die SSL-Verschlüsselungsverfahren, die im FIPS 140-2-Modus unterstützt werden:

* *FIPS 140-2 deaktiviert*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) – A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5 (rsa 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA (rsa 2048) - C

+
TLS_RSA_WITH_SEED_CBC_SHA (rsa 2048) - A

* *FIPS 140-2-fähig*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) – A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) – A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (Sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (Sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (Sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (Sect571r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A





== Weitere Informationen

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Aktivieren Sie FIPS 140-2 für HTTPS auf Ihrem Cluster.]
