---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Copyright
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. Alle Rechte vorbehalten. Gedruckt in den USA.

Kein Teil dieses urheberrechtlich geschützten Dokuments darf ohne vorherige schriftliche Genehmigung des Urheberrechtsinhabers in irgendeiner Form oder mit irgendwelchen Mitteln – grafisch, elektronisch oder mechanisch, einschließlich Fotokopieren, Aufzeichnen, Speichern oder Speichern in einem elektronischen Abrufsystem – reproduziert werden.

Software, die von urheberrechtlich geschütztem NetApp Material abgeleitet wird, unterliegt der folgenden Lizenz und dem folgenden Haftungsausschluss:

DIE VORLIEGENDE SOFTWARE WIRD IN DER VORLIEGENDEN FORM VON NETAPP ZUR VERFÜGUNG GESTELLT, D. H. OHNE JEGLICHE EXPLIZITE ODER IMPLIZITE GEWÄHRLEISTUNG, EINSCHLIESSLICH, JEDOCH NICHT BESCHRÄNKT AUF DER STILLSCHWEIGENDEN GEWÄHRLEISTUNG DER MARKTGÄNGIGKEIT UND EIGNUNG FÜR EINEN BESTIMMTEN ZWECK, DIE HIERMIT AUSGESCHLOSSEN WERDEN. NETAPP ÜBERNIMMT KEINERLEI HAFTUNG FÜR DIREKTE, INDIREKTE, ZUFÄLLIGE, BESONDERE ODER FOLGESCHÄDEN (EINSCHLIESSLICH, JEDOCH NICHT BESCHRÄNKT AUF DIE BESCHAFFUNG ODER DEN ERSATZ VON WAREN ODER DIENSTLEISTUNGEN, NUTZUNGS-, DATEN- ODER GEWINNVERLUST ODER UNTERBRECHUNG DES GESCHÄFTSBETRIEBS), DIE SICH UNABHÄNGIG VON DER URSACHE UND BELIEBIGER THEORETISCHER HAFTBARKEIT, OB VERTRAGLICH FESTGELEGT, PER KAUSALHAFTUNG ODER DELIKTSHAFTUNG (EINSCHLIESSLICH FAHRLÄSSIGKEIT ODER AUF ANDEREM WEGE), ERGEBEN, DIE IN IRGENDEINER ART UND WEISE AUS DER NUTZUNG DIESER SOFTWARE RESULTIEREN, SELBST WENN AUF DIE MÖGLICHKEIT DERARTIGER SCHÄDEN HINGEWIESEN WURDE.

NetApp behält sich das Recht vor, die hierin beschriebenen Produkte jederzeit und ohne Vorankündigung zu ändern. NetApp übernimmt keine Verantwortung oder Haftung für die Verwendung der hier beschriebenen Produkte, sofern nicht ausdrücklich in schriftlicher Form von NetApp angegeben. Die Verwendung oder der Erwerb dieses Produkts stellt keine Lizenzierung im Rahmen eines Patentrechts, Markenrechts oder eines anderen Rechts an geistigem Eigentum von NetApp dar.

Das in diesem Handbuch beschriebene Produkt kann durch eines oder mehrere US-amerikanische oder ausländische Patente oder Patentanmeldungen geschützt sein.

Die hierin enthaltenen Daten beziehen sich auf einen Handelsartikel (gemäß Definition in FAR 2.101) und sind Eigentum von NetApp, Inc. Die US-Regierung besitzt eine nicht-exklusive, nicht übertragbare, nicht unterlizenzierbare, weltweite, beschränkte und unwiderrufliche Lizenz zur Nutzung der Daten ausschließlich im Zusammenhang mit und zur Unterstützung des Vertrags mit der US-Regierung, im Rahmen dessen die Daten geliefert wurden.  Sofern hierin nicht anders angegeben, dürfen die Daten ohne vorherige schriftliche Genehmigung von NetApp, Inc. weder verwendet, offengelegt, reproduziert, verändert, aufgeführt noch angezeigt werden. Die Lizenzrechte der US-Regierung für das Verteidigungsministerium beschränken sich auf die in DFARS-Klausel 252.227-7015(b) genannten Rechte.
