---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'Sicherheit wird bei der Implementierung von Lösungen in vielen Kundenumgebungen zunehmend entscheidend.  Die Federal Information Processing Standards (FIPS) sind Standards für Computersicherheit und Interoperabilität.  Die nach FIPS 140-2 zertifizierte Verschlüsselung ruhender Daten ist Bestandteil der gesamten Sicherheitslösung.' 
---
= Elementcluster für FIPS-Laufwerke vorbereiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sicherheit wird bei der Implementierung von Lösungen in vielen Kundenumgebungen zunehmend entscheidend.  Die Federal Information Processing Standards (FIPS) sind Standards für Computersicherheit und Interoperabilität.  Die nach FIPS 140-2 zertifizierte Verschlüsselung ruhender Daten ist Bestandteil der gesamten Sicherheitslösung.

Um die Aktivierung der FIPS-Laufwerksfunktion vorzubereiten, sollten Sie vermeiden, Knoten zu mischen, bei denen einige FIPS-Laufwerke unterstützen und andere nicht.

Ein Cluster gilt als FIPS-konform, wenn folgende Bedingungen erfüllt sind:

* Alle Laufwerke sind FIPS-zertifiziert.
* Alle Knoten sind FIPS-Laufwerksknoten.
* Die Verschlüsselung ruhender Daten (EAR) ist aktiviert.
* Die FIPS-Laufwerksfunktion ist aktiviert.  Alle Laufwerke und Knoten müssen FIPS-fähig sein und die Verschlüsselung ruhender Daten muss aktiviert sein, um die FIPS-Laufwerksfunktion aktivieren zu können.

