---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'Sie können das Standard-Administratorkennwort der Intelligent Platform Management Interface (IPMI) ändern, sobald Sie über Remote-IPMI-Zugriff auf den Knoten verfügen.  Dies sollten Sie gegebenenfalls tun, falls es Installationsaktualisierungen gibt.' 
---
= Ändern des Standard-IPMI-Passworts für Knoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Standard-Administratorkennwort der Intelligent Platform Management Interface (IPMI) ändern, sobald Sie über Remote-IPMI-Zugriff auf den Knoten verfügen.  Dies sollten Sie gegebenenfalls tun, falls es Installationsaktualisierungen gibt.

Einzelheiten zur Konfiguration des IPM-Zugriffs für Knoten finden Sie unterlink:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["IPMI für jeden Knoten konfigurieren"^] Die

Sie können das IPM-Passwort für diese Knoten ändern:

* H410S-Knoten
* H610S-Knoten




== Ändern Sie das Standard-IPMI-Passwort für H410S-Knoten.

Sie sollten das Standardkennwort für das IPMI-Administratorkonto auf jedem Speicherknoten ändern, sobald Sie den IPMI-Netzwerkport konfiguriert haben.

.Was du brauchst
Sie sollten die IPMI-IP-Adresse für jeden Speicherknoten konfiguriert haben.

.Schritte
. Öffnen Sie einen Webbrowser auf einem Computer, der auf das IPMI-Netzwerk zugreifen kann, und rufen Sie die IPMI-IP-Adresse des Knotens auf.
. Geben Sie den Benutzernamen ein `ADMIN` und Passwort `ADMIN` im Anmeldefenster.
. Klicken Sie nach dem Einloggen auf die Registerkarte *Konfiguration*.
. Klicken Sie auf *Benutzer*.
. Wählen Sie die `ADMIN` Benutzer und klicken Sie auf *Benutzer bearbeiten*.
. Aktivieren Sie das Kontrollkästchen *Passwort ändern*.
. Geben Sie in den Feldern *Passwort* und *Passwort bestätigen* ein neues Passwort ein.
. Klicken Sie auf *Ändern* und anschließend auf *OK*.
. Wiederholen Sie diese Prozedur für alle anderen H410S-Knoten mit Standard-IPMI-Passwörtern.




== Ändern Sie das Standard-IPMI-Passwort für H610S-Knoten.

Sie sollten das Standardkennwort für das IPMI-Administratorkonto auf jedem Speicherknoten ändern, sobald Sie den IPMI-Netzwerkport konfiguriert haben.

.Was du brauchst
Sie sollten die IPMI-IP-Adresse für jeden Speicherknoten konfiguriert haben.

.Schritte
. Öffnen Sie einen Webbrowser auf einem Computer, der auf das IPMI-Netzwerk zugreifen kann, und rufen Sie die IPMI-IP-Adresse des Knotens auf.
. Geben Sie den Benutzernamen ein `root` und Passwort `calvin` im Anmeldefenster.
. Nach dem Einloggen klicken Sie auf das Menünavigationssymbol oben links auf der Seite, um die Seitenleiste zu öffnen.
. Klicken Sie auf *Einstellungen*.
. Klicken Sie auf *Benutzerverwaltung*.
. Wählen Sie den *Administrator*-Benutzer aus der Liste aus.
. Aktivieren Sie das Kontrollkästchen *Passwort ändern*.
. Geben Sie in den Feldern *Passwort* und *Passwort bestätigen* ein neues, sicheres Passwort ein.
. Klicken Sie unten auf der Seite auf *Speichern*.
. Wiederholen Sie diese Prozedur für alle anderen H610S-Knoten mit Standard-IPMI-Passwörtern.




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

