---
permalink: storage/task_data_protection_clone_a_volume_from_a_snapshot.html 
sidebar: sidebar 
keywords: clone volume from snapshot, volume snapshots, clone 
summary: Sie können ein neues Volume aus einem Snapshot eines Volumes erstellen.  Wenn Sie dies tun, verwendet das System die Snapshot-Informationen, um ein neues Volume zu klonen, wobei die Daten verwendet werden, die sich zum Zeitpunkt der Erstellung des Snapshots auf dem Volume befanden.  Dieser Prozess speichert Informationen über andere Snapshots des Volumes im neu erstellten Volume. 
---
= Ein Volume aus einem Snapshot klonen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein neues Volume aus einem Snapshot eines Volumes erstellen.  Wenn Sie dies tun, verwendet das System die Snapshot-Informationen, um ein neues Volume zu klonen, wobei die Daten verwendet werden, die sich zum Zeitpunkt der Erstellung des Snapshots auf dem Volume befanden.  Dieser Prozess speichert Informationen über andere Snapshots des Volumes im neu erstellten Volume.

. Klicken Sie auf *Datenschutz* > *Schnappschüsse*.
. Klicken Sie auf das Symbol *Aktionen* für den Snapshot, den Sie für die Volume-Klonung verwenden möchten.
. Klicken Sie im daraufhin angezeigten Menü auf *Volume aus Snapshot klonen*.
. Geben Sie im Dialogfeld *Volume aus Snapshot klonen* einen *Volume-Namen* ein.
. Wählen Sie eine *Gesamtgröße* und die Größeneinheiten für das neue Volumen aus.
. Wählen Sie einen *Zugriffstyp* für das Volume aus.
. Wählen Sie aus der Liste ein *Konto* aus, das dem neuen Volume zugeordnet werden soll.
. Klicken Sie auf *Klonen starten*.

