---
permalink: storage/task_data_manage_volumes_deleting_a_qos_policy.html 
sidebar: sidebar 
keywords: qos policy, delete, volumes 
summary: Sie können eine QoS-Richtlinie löschen, wenn sie nicht mehr benötigt wird.  Wenn Sie eine QoS-Richtlinie löschen, behalten alle mit der Richtlinie verknüpften Volumes die QoS-Einstellungen bei, werden aber nicht mehr mit einer Richtlinie verknüpft. 
---
= Löschen einer QoS-Richtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine QoS-Richtlinie löschen, wenn sie nicht mehr benötigt wird.  Wenn Sie eine QoS-Richtlinie löschen, behalten alle mit der Richtlinie verknüpften Volumes die QoS-Einstellungen bei, werden aber nicht mehr mit einer Richtlinie verknüpft.


NOTE: Wenn Sie stattdessen ein Volume von einer QoS-Richtlinie trennen möchten, können Sie die QoS-Einstellungen für dieses Volume auf benutzerdefiniert ändern.

. Wählen Sie *Verwaltung* > *QoS-Richtlinien*.
. Klicken Sie auf das Aktionssymbol für die QoS-Richtlinie, die Sie löschen möchten.
. Im daraufhin angezeigten Menü wählen Sie *Löschen*.
. Bestätigen Sie die Aktion.




== Weitere Informationen

xref:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.adoc[Entfernen Sie die QoS-Richtlinienzuordnung eines Volumes]
