---
permalink: storage/task_system_manage_nodes_view_individual_node_details.html 
sidebar: sidebar 
keywords: nodes, view, details, vlan, mip, cip, sip, virtual id 
summary: Sie können Details zu einzelnen Knoten anzeigen, wie z. B. Service-Tags, Laufwerksdetails und Grafiken zur Auslastung und Laufwerksstatistik.  Auf der Seite „Knoten“ des Cluster-Tabs finden Sie die Spalte „Version“, in der Sie die Softwareversion jedes Knotens anzeigen können. 
---
= Knotendetails anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Details zu einzelnen Knoten anzeigen, wie z. B. Service-Tags, Laufwerksdetails und Grafiken zur Auslastung und Laufwerksstatistik.  Auf der Seite „Knoten“ des Cluster-Tabs finden Sie die Spalte „Version“, in der Sie die Softwareversion jedes Knotens anzeigen können.

.Schritte
. Klicken Sie auf *Cluster* > *Knoten*.
. Um die Details eines bestimmten Knotens anzuzeigen, klicken Sie auf das Symbol *Aktionen* für den Knoten.
. Klicken Sie auf *Details anzeigen*.
. Überprüfen Sie die Knotendetails:
+
** *Knoten-ID*: Die vom System generierte ID für den Knoten.
** *Knotenname*: Der Hostname des Knotens.
** *Knotenrolle*: Die Rolle, die der Knoten im Cluster innehat. Mögliche Werte:
+
*** Cluster-Master: Der Knoten, der clusterweite administrative Aufgaben ausführt und den MVIP und SVIP enthält.
*** Ensemble-Knoten: Ein Knoten, der am Cluster teilnimmt.  Je nach Clustergröße gibt es entweder 3 oder 5 Ensemble-Knoten.
*** Fibre Channel: Ein Knoten im Cluster.


** *Knotentyp*: Der Modelltyp des Knotens.
** *Aktive Laufwerke*: Die Anzahl der aktiven Laufwerke im Knoten.
** *Knotenauslastung*: Der Prozentsatz der Knotenauslastung basierend auf nodeHeat.  Der angezeigte Wert ist recentPrimaryTotalHeat als Prozentsatz.  Verfügbar ab Element 12.8.
** *Management IP*: Die Management-IP-Adresse (MIP), die dem Knoten für 1GbE- oder 10GbE-Netzwerkadministrationsaufgaben zugewiesen ist.
** *Cluster-IP*: Die Cluster-IP-Adresse (CIP), die dem Knoten zugewiesen ist und für die Kommunikation zwischen Knoten im selben Cluster verwendet wird.
** *Speicher-IP*: Die Speicher-IP-Adresse (SIP), die dem Knoten zugewiesen ist und für die iSCSI-Netzwerkerkennung und den gesamten Datennetzwerkverkehr verwendet wird.
** *Management VLAN ID*: Die virtuelle ID für das Management-LAN.
** *Storage VLAN ID*: Die virtuelle ID für das lokale Speichernetzwerk.
** *Version*: Die auf jedem Knoten laufende Softwareversion.
** *Replikationsport*: Der Port, der auf den Knoten für die Remote-Replikation verwendet wird.
** *Service Tag*: Die eindeutige Service-Tag-Nummer, die dem Knoten zugewiesen ist.
** *Benutzerdefinierte Schutzdomäne*: Die dem Knoten zugewiesene benutzerdefinierte Schutzdomäne.



