---
permalink: storage/task_data_manage_volumes_work_with_volumes_task.html 
sidebar: sidebar 
keywords: volumes, work, storage, iscsi, fc, cluster data management, overview of functions 
summary: Das SolidFire -System stellt Speicherplatz mithilfe von Volumes bereit.  Volumes sind Blockgeräte, auf die über das Netzwerk von iSCSI- oder Fibre-Channel-Clients zugegriffen wird.  Auf der Seite „Volumes“ im Menüband „Verwaltung“ können Sie Volumes auf einem Knoten erstellen, ändern, klonen und löschen.  Sie können auch Statistiken über Datenvolumen, Bandbreite und E/A-Auslastung einsehen. 
---
= Arbeiten mit Volumina
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SolidFire -System stellt Speicherplatz mithilfe von Volumes bereit.  Volumes sind Blockgeräte, auf die über das Netzwerk von iSCSI- oder Fibre-Channel-Clients zugegriffen wird.  Auf der Seite „Volumes“ im Menüband „Verwaltung“ können Sie Volumes auf einem Knoten erstellen, ändern, klonen und löschen.  Sie können auch Statistiken über Datenvolumen, Bandbreite und E/A-Auslastung einsehen.



== Weitere Informationen

* link:concept_data_manage_volumes_quality_of_service_policies.html["Richtlinien zur Servicequalität verwalten"]
* link:task_data_manage_volumes.html#create-a-volume["Erstellen eines Volumes"]
* link:task_data_manage_volumes.html#view-volume-details["Details zur individuellen Lautstärkeleistung anzeigen"]
* link:task_data_manage_volumes.html#edit-active-volumes["Aktive Volumes bearbeiten"]
* link:task_data_manage_volumes.html#delete-a-volume["Löschen eines Volumes"]
* link:task_data_manage_volumes.html#restore-a-deleted-volume["Wiederherstellen eines gelöschten Volumes"]
* link:task_data_manage_volumes.html#purge-a-volume["Ein Volumen säubern"]
* link:task_data_manage_volumes.html#clone-a-volume["Klonen eines Volumes"]
* link:task_data_manage_volumes_assign_luns_to_fibre_channel_volumes.html["LUNs Fibre Channel-Volumes zuweisen"]
* link:task_data_manage_volumes_apply_a_qos_policy.html["Wenden Sie eine QoS-Richtlinie auf Volumes an"]
* link:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.html["Entfernen Sie die QoS-Richtlinienzuordnung eines Volumes"]

