---
permalink: storage/task-element-replication-create-relationship-element-destination.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, replication, snapmirror 
summary: Ab ONTAP 9.4 können Sie SnapMirror verwenden, um Snapshot-Kopien einer auf einer ONTAP Quelle erstellten LUN zurück auf ein Element-Ziel zu replizieren.  Möglicherweise verwenden Sie die LUN, um Daten von ONTAP auf die Element-Software zu migrieren. 
---
= Erstellen Sie eine Beziehung von einer ONTAP -Quelle zu einem Element-Ziel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.4 können Sie SnapMirror verwenden, um Snapshot-Kopien einer auf einer ONTAP Quelle erstellten LUN zurück auf ein Element-Ziel zu replizieren.  Möglicherweise verwenden Sie die LUN, um Daten von ONTAP auf die Element-Software zu migrieren.

.Bevor Sie beginnen
* Der Element-Zielknoten muss für ONTAP zugänglich gemacht worden sein.
* Das Element-Volume muss für die SnapMirror Replikation aktiviert sein.


.Informationen zu diesem Vorgang
Sie müssen den Zielpfad des Elements in folgender Form angeben: `<hostip:>/lun/<name>` , wobei "`lun`" die eigentliche Zeichenkette "`lun`" ist und `name` ist der Name des Element-Volumes.

Die Replikationsregeln lauten wie folgt:

* Die Replikationsbeziehung muss eine Richtlinie vom Typ "`async-mirror`" aufweisen.
+
Sie können eine Standardrichtlinie oder eine benutzerdefinierte Richtlinie verwenden.

* Es werden ausschließlich iSCSI-LUNs unterstützt.
* Es ist nicht möglich, mehr als eine LUN von einem ONTAP -Volume auf ein Element-Volume zu replizieren.
* Eine LUN kann nicht von einem ONTAP -Volume auf mehrere Element-Volumes repliziert werden.


.Schritt
. Erstellen einer Replikationsbeziehung von einer ONTAP -Quelle zu einem Element-Ziel:
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`

+
Die vollständige Befehlssyntax finden Sie in der Manpage.

+
Das folgende Beispiel erstellt eine SnapMirror DR-Beziehung unter Verwendung der Standardeinstellungen. `MirrorLatest` Politik:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
Das folgende Beispiel erstellt eine SnapMirror DR-Beziehung mithilfe der benutzerdefinierten Schnittstelle. `my_mirror` Politik:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


.Nach Abschluss
Verwenden Sie die `snapmirror show` Befehl zur Überprüfung, ob die SnapMirror -Beziehung erstellt wurde.  Die vollständige Befehlssyntax finden Sie in der Manpage.
