---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: Sie können einer bestehenden Volume-Zugriffsgruppe mehrere Initiatoren hinzufügen, um den Zugriff auf Volumes in der Volume-Zugriffsgruppe mit oder ohne CHAP-Authentifizierung zu ermöglichen. 
---
= Fügen Sie einer Volume-Zugriffsgruppe mehrere Initiatoren hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einer bestehenden Volume-Zugriffsgruppe mehrere Initiatoren hinzufügen, um den Zugriff auf Volumes in der Volume-Zugriffsgruppe mit oder ohne CHAP-Authentifizierung zu ermöglichen.

Wenn Sie Initiatoren zu einer Volume-Zugriffsgruppe hinzufügen, haben die Initiatoren Zugriff auf alle Volumes in dieser Volume-Zugriffsgruppe.


TIP: Den Initiator für jedes Volume finden Sie, indem Sie auf das Symbol „Aktionen“ und anschließend in der Liste der aktiven Volumes auf „Details anzeigen“ für das jeweilige Volume klicken.

Sie können einer bestehenden Volume-Zugriffsgruppe mehrere Initiatoren hinzufügen, um den Zugriff auf Volumes zu ermöglichen und jedem Initiator innerhalb dieser Volume-Zugriffsgruppe eindeutige CHAP-Anmeldeinformationen zuzuweisen.  Dies ermöglicht es Ihnen, diese Option auf bereits vorhandene Datenträgerzugriffsgruppen anzuwenden.

Sie können initiatorbasierte CHAP-Attribute mithilfe eines API-Aufrufs zuweisen.  Um einen CHAP-Kontonamen und Anmeldeinformationen pro Initiator hinzuzufügen, müssen Sie den API-Aufruf ModifyInitiator verwenden, um CHAP-Zugriff und -Attribute zu entfernen und hinzuzufügen.

Weitere Einzelheiten finden Sie unterlink:../api/concept_element_api_about_the_api.html["Speicherverwaltung mit der Element-API"] .

.Schritte
. Klicken Sie auf *Management* > *Initiatoren*.
. Wählen Sie die Initiatoren aus, die Sie einer Zugriffsgruppe hinzufügen möchten.
. Klicken Sie auf die Schaltfläche *Massenaktionen*.
. Klicken Sie auf *Zur Datenträgerzugriffsgruppe hinzufügen*.
. Im Dialogfeld „Zur Datenträgerzugriffsgruppe hinzufügen“ wählen Sie eine Zugriffsgruppe aus der Liste *Datenträgerzugriffsgruppe* aus.
. Klicken Sie auf *Hinzufügen*.

