---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: Sie können festlegen, dass in bestimmten Abständen automatisch ein Snapshot eines oder mehrerer Volumes erstellt wird. 
---
= Erstellen Sie einen Snapshot-Zeitplan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können festlegen, dass in bestimmten Abständen automatisch ein Snapshot eines oder mehrerer Volumes erstellt wird.

Wenn Sie einen Snapshot-Zeitplan konfigurieren, können Sie zwischen Zeitintervallen wählen, die auf Wochentagen oder Monatstagen basieren.  Sie können auch einen wiederkehrenden Zeitplan erstellen und die Tage, Stunden und Minuten vor dem nächsten Snapshot angeben.

Wenn Sie einen Snapshot für einen Zeitraum planen, der nicht durch 5 Minuten teilbar ist, wird der Snapshot zum nächsten Zeitpunkt ausgeführt, der durch 5 Minuten teilbar ist.  Wenn Sie beispielsweise einen Snapshot für 12:42:00 UTC planen, wird er um 12:45:00 UTC ausgeführt.  Sie können nicht planen, dass ein Snapshot in Intervallen von weniger als 5 Minuten ausgeführt wird.

Ab Element 12.5 können Sie die serielle Erstellung aktivieren und über die Benutzeroberfläche auswählen, ob die Snapshots nach dem Prinzip „First-In-First-Out“ (FIFO) gespeichert werden sollen.

* Die Option *Serielle Erstellung aktivieren* legt fest, dass jeweils nur ein Snapshot repliziert wird.  Die Erstellung eines neuen Snapshots schlägt fehl, wenn die Replikation eines vorherigen Snapshots noch im Gange ist.  Wenn das Kontrollkästchen nicht ausgewählt ist, ist die Erstellung eines Snapshots zulässig, während die Replikation eines anderen Snapshots noch im Gange ist.
* Die *FIFO*-Option bietet die Möglichkeit, eine konstante Anzahl der neuesten Snapshots beizubehalten.  Wenn das Kontrollkästchen aktiviert ist, werden Snapshots nach dem FIFO-Prinzip gespeichert.  Sobald die Warteschlange der FIFO-Snapshots ihre maximale Tiefe erreicht hat, wird der älteste FIFO-Snapshot verworfen, wenn ein neuer FIFO-Snapshot eingefügt wird.


.Schritte
. Wählen Sie *Datenschutz* > *Zeitpläne*.
. Wählen Sie *Zeitplan erstellen*.
. Geben Sie im Feld *Volume IDs CSV* eine einzelne Volume-ID oder eine durch Kommas getrennte Liste von Volume-IDs ein, die in den Snapshot-Vorgang einbezogen werden sollen.
. Geben Sie einen neuen Terminnamen ein.
. Wählen Sie einen Zeitplantyp aus und legen Sie den Zeitplan anhand der bereitgestellten Optionen fest.
. *Optional:* Wählen Sie *Wiederkehrender Zeitplan*, um den Snapshot-Zeitplan unbegrenzt zu wiederholen.
. *Optional:* Geben Sie im Feld *Name des neuen Snapshots* einen Namen für den neuen Snapshot ein.
+
Wenn Sie das Feld leer lassen, verwendet das System Datum und Uhrzeit der Snapshot-Erstellung als Namen.

. *Optional:* Aktivieren Sie das Kontrollkästchen *Snapshots bei der Replikation berücksichtigen, wenn gekoppelt*, um sicherzustellen, dass die Snapshots bei der Replikation erfasst werden, wenn das übergeordnete Volume gekoppelt wird.
. *Optional:* Aktivieren Sie das Kontrollkästchen *Serielle Erstellung aktivieren*, um sicherzustellen, dass jeweils nur ein Snapshot repliziert wird.
. Um die Aufbewahrungsdauer für den Snapshot festzulegen, wählen Sie eine der folgenden Optionen aus:
+
** *Optional:* Aktivieren Sie das Kontrollkästchen *FIFO (First In First Out)*, um eine gleichbleibende Anzahl der neuesten Snapshots beizubehalten.
** Wählen Sie *Für immer behalten*, um den Snapshot auf unbestimmte Zeit im System zu speichern.
** Wählen Sie *Aufbewahrungsdauer festlegen* und verwenden Sie die Datums-Drehfelder, um eine Zeitspanne auszuwählen, für die das System den Snapshot aufbewahrt.


. Wählen Sie *Zeitplan erstellen*.

