---
permalink: storage/task_intro_limit_results_by_using_filters.html 
sidebar: sidebar 
keywords: filter, filtering, sorting information, viewing lists, unfiltered list 
summary: 'Sie können die Listeninformationen auf Seiten in der Element-Benutzeroberfläche filtern.  Beim Anzeigen von Listen (wie z. B. Volumes und Snapshots) können Sie einen oder mehrere Filter hinzufügen, um die Informationen zu fokussieren und sie besser auf der Seite darzustellen.' 
---
= Ergebnisse mithilfe von Filtern einschränken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Listeninformationen auf Seiten in der Element-Benutzeroberfläche filtern.  Beim Anzeigen von Listen (wie z. B. Volumes und Snapshots) können Sie einen oder mehrere Filter hinzufügen, um die Informationen zu fokussieren und sie besser auf der Seite darzustellen.

. Klicken Sie beim Anzeigen von Listeninformationen auf *Filter*.
. Erweitern Sie das Feld *Filtern nach*.
. Wählen Sie aus dem am weitesten links stehenden Element im Feld eine Spalte aus, nach der gefiltert werden soll.
. Wählen Sie eine Einschränkung für die Spalte.
. Geben Sie einen Text ein, nach dem gefiltert werden soll.
. Klicken Sie auf *Hinzufügen*.
+
Das System wendet den neuen Filter auf die Informationen in der Liste an und speichert den neuen Filter vorübergehend im Feld „Filtern nach“.

. Um einen weiteren Filter hinzuzufügen, klicken Sie auf *Hinzufügen* und wählen Sie erneut den gewünschten Filter aus.
. Klicken Sie auf *Alle löschen*, um die Filterliste zu entfernen und die ungefilterten Listeninformationen anzuzeigen.

