---
permalink: storage/task_replication_pair_volumes_using_volume_id_or_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, volume id, replication 
summary: Der Pairing-Prozess beinhaltet das Koppeln zweier Volumes mithilfe einer Volume-ID oder eines Pairing-Schlüssels. 
---
= Koppeln Sie Volumes mithilfe einer Volume-ID oder eines Kopplungsschlüssels.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Pairing-Prozess beinhaltet das Koppeln zweier Volumes mithilfe einer Volume-ID oder eines Pairing-Schlüssels.

. Kombinieren Sie die Volumes, indem Sie eine der folgenden Methoden auswählen:
+
** Verwendung einer Volume-ID: Verwenden Sie diese Methode, wenn Sie über Cluster-Administratorrechte für beide Cluster verfügen, auf denen die Volumes gepaart werden sollen. Bei dieser Methode wird die Volume-ID des Volumes auf dem Remote-Cluster verwendet, um eine Verbindung herzustellen.
** Verwendung eines Kopplungsschlüssels: Verwenden Sie diese Methode, wenn Sie nur über Clusteradministratorzugriff auf den Quellcluster verfügen.  Diese Methode generiert einen Kopplungsschlüssel, der auf dem Remote-Cluster verwendet werden kann, um das Volume-Paar zu vervollständigen.
+

NOTE: Der Volume-Pairing-Schlüssel enthält eine verschlüsselte Version der Volume-Informationen und kann sensible Informationen enthalten.  Geben Sie diesen Schlüssel nur auf sichere Weise weiter.







== Weitere Informationen

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[Datenträger mithilfe einer Datenträger-ID koppeln]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[Datenträger mithilfe eines Kopplungsschlüssels koppeln]

