---
permalink: storage/task_replication_pair_cluster_using_mvip.html 
sidebar: sidebar 
keywords: pair clusters, mvip, connection 
summary: Sie können zwei Cluster für die Echtzeitreplikation koppeln, indem Sie die MVIP des einen Clusters verwenden, um eine Verbindung zum anderen Cluster herzustellen.  Für diese Methode ist der Zugriff auf beide Cluster als Clusteradministrator erforderlich.  Der Benutzername und das Passwort des Clusteradministrators werden verwendet, um den Clusterzugriff zu authentifizieren, bevor die Cluster gekoppelt werden können. 
---
= Paarcluster mithilfe von MVIP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können zwei Cluster für die Echtzeitreplikation koppeln, indem Sie die MVIP des einen Clusters verwenden, um eine Verbindung zum anderen Cluster herzustellen.  Für diese Methode ist der Zugriff auf beide Cluster als Clusteradministrator erforderlich.  Der Benutzername und das Passwort des Clusteradministrators werden verwendet, um den Clusterzugriff zu authentifizieren, bevor die Cluster gekoppelt werden können.

. Wählen Sie im lokalen Cluster *Datenschutz* > *Clusterpaare*.
. Klicken Sie auf *Cluster koppeln*.
. Klicken Sie auf *Start Pairing* und anschließend auf *Ja*, um anzugeben, dass Sie Zugriff auf den Remote-Cluster haben.
. Geben Sie die MVIP-Adresse des Remote-Clusters ein.
. Klicken Sie auf *Kopplung auf dem Remote-Cluster abschließen*.
+
Geben Sie im Fenster *Authentifizierung erforderlich* den Benutzernamen und das Kennwort des Clusteradministrators des Remote-Clusters ein.

. Wählen Sie auf dem Remote-Cluster *Datenschutz* > *Clusterpaare*.
. Klicken Sie auf *Cluster koppeln*.
. Klicken Sie auf *Kopplung abschließen*.
. Klicken Sie auf die Schaltfläche *Kopplung abschließen*.




== Weitere Informationen

* xref:task_replication_pair_cluster_using_pairing_key.adoc[Cluster mithilfe eines Paarungsschlüssels koppeln]
* https://www.youtube.com/watch?v=HbKxPZnNvn4&feature=youtu.be["Clusterpaarung mittels MVIP (Video)"]

