---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: Sie können ein Volume mit einem anderen Volume auf einem Remote-Cluster koppeln, wenn Sie über Cluster-Administratorrechte für den Remote-Cluster verfügen. 
---
= Datenträger mithilfe einer Datenträger-ID koppeln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume mit einem anderen Volume auf einem Remote-Cluster koppeln, wenn Sie über Cluster-Administratorrechte für beide Cluster verfügen, auf denen die Volumes gekoppelt werden sollen. Bei dieser Methode wird die Volume-ID des Volumes auf dem Remote-Cluster verwendet, um eine Verbindung herzustellen.

.Was du brauchst
* Stellen Sie sicher, dass die Cluster, die die Volumes enthalten, gepaart sind.
* Erstellen Sie ein neues Volume auf dem Remote-Cluster.
+

NOTE: Sie können eine Replikationsquelle und ein Replikationsziel nach dem Kopplungsprozess zuweisen.  Als Replikationsquelle oder -ziel kann jedes der beiden Volumes eines Volume-Paares dienen.  Sie sollten ein Zielvolume erstellen, das keine Daten enthält und die exakten Eigenschaften des Quellvolumes aufweist, wie z. B. Größe, Blockgrößeneinstellung für die Volumes (entweder 512e oder 4k) und QoS-Konfiguration.  Wenn Sie ein vorhandenes Volume als Replikationsziel zuweisen, werden die Daten auf diesem Volume überschrieben.  Das Zielvolumen kann größer oder gleich groß wie das Quellvolumen sein, aber es darf nicht kleiner sein.

* Kennen Sie die Ziel-Volume-ID.


.Schritte
. Wählen Sie *Verwaltung* > *Volumes*.
. Klicken Sie auf das Symbol *Aktionen* für das Volume, das Sie koppeln möchten.
. Klicken Sie auf *Paaren*.
. Im Dialogfeld *Lautstärke koppeln* wählen Sie *Kopplung starten*.
. Wählen Sie *Ich will*, um anzuzeigen, dass Sie Zugriff auf den Remote-Cluster haben.
. Wählen Sie einen *Replikationsmodus* aus der Liste aus:
+
** *Echtzeit (Asynchron)*: Schreibvorgänge werden dem Client erst bestätigt, nachdem sie im Quellcluster abgeschlossen wurden.
** *Echtzeit (synchron)*: Schreibvorgänge werden dem Client bestätigt, nachdem sie sowohl im Quell- als auch im Zielcluster abgeschlossen wurden.
** *Nur Snapshots*: Es werden nur Snapshots repliziert, die auf dem Quellcluster erstellt wurden.  Aktive Schreibvorgänge vom Quellvolume werden nicht repliziert.


. Wählen Sie einen Remote-Cluster aus der Liste aus.
. Wählen Sie eine Remote-Volume-ID.
. Klicken Sie auf *Kopplung starten*.
+
Das System öffnet einen Webbrowser-Tab, der eine Verbindung zur Element-Benutzeroberfläche des Remote-Clusters herstellt.  Möglicherweise müssen Sie sich mit den Anmeldeinformationen des Clusteradministrators beim Remote-Cluster anmelden.

. Wählen Sie in der Element-Benutzeroberfläche des Remote-Clusters die Option *Kopplung abschließen*.
. Bestätigen Sie die Details unter *Volume-Pairing bestätigen*.
. Klicken Sie auf *Kopplung abschließen*.
+
Nachdem Sie die Kopplung bestätigt haben, beginnen die beiden Cluster mit dem Prozess der Verbindung der Volumes für die Kopplung.  Während des Kopplungsvorgangs können Sie Meldungen in der Spalte *Volume-Status* des Fensters *Volume-Paare* sehen.  Die Lautstärkeanzeige `PausedMisconfigured` bis das Datenträgerpaar Quelle und Ziel zugewiesen ist.

+
Nach erfolgreichem Abschluss der Kopplung wird empfohlen, die Volumes-Tabelle zu aktualisieren, um die Option *Pair* aus der Liste *Actions* für das gekoppelte Volume zu entfernen.  Wenn Sie die Tabelle nicht aktualisieren, bleibt die Option *Paar* weiterhin auswählbar.  Wenn Sie die Option *Koppeln* erneut auswählen, öffnet sich ein neuer Tab, und da das Volume bereits gekoppelt ist, meldet das System Folgendes: `StartVolumePairing Failed: xVolumeAlreadyPaired` Fehlermeldung im Fenster *Lautstärke koppeln* der Element-UI-Seite.





== Weitere Informationen

* xref:reference_replication_volume_pairing_messages.adoc[Volume-Pairing-Nachrichten]
* xref:reference_replication_volume_pairing_warnings.adoc[Warnungen zur Lautstärkepaarung]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Weisen Sie gepaarten Volumes eine Replikationsquelle und ein Replikationsziel zu.]

