---
permalink: storage/task_data_protection_roll_back_a_volume_to_a_snapshot.html 
sidebar: sidebar 
keywords: volume to snapshot roll back, snapshot roll back, revert changes 
summary: Sie können ein Volume jederzeit auf einen früheren Snapshot zurücksetzen.  Dadurch werden alle Änderungen rückgängig gemacht, die seit der Erstellung des Snapshots am Volume vorgenommen wurden. 
---
= Ein Volume auf einen Snapshot zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume jederzeit auf einen früheren Snapshot zurücksetzen.  Dadurch werden alle Änderungen rückgängig gemacht, die seit der Erstellung des Snapshots am Volume vorgenommen wurden.

.Schritte
. Klicken Sie auf *Datenschutz* > *Schnappschüsse*.
. Klicken Sie auf das Symbol *Aktionen* für den Snapshot, den Sie für das Volume-Rollback verwenden möchten.
. Im daraufhin angezeigten Menü wählen Sie *Rollback Volume To Snapshot*.
. *Optional:* Um den aktuellen Zustand des Volumes zu speichern, bevor auf den Snapshot zurückgegriffen wird:
+
.. Im Dialogfeld *Rollback auf Snapshot* wählen Sie *Aktuellen Zustand des Volumes als Snapshot speichern*.
.. Geben Sie einen Namen für den neuen Snapshot ein.


. Klicken Sie auf *Rollback-Snapshot*.

