---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'Sie können Virtual Routing and Forwarding (VRF) aktivieren, wodurch mehrere Instanzen einer Routingtabelle in einem Router existieren und gleichzeitig funktionieren können.  Diese Funktionalität ist nur für Speichernetzwerke verfügbar.' 
---
= Virtuelles Routing und Weiterleitung aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Virtual Routing and Forwarding (VRF) aktivieren, wodurch mehrere Instanzen einer Routingtabelle in einem Router existieren und gleichzeitig funktionieren können.  Diese Funktionalität ist nur für Speichernetzwerke verfügbar.

VRF kann nur beim Erstellen eines VLANs aktiviert werden.  Wenn Sie wieder auf Nicht-VRF umstellen möchten, müssen Sie das VLAN löschen und neu erstellen.

. Klicken Sie auf *Cluster* > *Netzwerk*.
. Um VRF in einem neuen VLAN zu aktivieren, wählen Sie *VLAN erstellen*.
+
.. Geben Sie die relevanten Informationen für das neue VRF/VLAN ein.  Siehe Hinzufügen eines virtuellen Netzwerks.
.. Aktivieren Sie das Kontrollkästchen *VRF aktivieren*.
.. *Optional*: Geben Sie ein Gateway ein.


. Klicken Sie auf *VLAN erstellen*.




== Weitere Informationen

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Fügen Sie ein virtuelles Netzwerk hinzu]
