---
permalink: storage/task_data_protection_back_up_volume_to_amazon_s3.html 
sidebar: sidebar 
keywords: volume backup, amazon s3 object store 
summary: Sie können Volumes in externen Objektspeichern sichern, die mit Amazon S3 kompatibel sind. 
---
= Sichern eines Volumes in einem Amazon S3-Objektspeicher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Volumes in externen Objektspeichern sichern, die mit Amazon S3 kompatibel sind.

. Klicken Sie auf *Verwaltung* > *Volumes*.
. Klicken Sie auf das Aktionssymbol für das Volume, das Sie sichern möchten.
. Klicken Sie im daraufhin angezeigten Menü auf *Backup to*.
. Im Dialogfeld *Integrierte Sicherung* wählen Sie unter *Sichern nach* die Option *S3* aus.
. Wählen Sie eine Option unter *Datenformat* aus:
+
** *Nativ*: Ein komprimiertes Format, das nur von SolidFire -Speichersystemen gelesen werden kann.
** *Unkomprimiert*: Ein unkomprimiertes Format, das mit anderen Systemen kompatibel ist.


. Geben Sie im Feld *Hostname* einen Hostnamen ein, der für den Zugriff auf den Objektspeicher verwendet werden soll.
. Geben Sie im Feld *Zugriffsschlüssel-ID* eine Zugriffsschlüssel-ID für das Konto ein.
. Geben Sie den geheimen Zugriffsschlüssel für das Konto im Feld *Geheimer Zugriffsschlüssel* ein.
. Geben Sie im Feld *S3 Bucket* den S3-Bucket an, in dem das Backup gespeichert werden soll.
. Geben Sie im Feld *Namensschild* einen Namen ein, der an das Präfix angehängt werden soll.
. Klicken Sie auf *Lesen starten*.

