---
permalink: storage/task-element-replication-update-replication-relationship-manually.html 
sidebar: sidebar 
keywords: update, replication, relationship, manually 
summary: Möglicherweise müssen Sie eine Replikationsbeziehung manuell aktualisieren, wenn eine Aktualisierung aufgrund eines Netzwerkfehlers fehlschlägt. 
---
= Aktualisieren einer Replikationsbeziehung manuell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie eine Replikationsbeziehung manuell aktualisieren, wenn eine Aktualisierung aufgrund eines Netzwerkfehlers fehlschlägt.

.Informationen zu diesem Vorgang
Sie müssen den Elementquellpfad im folgenden Format angeben: `<hostip:>/lun/<name>` , wobei "`lun`" die eigentliche Zeichenkette "`lun`" ist und `name` ist der Name des Element-Volumes.

.Schritte
. Eine Replikationsbeziehung manuell aktualisieren:
+
`snapmirror update -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Die vollständige Befehlssyntax finden Sie in der Manpage.

+
[NOTE]
====
Der Befehl schlägt fehl, wenn auf dem Quell- und Zielsystem keine gemeinsame Snapshot-Kopie existiert.  Verwenden `snapmirror initialize` um die Beziehung neu zu initialisieren.

====
+
Das folgende Beispiel aktualisiert die Beziehung zwischen dem Quellvolume `0005` an der IP-Adresse 10.0.0.11 und dem Zielvolumen `volA_dst` An `svm_backup` :

+
[listing]
----
cluster_src::> snapmirror update -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

