---
permalink: api/reference_element_api_disablefeature.html 
sidebar: sidebar 
keywords: SNMP,disable,disabling,DisableFeature,vvols,virtual volumes 
summary: Mit der Methode DisableFeature können Sie VolumeLoadBalanceOnActualIOPS deaktivieren. 
---
= Funktion deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `DisableFeature` Methode zum Deaktivieren `VolumeLoadBalanceOnActualIOPS` Besonderheit. `VolumeLoadBalanceOnActualIOPS` ist standardmäßig deaktiviert.

[NOTE]
====
Wenn Sie versuchen, eine andere Funktion zu deaktivieren, z. B. VVols, erscheint die folgende Fehlermeldung:

[listing]
----
{"error":{"code":500,"message":"VolumeLoadBalanceOnActualIOPS is the only feature that can be disabled","name":"xAPINotPermitted"},"id":null}
----
====


== Parameter

Diese Methode hat die folgenden Eingabeparameter.

[cols="1a,3a,1a,1a,1a"]
|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Besonderheit
 a| 
Eine Clusterfunktion deaktivieren.  Möglicher Wert:

* `VolumeLoadBalanceOnActualIOPS`: Deaktivieren Sie den Slice-Balancing auf Basis der tatsächlichen IOPS anstatt der minimalen IOPS.

 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "DisableFeature",
    "params": {
        "feature" : "VolumeLoadBalanceOnActualIOPS"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Neu seit Version

12,8
