---
permalink: setup/concept_setup_fc_configure_a_fibre_channel_node.html 
sidebar: sidebar 
keywords:  
summary: 'Fibre Channel-Knoten ermöglichen es Ihnen, den Cluster mit einem Fibre Channel-Netzwerk zu verbinden.  Fibre Channel-Knoten werden paarweise hinzugefügt und arbeiten im Aktiv-Aktiv-Modus (alle Knoten verarbeiten aktiv den Datenverkehr für den Cluster).  Cluster, auf denen die Element-Softwareversion 9.0 und höher läuft, unterstützen bis zu vier Knoten; Cluster, auf denen frühere Versionen laufen, unterstützen maximal zwei Knoten.' 
---
= Konfigurieren eines Fibre-Channel-Knotens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fibre Channel-Knoten ermöglichen es Ihnen, den Cluster mit einem Fibre Channel-Netzwerk zu verbinden.  Fibre Channel-Knoten werden paarweise hinzugefügt und arbeiten im Aktiv-Aktiv-Modus (alle Knoten verarbeiten aktiv den Datenverkehr für den Cluster).  Cluster, auf denen die Element-Softwareversion 9.0 und höher läuft, unterstützen bis zu vier Knoten; Cluster, auf denen frühere Versionen laufen, unterstützen maximal zwei Knoten.

Sie müssen sicherstellen, dass die folgenden Bedingungen erfüllt sind, bevor Sie einen Fibre Channel-Knoten konfigurieren:

* Mindestens zwei Fibre-Channel-Knoten sind mit Fibre-Channel-Switches verbunden.
* Alle SolidFire Fibre Channel-Ports sollten mit Ihrem Fibre Channel-Fabric verbunden sein.  Die vier SolidFire Bond10G-Netzwerkverbindungen sollten auf Switch-Ebene in einer LACP-Bondgruppe verbunden werden.  Dies ermöglicht die bestmögliche Gesamtleistung der Fibre-Channel-Systeme.
* Überprüfen und bestätigen Sie alle Best Practices für Fibre Channel-Cluster, die in diesem NetApp Knowledge Base-Artikel enthalten sind.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/SolidFire_FC_cluster_best_practice["Best Practices für SolidFire FC-Cluster"]



Die Schritte zur Netzwerk- und Clusterkonfiguration sind für Fibre-Channel-Knoten und Speicherknoten identisch.

Wenn Sie einen neuen Cluster mit Fibre Channel-Knoten und SolidFire -Speicherknoten erstellen, stehen Ihnen die weltweiten Portnamen (WWPN) der Knoten in der Element-Benutzeroberfläche zur Verfügung.  Sie können die WWPN-Adressen verwenden, um den Fibre Channel-Switch zu zonieren.

WWPNs werden im System registriert, wenn Sie einen neuen Cluster mit Knoten erstellen.  In der Element-Benutzeroberfläche finden Sie die WWPN-Adressen in der Spalte WWPN auf der Registerkarte FC-Ports, die Sie über die Registerkarte Cluster aufrufen.



== Weitere Informationen

xref:task_setup_fc_add_fibre_channel_nodes_to_a_cluster.adoc[Fügen Sie einem Cluster Fibre-Channel-Knoten hinzu.]

xref:task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.adoc[Erstellen Sie einen neuen Cluster mit Fibre-Channel-Knoten.]
