---
permalink: setup/task_setup_add_drives_to_a_cluster.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie einen Knoten zum Cluster hinzufügen oder neue Laufwerke in einem vorhandenen Knoten installieren, werden die Laufwerke automatisch als verfügbar registriert.  Sie müssen die Laufwerke dem Cluster entweder über die Element-Benutzeroberfläche oder die API hinzufügen, bevor sie am Cluster teilnehmen können. 
---
= Fügen Sie einem Cluster Laufwerke hinzu.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Knoten zum Cluster hinzufügen oder neue Laufwerke in einem vorhandenen Knoten installieren, werden die Laufwerke automatisch als verfügbar registriert.  Sie müssen die Laufwerke dem Cluster entweder über die Element-Benutzeroberfläche oder die API hinzufügen, bevor sie am Cluster teilnehmen können.

Laufwerke werden in der Liste „Verfügbare Laufwerke“ nicht angezeigt, wenn folgende Bedingungen erfüllt sind:

* Die Laufwerke befinden sich im Status „Aktiv“, „Wird entfernt“, „Wird gelöscht“ oder „Ausgefallen“.
* Der Knoten, zu dem das Laufwerk gehört, befindet sich im Status „Ausstehend“.


.Schritte
. Wählen Sie in der Element-Benutzeroberfläche *Cluster* > *Laufwerke*.
. Klicken Sie auf *Verfügbar*, um die Liste der verfügbaren Laufwerke anzuzeigen.
. Führen Sie einen der folgenden Schritte aus:
+
** Um einzelne Laufwerke hinzuzufügen, klicken Sie auf das Symbol *Aktionen* für das Laufwerk, das Sie hinzufügen möchten, und klicken Sie dann auf *Hinzufügen*.
** Um mehrere Laufwerke hinzuzufügen, wählen Sie die Kontrollkästchen der hinzuzufügenden Laufwerke aus, klicken Sie auf *Massenaktionen* und anschließend auf *Hinzufügen*.
+
....
== Find more information
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
....



