---
permalink: api/concept_element_api_ldap_api_methods.html 
sidebar: sidebar 
keywords: ldap,api,methods 
summary: 'Sie können das Lightweight Directory Access Protocol (LDAP) verwenden, um den Zugriff auf den Element-Speicher zu authentifizieren.  Die in diesem Abschnitt beschriebenen LDAP-API-Methoden ermöglichen Ihnen die Konfiguration des LDAP-Zugriffs auf den Speichercluster.' 
---
= LDAP-API-Methoden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Lightweight Directory Access Protocol (LDAP) verwenden, um den Zugriff auf den Element-Speicher zu authentifizieren.  Die in diesem Abschnitt beschriebenen LDAP-API-Methoden ermöglichen Ihnen die Konfiguration des LDAP-Zugriffs auf den Speichercluster.

* xref:reference_element_api_addldapclusteradmin.adoc[AddLdapClusterAdmin]
* xref:reference_element_api_enableldapauthentication.adoc[LDAP-Authentifizierung aktivieren]
* xref:reference_element_api_disableldapauthentication.adoc[LDAP-Authentifizierung deaktivieren]
* xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration]
* xref:reference_element_api_testldapauthentication.adoc[TestLdapAuthentication]




== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen der NetApp SolidFire und Element-Produkte"^]

