---
permalink: api/concept_element_api_snapshots_overview.html 
sidebar: sidebar 
keywords: snapshot,overview 
summary: Ein Volume-Snapshot ist eine Momentaufnahme eines Volumes.  Mit Snapshots können Sie ein Volume auf den Zustand zurücksetzen, in dem es sich zum Zeitpunkt der Erstellung des Snapshots befand. 
---
= Momentaufnahmen – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Volume-Snapshot ist eine Momentaufnahme eines Volumes.  Mit Snapshots können Sie ein Volume auf den Zustand zurücksetzen, in dem es sich zum Zeitpunkt der Erstellung des Snapshots befand.

Sie können Volume-Snapshots gruppieren, sodass zusammengehörige Volumes auf einheitliche Weise gesichert oder wiederhergestellt werden können.  Ein Gruppen-Snapshot erfasst ein Momentaufnahmebild aller Volumenschnittdateien.  Anschließend können Sie das Image verwenden, um eine Gruppe von Volumes auf einen früheren Zeitpunkt zurückzusetzen und sicherzustellen, dass alle Daten über alle Volumes in der Gruppe hinweg konsistent sind.

Sie können festlegen, dass Volume-Snapshots in definierten Intervallen automatisch erstellt werden.  Sie können Intervalle nach Zeit, Wochentagen oder Monatstagen definieren.  Sie können auch geplante Snapshots verwenden, um sicherzustellen, dass Snapshots zu Archivierungszwecken auf einem entfernten Speicher gesichert werden.



== Weitere Informationen

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen der NetApp SolidFire und Element-Produkte"^]

