---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: Mit der Methode ListVolumeStatsByVolumeAccessGroup können Sie die gesamten Aktivitätsmessungen für alle Datenträger auflisten, die Mitglieder der angegebenen Datenträgerzugriffsgruppen sind. 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVolumeStatsByVolumeAccessGroup` Methode zur Auflistung der gesamten Aktivitätsmessungen für alle Datenträger, die Mitglieder der angegebenen Datenträgerzugriffsgruppen sind.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Virtuelle Volumes einbeziehen
 a| 
Virtuelle Volumes werden standardmäßig in die Antwort einbezogen.  Um virtuelle Volumes auszuschließen, auf „false“ setzen.
 a| 
boolescher Wert
 a| 
true
 a| 
Nein



 a| 
volumeAccessGroups
 a| 
Ein Array von VolumeAccessGroupIDs, für die die Volumenaktivität zurückgegeben wird.  Wird dieser Parameter weggelassen, werden Statistiken für alle Datenträgerzugriffsgruppen zurückgegeben.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
volumeStats
 a| 
Liste der Volumenaktivitätsinformationen für alle Volumen in der angegebenen Volumenzugriffsgruppe.*Hinweis:* Das Element volumeID ist für jeden Eintrag 0, da die Werte die Summe aller dem Konto gehörenden Volumen darstellen.
 a| 
xref:reference_element_api_volumestats.adoc[volumeStats]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== Neu seit Version

9,6
