---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: Mit der Methode ListEvents können Sie die im Cluster erkannten Ereignisse auflisten, sortiert vom ältesten zum neuesten. 
---
= ListEvents
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListEvents` Methode zum Auflisten der im Cluster erkannten Ereignisse, sortiert vom ältesten zum neuesten.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Laufwerk-ID
 a| 
Gibt an, dass nur Ereignisse mit dieser Laufwerks-ID zurückgegeben werden.
 a| 
ganze Zahl
 a| 
0
 a| 
Nein



 a| 
endEventID
 a| 
Gibt das Ende eines Bereichs von Ereignis-IDs an, die zurückgegeben werden sollen.
 a| 
ganze Zahl
 a| 
(unbegrenzt)
 a| 
Nein



 a| 
endPublishTime
 a| 
Gibt an, dass nur Ereignisse zurückgegeben werden, die vor diesem Zeitpunkt veröffentlicht wurden.
 a| 
Schnur
 a| 
0
 a| 
Nein



 a| 
endReportTime
 a| 
Gibt an, dass nur Ereignisse zurückgegeben werden, die vor diesem Zeitpunkt gemeldet wurden.
 a| 
Schnur
 a| 
0
 a| 
Nein



 a| 
Ereignistyp
 a| 
Gibt den Typ der zurückzugebenden Ereignisse an.  Sehenxref:reference_element_api_event.adoc[Ereignis] für mögliche Ereignistypen.
 a| 
Schnur
 a| 
0
 a| 
Nein



 a| 
maxEvents
 a| 
Gibt die maximale Anzahl der zurückzugebenden Ereignisse an.
 a| 
ganze Zahl
 a| 
(unbegrenzt)
 a| 
Nein



 a| 
Knoten-ID
 a| 
Gibt an, dass nur Ereignisse mit dieser Knoten-ID zurückgegeben werden.
 a| 
ganze Zahl
 a| 
 a| 



 a| 
Service-ID
 a| 
Gibt an, dass nur Ereignisse mit dieser Dienst-ID zurückgegeben werden.
 a| 
 a| 
 a| 



 a| 
startEventID
 a| 
Kennzeichnet den Beginn einer Reihe von Ereignissen, die zurückkehren.
 a| 
ganze Zahl
 a| 
0
 a| 
Nein



 a| 
Startzeit für die Veröffentlichung
 a| 
Gibt an, dass nur Ereignisse zurückgegeben werden, die nach diesem Zeitpunkt veröffentlicht wurden.
 a| 
Schnur
 a| 
0
 a| 
Nein



 a| 
startReportTime
 a| 
Gibt an, dass nur Ereignisse zurückgegeben werden, die nach diesem Zeitpunkt gemeldet werden.
 a| 
Schnur
 a| 
0
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Veranstaltungen
 a| 
Veranstaltungsliste.
 a| 
xref:reference_element_api_event.adoc[Ereignis]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Neu seit Version

9,6
