---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: Mit der Methode ListDriveStats können Sie die Aktivitätsmessungen auf hoher Ebene für mehrere Laufwerke im Cluster auflisten.  Standardmäßig liefert diese Methode Statistiken für alle Laufwerke im Cluster, und diese Messwerte sind kumulativ seit dem Hinzufügen des Laufwerks zum Cluster.  Einige der von dieser Methode zurückgegebenen Werte sind spezifisch für Blocklaufwerke, andere wiederum spezifisch für Metadatenlaufwerke. 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListDriveStats` Methode zur Auflistung von Aktivitätsmessungen auf hoher Ebene für mehrere Laufwerke im Cluster.  Standardmäßig liefert diese Methode Statistiken für alle Laufwerke im Cluster, und diese Messwerte sind kumulativ seit dem Hinzufügen des Laufwerks zum Cluster.  Einige der von dieser Methode zurückgegebenen Werte sind spezifisch für Blocklaufwerke, andere wiederum spezifisch für Metadatenlaufwerke.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Laufwerke
 a| 
Liste der Laufwerks-IDs (driveID), für die Laufwerksstatistiken abgerufen werden sollen.  Wenn Sie diesen Parameter weglassen, werden Messwerte für alle Laufwerke zurückgegeben.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
Fahrstatistik
 a| 
Liste der Laufwerksaktivitätsinformationen für jedes Laufwerk.
 a| 
xref:reference_element_api_drivestats.adoc[Fahrstatistik]Array



 a| 
Fehler
 a| 
Diese Liste enthält die Laufwerks-ID und die zugehörige Fehlermeldung.  Es ist immer vorhanden und leer, wenn keine Fehler vorliegen.
 a| 
JSON-Objektarray

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
