---
permalink: api/reference_element_api_createkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,creating,create 
summary: 'Mit der Methode CreateKeyProviderKmip können Sie einen KMIP-Schlüsselanbieter (Key Management Interoperability Protocol) mit dem angegebenen Namen erstellen.  Ein Schlüsselanbieter definiert einen Mechanismus und einen Speicherort zum Abrufen von Authentifizierungsschlüsseln.  Wenn Sie einen neuen KMIP-Schlüsselanbieter erstellen, sind diesem keine KMIP-Schlüsselserver zugewiesen.  Um einen KMIP-Schlüsselserver zu erstellen, verwenden Sie die Methode CreateKeyServerKmip.  Informationen zur Zuordnung zu einem Provider finden Sie unter AddKeyServerToProviderKmip.' 
---
= CreateKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `CreateKeyProviderKmip` Methode zum Erstellen eines KMIP-Schlüsselanbieters (Key Management Interoperability Protocol) mit dem angegebenen Namen.  Ein Schlüsselanbieter definiert einen Mechanismus und einen Speicherort zum Abrufen von Authentifizierungsschlüsseln.  Wenn Sie einen neuen KMIP-Schlüsselanbieter erstellen, sind diesem keine KMIP-Schlüsselserver zugewiesen.  Um einen KMIP-Schlüsselserver zu erstellen, verwenden Sie den `CreateKeyServerKmip` Verfahren.  Um es einem Anbieter zuzuordnen, siehe `AddKeyServerToProviderKmip` Die



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
keyProviderName
 a| 
Der Name, der dem erstellten KMIP-Schlüsselanbieter zugeordnet werden soll.  Dieser Name dient nur zu Darstellungszwecken und muss nicht eindeutig sein.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
kmipKeyProvider
 a| 
Ein Objekt, das Details zum neu erstellten Schlüsselanbieter enthält.
 a| 
link:reference_element_api_keyproviderkmip.html["KeyProviderKmip"]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "CreateKeyProviderKmip",
  "params": {
    "keyProviderName": "ProviderName",
    },
"id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result":
      {
    "kmipKeyProvider": {
        "keyProviderName": "ProviderName",
        "keyProviderIsActive": true,
        "kmipCapabilities": "SSL",
        "keyServerIDs": [
            15
        ],
        "keyProviderID": 1
    }
}
}
----


== Neu seit Version

11,7
