---
permalink: api/reference_element_api_enableidpauthentication.html 
sidebar: sidebar 
keywords: IdP,idp,authentication,enable 
summary: Mit der Methode EnableIdpAuthentication können Sie die Unterstützung für die Authentifizierung mit Drittanbieter-IdPs für den Cluster aktivieren.  Sobald die IdP-Authentifizierung aktiviert ist, können LDAP- und Cluster-Administratoren nicht mehr über die unterstützten Benutzeroberflächen auf den Cluster zugreifen, und alle aktiven authentifizierten Sitzungen werden ungültig bzw. getrennt.  Nur Benutzer, die von Drittanbieter-Identitätsanbietern authentifiziert wurden, können über unterstützte Benutzeroberflächen auf den Cluster zugreifen. 
---
= EnableIdpAuthentication
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `EnableIdpAuthentication` Methode zur Aktivierung der Unterstützung für die Authentifizierung mittels Drittanbieter-IdPs für den Cluster.  Sobald die IdP-Authentifizierung aktiviert ist, können LDAP- und Cluster-Administratoren nicht mehr über die unterstützten Benutzeroberflächen auf den Cluster zugreifen, und alle aktiven authentifizierten Sitzungen werden ungültig gemacht/getrennt.  Nur Benutzer, die von Drittanbieter-Identitätsanbietern authentifiziert wurden, können über unterstützte Benutzeroberflächen auf den Cluster zugreifen.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
idpConfigurationID
 a| 
UUID für die IdP-Konfiguration des Drittanbieters.  Wenn nur eine IdP-Konfiguration existiert, wird standardmäßig diese Konfiguration aktiviert.  Wenn Sie nur eine einzige IdpConfiguration haben, brauchen Sie den Parameter idpConfigurationID nicht anzugeben.
 a| 
UUID
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "EnableIdpAuthentication",
  "params": {
    "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
  }
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"result": {}
}
----


== Neu seit Version

12,0
