---
permalink: api/reference_element_api_response_object_members.html 
sidebar: sidebar 
keywords: response,object,member 
summary: 'Jeder Antworttext der Element-Software-API enthält die folgenden grundlegenden Bestandteile:' 
---
= Mitglieder des Antwortobjekts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Antworttext der Element-Software-API enthält die folgenden grundlegenden Bestandteile:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Das von der Methode zurückgegebene Objekt.  Das System gibt ein Objekt mit benannten Elementen zurück, die dem dokumentierten Rückgabewert der Methode entsprechen.  Dieses Mitglied ist nicht vorhanden, wenn ein Fehler aufgetreten ist.
 a| 
JSON-Objekt



 a| 
Fehler
 a| 
Das Objekt, das im Fehlerfall zurückgegeben wird.  Dieses Element ist nur vorhanden, wenn ein Fehler aufgetreten ist.
 a| 
Objekt



 a| 
Ausweis
 a| 
Eine Kennung, die dazu dient, die Anfrage der Antwort zuzuordnen, wie sie in der Anfrage angegeben ist.
 a| 
Zeichenkette oder Ganzzahl



 a| 
ungenutzte Parameter
 a| 
Eine Warnmeldung, dass mindestens ein falscher Parameter an die API-Methode übergeben wurde und nicht verwendet wurde.
 a| 
Objekt

|===