---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: Mit der Methode SetNodeSupplementalTlsCiphers können Sie die Liste der zusätzlichen TLS-Verschlüsselungen angeben.  Sie können diesen Befehl auf Management-Knoten verwenden. 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `SetNodeSupplementalTlsCiphers` Methode zur Angabe der Liste zusätzlicher TLS-Verschlüsselungen.  Sie können diesen Befehl auf Management-Knoten verwenden.



== Parameter


NOTE: Sie müssen diese Methode auf dem Management-Knoten aufrufen. Beispiel:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
ergänzende Chiffren
 a| 
Die Namen der zusätzlichen Verschlüsselungssuiten werden gemäß dem OpenSSL-Namensschema verwendet.  Die Verwendung von Cipher Suite-Namen unterscheidet nicht zwischen Groß- und Kleinschreibung.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
obligatorische Verschlüsselungen
 a| 
Liste der für den Knoten obligatorischen TLS-Verschlüsselungssammlungen.  Dies sind Verschlüsselungsverfahren, die auf dem Knoten immer aktiv sind.
 a| 
Schnur



 a| 
ergänzende Chiffren
 a| 
Liste der zusätzlichen TLS-Verschlüsselungssammlungen für den Knoten.
 a| 
Schnur

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----