---
permalink: api/reference_element_api_listvirtualvolumebindings.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings 
summary: Mit der Methode ListVirtualVolumeBindings können Sie eine Liste aller virtuellen Volumes im Cluster abrufen, die an Protokollendpunkte gebunden sind. 
---
= ListVirtualVolumeBindings
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVirtualVolumeBindings` Methode zum Abrufen einer Liste aller virtuellen Volumes im Cluster, die an Protokollendpunkte gebunden sind.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
virtuelleVolumeBindingIDs
 a| 
Eine Liste von virtuellen Datenträgerbindungs-IDs, zu denen Informationen abgerufen werden können.  Wenn Sie diesen Parameter weglassen, gibt die Methode Informationen über alle virtuellen Volumenbindungen zurück.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Bindungen
 a| 
Eine Liste von Objekten, die alle virtuellen Volumes im Cluster beschreiben, die an Protokollendpunkte gebunden sind.
 a| 
xref:reference_element_api_binding_vvols.adoc[Bindung]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----


== Neu seit Version

9,6
