---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: Mit der Methode StartVolumePairing können Sie einen codierten Schlüssel aus einem Volume erstellen, der zum Koppeln mit einem anderen Volume verwendet wird.  Der mit dieser Methode erzeugte Schlüssel wird in der CompleteVolumePairing-Methode verwendet, um eine Volume-Paarung herzustellen. 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `StartVolumePairing` Methode zum Erstellen eines codierten Schlüssels aus einem Volume, der zum Koppeln mit einem anderen Volume verwendet wird.  Der mit dieser Methode erzeugte Schlüssel wird verwendet in der `CompleteVolumePairing` Methode zur Herstellung einer Volumenpaarung.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Modus
 a| 
Der Modus des Volumens, auf dem der Kopplungsprozess gestartet werden soll.  Der Modus kann nur eingestellt werden, wenn es sich um die Quelllautstärke handelt. Mögliche Werte:

* `Async`Schreibvorgänge werden bestätigt, sobald sie lokal abgeschlossen sind.  Der Cluster wartet nicht darauf, dass Schreibvorgänge in den Zielcluster repliziert werden.  (Standardeinstellung, falls kein Modusparameter angegeben ist.)
* `Sync`Die Quelle bestätigt den Schreibvorgang, wenn die Daten lokal und auf dem Remote-Cluster gespeichert werden.
* `SnapshotsOnly`Es werden nur Snapshots repliziert, die auf dem Quellcluster erstellt wurden.  Aktive Schreibvorgänge vom Quellvolume werden nicht repliziert.

 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Volume-ID
 a| 
Die ID des Datenträgers, auf dem der Kopplungsprozess gestartet werden soll.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Lautstärke-Kopplungstaste
 a| 
Eine Zeichenkette, die von derxref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API-Methode.
 a| 
Schnur

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
