---
permalink: api/reference_element_api_listvolumestatsbyaccount.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,account,listvolumestatsbyaccount,activity 
summary: Mit der Methode ListVolumeStatsByAccount können Sie die wichtigsten Volumenaktivitätsmessungen für jedes Konto auflisten.  Die Werte werden aus allen zum Konto gehörenden Volumes summiert. 
---
= ListVolumeStatsByAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVolumeStatsByAccount` Methode zur Auflistung von Kennzahlen zur Volumenaktivität auf hoher Ebene für jedes Konto.  Die Werte werden aus allen zum Konto gehörenden Volumes summiert.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Virtuelle Volumes einbeziehen
 a| 
Virtuelle Volumes werden standardmäßig in die Antwort einbezogen.  Um virtuelle Volumes auszuschließen, auf „false“ setzen.
 a| 
boolescher Wert
 a| 
true
 a| 
Nein



 a| 
Konten
 a| 
Eine Liste der Konto-IDs, für die Volumenstatistiken abgerufen werden sollen.  Wird dieser Parameter weggelassen, werden Statistiken für alle Konten zurückgegeben.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
volumeStats
 a| 
Liste der Volumenaktivitätsinformationen für jedes Konto.*Hinweis:* Das VolumeID-Element ist für jeden Eintrag 0, da die Werte die Summe aller dem Konto gehörenden Volumes darstellen.
 a| 
xref:reference_element_api_volumestats.adoc[volumeStats]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
"method": "ListVolumeStatsByAccount",
  "params": {"accounts": [3]},
  "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "nonZeroBlocks": 155040175,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T20:42:26.231661Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [],
        "volumeID": 0,
        "volumeSize": 1127428915200,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 120211025
      }
    ]
  }
}
----


== Neu seit Version

9,6
