---
permalink: api/reference_element_api_removevolumesfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: remove,removing,volume,volumes,access,group,removevolumesfromvolumeaccessgroup 
summary: Mit der Methode RemoveVolumesFromVolumeAccessGroup können Sie Datenträger aus einer bestimmten Datenträgerzugriffsgruppe entfernen. 
---
= RemoveVolumesFromVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `RemoveVolumesFromVolumeAccessGroup` Methode zum Entfernen von Datenträgern aus einer bestimmten Datenträgerzugriffsgruppe.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
volumeAccessGroupID
 a| 
VolumeAccessGroupID, aus der Volumes entfernt werden sollen.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja



 a| 
Bände
 a| 
Volume-IDs der Datenträger, die aus der Datenträgerzugriffsgruppe entfernt werden sollen.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
volumeAccessGroup
 a| 
Ein Objekt, das Informationen über die neu geänderte Datenträgerzugriffsgruppe enthält.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "RemoveVolumesFromVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": []
    }
  }
}
----


== Neu seit Version

9,6
