---
permalink: api/reference_element_api_setsnmptrapinfo.html 
sidebar: sidebar 
keywords: snmp,trap,information,info,setting,set,setsnmptrapinfo 
summary: 'Mit der Methode SetSnmpTrapInfo können Sie die Generierung von Cluster-SNMP-Benachrichtigungen (Traps) aktivieren und deaktivieren sowie die Menge der Hosts festlegen, die die Benachrichtigungen empfangen.  Die Werte, die Sie bei jedem Aufruf der Methode SetSnmpTrapInfo übergeben, ersetzen alle Werte, die in einem vorherigen Aufruf festgelegt wurden.' 
---
= SetSnmpTrapInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `SetSnmpTrapInfo` Methode zum Aktivieren und Deaktivieren der Generierung von Cluster-SNMP-Benachrichtigungen (Traps) und zum Festlegen der Menge von Hosts, die die Benachrichtigungen empfangen.  Die Werte, die Sie mit jedem `SetSnmpTrapInfo` Der Methodenaufruf ersetzt alle Werte, die in einem vorherigen Aufruf festgelegt wurden.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ 


 a| 
trapRecipients
 a| 
Liste der Hosts, die die vom Speichercluster generierten Traps empfangen sollen.  Mindestens ein Objekt ist erforderlich, wenn einer der Trap-Typen aktiviert ist.  Dieser Parameter ist nur erforderlich, wenn boolesche Parameter auf „true“ gesetzt sind.  (Kein Standardwert.)  Nicht erforderlich.)
 a| 
xref:reference_element_api_snmptraprecipient.adoc[snmpTrapRecipient]Array



 a| 
clusterFaultTrapsEnabled
 a| 
Wenn diese Option auf „true“ gesetzt ist, wird beim Protokollieren eines Clusterfehlers eine entsprechende Clusterfehlerbenachrichtigung an die konfigurierte Liste der Trap-Empfänger gesendet.  (Standardwert: false.)  Nicht erforderlich.)
 a| 
boolescher Wert



 a| 
clusterFaultResolvedTrapsEnabled
 a| 
Wenn diese Einstellung auf „true“ gesetzt ist, wird eine entsprechende Benachrichtigung über die Behebung eines Clusterfehlers an die konfigurierte Liste der Trap-Empfänger gesendet, sobald ein Clusterfehler behoben ist.  (Standardwert: false.)  Nicht erforderlich.)
 a| 
boolescher Wert



 a| 
clusterEventTrapsEnabled
 a| 
Wenn diese Option auf „true“ gesetzt ist, wird beim Protokollieren eines Clusterereignisses eine entsprechende Clusterereignisbenachrichtigung an die konfigurierte Liste der Trap-Empfänger gesendet.  (Standardwert: false.)  Nicht erforderlich.)
 a| 
boolescher Wert

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
"method":"SetSnmpTrapInfo",
"params":{
    "clusterFaultTrapsEnabled":true,
    "clusterFaultResolvedTrapsEnabled":true,
    "clusterEventTrapsEnabled":true,
    "trapRecipients":[
    {
      "host":"192.30.0.10",
      "port":162,
      "community":"public"
    }
   ]
  },
  "id":1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id" : 1,
    "result" : {}
}
----


== Neu seit Version

9,6
