---
permalink: api/reference_element_api_quiescesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,quiesce,quiescing,quiescescnapmirrorrelationship 
summary: Die Web-Benutzeroberfläche der Element-Software verwendet die Methode QuiesceSnapMirrorRelationship, um zukünftige Datenübertragungen für eine SnapMirror Beziehung zu deaktivieren.  Wenn eine Übertragung im Gange ist, ändert sich der Beziehungsstatus bis zum Abschluss der Übertragung in „ruhend“.  Wird die aktuelle Übertragung abgebrochen, wird sie nicht neu gestartet.  Sie können die Datenübertragung für die Beziehung mithilfe der API-Methode ResumeSnapMirrorRelationship wieder aktivieren. 
---
= QuiesceSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Web-Benutzeroberfläche der Element-Software verwendet die `QuiesceSnapMirrorRelationship` Methode zum Deaktivieren zukünftiger Datenübertragungen für eine SnapMirror -Beziehung.  Wenn eine Übertragung im Gange ist, ändert sich der Beziehungsstatus bis zum Abschluss der Übertragung in „ruhend“.  Wird die aktuelle Übertragung abgebrochen, wird sie nicht neu gestartet.  Sie können die Datenübertragung für die Beziehung mithilfe der folgenden Methode wieder aktivieren: `ResumeSnapMirrorRelationship` API-Methode.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
snapMirrorEndpointID
 a| 
Die Endpunkt-ID des entfernten ONTAP -Speichersystems, das mit dem Element-Speichercluster kommuniziert.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja



 a| 
Zielvolumen
 a| 
Das Zielvolumen in der SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Snap-Spiegelbeziehung
 a| 
Ein Objekt, das Informationen über die ruhende SnapMirror -Beziehung enthält.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[Snap-Spiegelbeziehung]

|===


== Neu seit Version

10,1
