---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: Mit der Methode ListVolumes können Sie eine Liste der Volumes in einem Cluster abrufen.  Sie können die Datenträger, die in der Liste zurückgegeben werden sollen, mithilfe der verfügbaren Parameter festlegen. 
---
= ListVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVolumes` Methode zum Abrufen einer Liste der Volumes in einem Cluster.  Sie können die Datenträger, die in der Liste zurückgegeben werden sollen, mithilfe der verfügbaren Parameter festlegen.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Konten
 a| 
Es werden nur die Volumes zurückgegeben, die den hier angegebenen Konten gehören.  Schließt sich gegenseitig mit dem Parameter volumeIDs aus.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein



 a| 
Virtuelle Volumes einbeziehen
 a| 
Virtuelle Volumes werden standardmäßig in die Antwort einbezogen.  Um virtuelle Volumes auszuschließen, auf „false“ setzen.
 a| 
boolescher Wert
 a| 
true
 a| 
Nein



 a| 
istgepaart
 a| 
Gibt gepaarte oder nicht gepaarte Volumes zurück. Mögliche Werte:

* true: Gibt alle gepaarten Volumes zurück.
* false: Gibt alle nicht gepaarten Volumes zurück.

 a| 
boolescher Wert
 a| 
Keine
 a| 
Nein



 a| 
Limit
 a| 
Ermöglicht es Ihnen, die maximale Anzahl der zurückgegebenen Volumenresultate festzulegen.  Schließt sich gegenseitig mit dem Parameter volumeIDs aus.
 a| 
ganze Zahl
 a| 
10000
 a| 
Nein



 a| 
startVolumeID
 a| 
Es werden nur Datenträger mit einer ID, die größer oder gleich diesem Wert ist, zurückgegeben.  Schließt sich gegenseitig mit dem Parameter volumeIDs aus.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
Volume-IDs
 a| 
Eine Liste der Datenträger-IDs.  Wenn Sie diesen Parameter angeben, wirken sich andere Parameter nur auf diesen Satz von Datenträgern aus.  Schließt sich gegenseitig mit den Parametern accounts, startVolumeID und limit aus.
 a| 
Ganzzahl-Array
 a| 
Nein
 a| 
Nein



 a| 
volumeName
 a| 
Es werden nur die Datenträgerobjektinformationen zurückgegeben, die mit dem Datenträgernamen übereinstimmen.
 a| 
Schnur
 a| 
Nein
 a| 
Nein



 a| 
Volumenstatus
 a| 
Es werden nur Datenträger zurückgegeben, deren Status dem Statuswert entspricht. Mögliche Werte:

* Erstellen
* Momentaufnahmen
* aktiv
* gelöscht

 a| 
Schnur
 a| 
Nein
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Bände
 a| 
Bandliste.
 a| 
xref:reference_element_api_volume.adoc[Volumen]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Neu seit Version

9,6
