---
permalink: api/reference_element_api_resetnode.html 
sidebar: sidebar 
keywords:  
summary: 'Mit der ResetNode-Methode können Sie einen Knoten auf die Werkseinstellungen zurücksetzen.  Beim Aufruf dieser Methode werden alle Daten, Pakete (Software-Upgrades usw.), Konfigurationen und Protokolldateien vom Knoten gelöscht.  Die Netzwerkeinstellungen des Knotens bleiben jedoch während dieses Vorgangs erhalten.  Knoten, die an einem Cluster beteiligt sind, können nicht auf die Werkseinstellungen zurückgesetzt werden.' 
---
= ResetNode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ResetNode` Methode zum Zurücksetzen eines Knotens auf die Werkseinstellungen.  Beim Aufruf dieser Methode werden alle Daten, Pakete (Software-Upgrades usw.), Konfigurationen und Protokolldateien vom Knoten gelöscht.  Die Netzwerkeinstellungen des Knotens bleiben jedoch während dieses Vorgangs erhalten.  Knoten, die an einem Cluster beteiligt sind, können nicht auf die Werkseinstellungen zurückgesetzt werden.



== Parameter

Die ResetNode-API kann nur auf Knoten verwendet werden, die sich im Status „Verfügbar“ befinden.  Es kann nicht auf Knoten verwendet werden, die in einem Cluster den Status „Aktiv“ haben oder sich im Status „Ausstehend“ befinden.

VORSICHT:

Diese Methode löscht sämtliche Kundendaten, die sich auf dem Knoten befinden.

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
bauen
 a| 
Dient zur Angabe der URL zu einem entfernten Element-Software-Image, auf das der Knoten zurückgesetzt wird.
 a| 
URL
 a| 
Keine
 a| 
Nein



 a| 
Gewalt
 a| 
Auf „true“ setzen, um den Knoten zurückzusetzen.
 a| 
boolescher Wert
 a| 
Keine
 a| 
Ja



 a| 
Optionen
 a| 
Dient zur Eingabe von Spezifikationen für die Durchführung der Reset-Operationen.  Detaillierte Informationen erhalten Sie bei Bedarf vom NetApp Support.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ResetNode",
   "params": {
      "build" : "file:///sf/rtfi/image/filesystem.squashfs",
      "force" : true
              },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": null,
  "result": {
    "rtfiInfo": {
      "build": "file:///sf/rtfi/image/filesystem.squashfs",
      "generation": "9",
      "options": {
        "edebug": "",
        "sf_auto": "0",
        "sf_bond_mode": "ActivePassive",
        "sf_check_hardware": "0",
        "sf_disable_otpw": "0",
        "sf_fa_host": "",
        "sf_hostname": "SF-FA18",
        "sf_inplace": "1",
        "sf_inplace_die_action": "kexec",
        "sf_inplace_safe": "0",
        "sf_keep_cluster_config": "0",
        "sf_keep_data": "0",
        "sf_keep_hostname": "0",
        "sf_keep_network_config": "0",
        "sf_keep_paths": "\"/var/log/hardware.xml\"",
        "sf_max_archives": "5",
        "sf_nvram_size": "",
        "sf_oldroot": "",
        "sf_postinst_erase_root_drive": "0",
        "sf_root_drive": "",
        "sf_rtfi_cleanup_state": "",
        "sf_secure_erase": "1",
        "sf_secure_erase_retries": "5",
        "sf_slice_size": "",
        "sf_ssh_key": "1",
        "sf_ssh_root": "1",
        "sf_start_rtfi": "1",
        "sf_status_httpserver": "1",
        "sf_status_httpserver_stop_delay": "5m",
        "sf_status_inject_failure": "",
        "sf_status_json": "0",
        "sf_support_host": "sfsupport.solidfire.com",
        "sf_test_hardware": "0",
        "sf_upgrade": "0",
        "sf_upgrade_firmware": "0",
        "sf_upload_logs_url": ""
     },
      "statusUrlAll": "http://192.168.130.20/status/all.json",
      "statusUrlCurrent": "http://192.168.130.20/status/current.json"
    }
  }
}
----


== Neu seit Version

9,6
