---
permalink: api/reference_element_api_createsnapmirrorendpoint.html 
sidebar: sidebar 
keywords: SnapMirror,endpoints,endpoint,creating,create,CreateSnapMirrorEndpoint 
summary: Die Element-Weboberfläche verwendet die Methode CreateSnapMirrorEndpoint, um eine Beziehung zu einem entfernten SnapMirror Endpunkt herzustellen. 
---
= CreateSnapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Element-Weboberfläche verwendet die `CreateSnapMirrorEndpoint` Methode zum Herstellen einer Beziehung zu einem entfernten SnapMirror Endpunkt.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Management-IP
 a| 
Die Management-IP-Adresse des entfernten SnapMirror Endpunkts.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Benutzername
 a| 
Der Verwaltungsbenutzername für das ONTAP -System.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Passwort
 a| 
Das Verwaltungspasswort für das ONTAP -System.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
SnapMirrorEndpunkt
 a| 
Der neu erstellte SnapMirror Endpunkt.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[SnapMirrorEndpunkt]

|===


== Neu seit Version

10,0
