---
permalink: api/reference_element_api_removenodesslcertificate.html 
sidebar: sidebar 
keywords: ssl,cert,certificate,remove,removing,node,management,removenodesslcertificate 
summary: Mit der Methode RemoveNodeSSLCertificate können Sie das Benutzer-SSL-Zertifikat und den privaten Schlüssel für den Verwaltungsknoten entfernen.  Nachdem das Zertifikat und der private Schlüssel entfernt wurden, wird der Verwaltungsknoten so konfiguriert, dass er das Standardzertifikat und den Standardschlüssel verwendet. 
---
= RemoveNodeSSLCertificate
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `RemoveNodeSSLCertificate` Methode zum Entfernen des Benutzer-SSL-Zertifikats und des privaten Schlüssels für den Verwaltungsknoten.  Nachdem das Zertifikat und der private Schlüssel entfernt wurden, wird der Verwaltungsknoten so konfiguriert, dass er das Standardzertifikat und den Standardschlüssel verwendet.



== Parameter


NOTE: Sie müssen diese Methode auf dem Management-Knoten aufrufen. Beispiel:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "method" : "RemoveNodeSSLCertificate",
    "params" : {},
    "id" : 3
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id" : 3,
    "result" : {}
}
----