---
permalink: api/reference_element_api_addldapclusteradmin.html 
sidebar: sidebar 
keywords: LDAP,cluster,admin,add,adding,addldapclusteradmin 
summary: Mit dem Befehl AddLdapClusterAdmin können Sie einen neuen LDAP-Cluster-Administratorbenutzer hinzufügen.  Ein LDAP-Cluster-Administrator kann den Cluster mithilfe der API und der Verwaltungstools verwalten.  LDAP-Cluster-Administratorkonten sind vollständig getrennt und stehen in keinem Zusammenhang mit Standard-Mandantenkonten. 
---
= AddLdapClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `AddLdapClusterAdmin` einen neuen LDAP-Cluster-Administratorbenutzer hinzufügen.  Ein LDAP-Cluster-Administrator kann den Cluster mithilfe der API und der Verwaltungstools verwalten.  LDAP-Cluster-Administratorkonten sind vollständig getrennt und stehen in keinem Zusammenhang mit Standard-Mandantenkonten.



== Parameter

Mit dieser Methode können Sie auch eine LDAP-Gruppe hinzufügen, die in Active Directory® definiert wurde.  Die der Gruppe zugewiesene Zugriffsebene wird an die einzelnen Benutzer in der LDAP-Gruppe weitergegeben.

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Zugang
 a| 
Steuert, welche Methoden dieser Cluster-Administrator verwenden kann.
 a| 
Zeichenketten-Array
 a| 
Keine
 a| 
Ja



 a| 
acceptEula
 a| 
Akzeptieren Sie die Endbenutzer-Lizenzvereinbarung.  Auf „true“ setzen, um dem System ein Cluster-Administratorkonto hinzuzufügen.  Wird der Parameter weggelassen oder auf „false“ gesetzt, schlägt der Methodenaufruf fehl.
 a| 
boolescher Wert
 a| 
Keine
 a| 
Ja



 a| 
Attribute
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
Benutzername
 a| 
Der eindeutige Benutzername für den neuen LDAP-Clusteradministrator.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "AddLdapClusterAdmin",
  "params": {"username":"cn=mike jones,ou=ptusers,dc=prodtest,dc=solidfire,dc=net",
    "access": ["administrator", "read"
    ]
  },
"id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
 "id": 1,
 "result": {}
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_app_b_access_control.adoc[Zugriffskontrolle]
