---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: Mit der Methode DisableClusterSsh können Sie den SSH-Dienst für den gesamten Speichercluster deaktivieren.  Wenn Sie dem Speichercluster Knoten hinzufügen, übernehmen die neuen Knoten diese clusterweite Einstellung. 
---
= ClusterSsh deaktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `DisableClusterSsh` Methode zum Deaktivieren des SSH-Dienstes für den gesamten Speichercluster.  Wenn Sie dem Speichercluster Knoten hinzufügen, übernehmen die neuen Knoten diese clusterweite Einstellung.



== Parameter

Diese Methode hat keinen Eingabeparameter.



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Ein JSON-Objekt, das den Status des SSH-Dienstes für den Speichercluster, die verbleibende Zeit bis zur Deaktivierung von SSH und den SSH-Dienststatus für jeden Knoten enthält.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Neu seit Version

10,3
