---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: Mit der Methode ListStorageContainers können Sie Informationen über alle dem System bekannten virtuellen Speichercontainer abrufen. 
---
= ListStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListStorageContainers` Methode zum Abrufen von Informationen über alle dem System bekannten virtuellen Speichercontainer.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Speichercontainer-IDs
 a| 
Eine Liste der Speichercontainer-IDs, für die Informationen abgerufen werden können.  Wenn Sie diesen Parameter weglassen, gibt die Methode Informationen über alle Speichercontainer im System zurück.
 a| 
UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Lagerbehälter
 a| 
Liste von Objekten, die Informationen über alle Speichercontainer im System enthalten.
 a| 
xref:reference_element_api_storagecontainer.adoc[Lagerbehälter]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Neu seit Version

9,6
