---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Mit der Methode DeleteStorageContainers können Sie bis zu 2000 Virtual Volume (VVol)-Speichercontainer gleichzeitig aus dem System entfernen.  Die zu entfernenden Speichercontainer dürfen keine VVols enthalten.' 
---
= Speichercontainer löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `DeleteStorageContainers` Methode zum gleichzeitigen Entfernen von bis zu 2000 Virtual Volume (VVol) Speichercontainern aus dem System.  Die zu entfernenden Speichercontainer dürfen keine VVols enthalten.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Speichercontainer-IDs
 a| 
Eine Liste der IDs der zu löschenden Speichercontainer.  Sie können bis zu 2000 IDs in der Liste angeben.
 a| 
UUID-Array
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Neu seit Version

9,6
