---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: 'Mit der Methode ListInitiators können Sie die Liste der Initiator-IQNs oder World Wide Port Names (WWPNs) abrufen.' 
---
= Listeninitiatoren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListInitiators` Methode zum Abrufen der Liste der Initiator-IQNs oder World Wide Port Names (WWPNs).



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Initiatoren
 a| 
Eine Liste der abzurufenden Initiator-IDs.  Sie können entweder diesen Parameter oder den Parameter startInitiatorID angeben, aber nicht beide.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein



 a| 
startInitiatorID
 a| 
Die Initiator-ID, mit der die Auflistung beginnen soll.  Sie können entweder diesen Parameter oder den Initiatorenparameter angeben, aber nicht beide.
 a| 
ganze Zahl
 a| 
0
 a| 
Nein



 a| 
Limit
 a| 
Die maximale Anzahl der zurückzugebenden Initiatorobjekte.
 a| 
ganze Zahl
 a| 
(unbegrenzt)
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Initiatoren
 a| 
Liste der Initiatorinformationen.
 a| 
xref:reference_element_api_initiator.adoc[Initiator]Array

|===


== Ausnahmen

Bei dieser Methode kann folgende Ausnahme auftreten:

|===


| Name | Beschreibung 


 a| 
xInvalidParameter
 a| 
Wird ausgelöst, wenn Sie sowohl den Parameter startInitiatorID als auch den Parameter initiators im selben Methodenaufruf angeben.

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Neu seit Version

9,6
