---
permalink: api/reference_element_api_createsnapmirrorvolume.html 
sidebar: sidebar 
keywords: SnapMirror,endpoints,create,creating,volume,volumes,CreateSnapMirrorVolume 
summary: Die Element-Weboberfläche verwendet die CreateSnapMirrorVolume-Methode, um ein Volume auf dem entfernten ONTAP -System zu erstellen. 
---
= CreateSnapMirrorVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Element-Weboberfläche verwendet die `CreateSnapMirrorVolume` Methode zum Erstellen eines Volumes auf dem entfernten ONTAP System.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
snapMirrorEndpointID
 a| 
Die Endpunkt-ID des entfernten ONTAP -Speichersystems, das mit dem Element-Speichercluster kommuniziert.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja



 a| 
vServer
 a| 
Der Name des Vservers.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Name
 a| 
Der Name des Ziel ONTAP Volumes.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Typ
 a| 
Der Volumentyp. Mögliche Werte:

* rw: Lese-/Schreib-Volume
* ls: Lastverteilungsvolumen
* dp: Datenschutzvolumen


Wird kein Typ angegeben, ist der Standardtyp dp.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Aggregat
 a| 
Das enthaltende ONTAP Aggregat, in dem das Volume erstellt werden soll.  Mit ListSnapMirrorAggregates erhalten Sie Informationen über verfügbare ONTAP Aggregate.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Größe
 a| 
Die Größe des Datenvolumens in Bytes.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
SnapMirrorVolume
 a| 
Informationen zu einem SnapMirror Volume.
 a| 
xref:reference_element_api_snapmirrorvolume.adoc[SnapMirrorVolume]

|===


== Neu seit Version

10,1
