---
permalink: api/reference_element_api_deleteauthsessionsbyclusteradmin.html 
sidebar: sidebar 
keywords: auth sessions,cluster,admin,delete,authentication sessions 
summary: Mit der Methode DeleteAuthSessionsByClusterAdmin können Sie alle Authentifizierungssitzungen löschen, die mit der angegebenen ClusterAdminID verknüpft sind.  Wenn die angegebene ClusterAdminID einer Benutzergruppe zugeordnet ist, werden alle Authentifizierungssitzungen für alle Mitglieder dieser Gruppe gelöscht.  Um eine Liste der Sitzungen anzuzeigen, die möglicherweise gelöscht werden sollen, verwenden Sie die Methode ListAuthSessionsByClusterAdmin mit dem Parameter ClusterAdminID. 
---
= DeleteAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `DeleteAuthSessionsByClusterAdmin` Methode zum Löschen aller Authentifizierungssitzungen, die mit dem angegebenen verknüpft sind `ClusterAdminID` Die  Wenn die angegebene ClusterAdminID einer Benutzergruppe zugeordnet ist, werden alle Authentifizierungssitzungen für alle Mitglieder dieser Gruppe gelöscht.  Um eine Liste der Sitzungen anzuzeigen, die möglicherweise gelöscht werden können, verwenden Sie die Methode ListAuthSessionsByClusterAdmin. `ClusterAdminID` Parameter.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
clusterAdminID
 a| 
Eindeutige Kennung für den Cluster-Administrator.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Sitzungen
 a| 
Sitzungsinformationen für die gelöschten Authentifizierungssitzungen.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "DeleteAuthSessionsByClusterAdmin",
  "params": {
    "clusterAdminID": 1
  }
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Neu seit Version

12,0
