---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: Mit der Methode GetNodeActiveTlsCiphers eines einzelnen Knotens können Sie eine Liste der TLS-Verschlüsselungen erhalten, die derzeit auf diesem Knoten akzeptiert werden.  Diese Methode kann auf Management- und Speicherknoten angewendet werden. 
---
= GetNodeActiveTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetNodeActiveTlsCiphers` Methode auf einem einzelnen Knoten, um eine Liste der TLS-Verschlüsselungen zu erhalten, die derzeit auf diesem Knoten akzeptiert werden.  Diese Methode kann auf Management- und Speicherknoten angewendet werden.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
obligatorische Verschlüsselungen
 a| 
Liste der für den Knoten obligatorischen TLS-Verschlüsselungssammlungen.  Dies sind Verschlüsselungsverfahren, die auf dem Knoten immer aktiv sind.
 a| 
Schnur



 a| 
ergänzende Chiffren
 a| 
Liste der zusätzlichen TLS-Verschlüsselungssammlungen für den Knoten.
 a| 
Schnur

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----