---
permalink: api/reference_element_api_listvolumesforaccount.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,account,active,pending,deleted,listvolumesforaccount 
summary: 'Mit der Methode ListVolumesForAccount können Sie die aktiven und (ausstehende) gelöschten Volumes eines Kontos auflisten.' 
---
= ListVolumesForAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVolumesForAccount` Methode zum Auflisten aktiver und (ausstehender) gelöschter Volumes für ein Konto.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Virtuelle Volumes einbeziehen
 a| 
Virtuelle Volumes werden standardmäßig in die Antwort einbezogen.  Um virtuelle Volumes auszuschließen, auf „false“ setzen.
 a| 
boolescher Wert
 a| 
true
 a| 
Nein



 a| 
Konto-ID
 a| 
Alle Volumes, die diesem Account zugeordnet sind, werden zurückgegeben.
 a| 
ganze Zahl
 a| 
Nein
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Bände
 a| 
Liste der Volumeninformationen.
 a| 
xref:reference_element_api_volume.adoc[Volumen]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListVolumesForAccount",
   "params": {
      "accountID"  : 1
   },
   "id" : 1
}
----


== Antwortbeispiel

Die Antworten auf diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-07-22T16:15:25Z",
                "deleteTime": "",
                "enable512e": false,
                "iqn": "iqn.2010-01.com.solidfire:0oto.test1.25",
                "name": "test1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000019f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000019",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 1000341504,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 25,
                "volumePairs": []
            }
        ]
    }
}
----


== Neu seit Version

9,6
