---
permalink: api/reference_element_api_listdrives.html 
sidebar: sidebar 
keywords: drives,drive,list,listing,listdrives,cluster 
summary: Mit der ListDrives-Methode können Sie die Laufwerke auflisten, die in den aktiven Knoten des Clusters vorhanden sind.  Diese Methode gibt Laufwerke zurück, die als Volume-Metadaten oder Blocklaufwerke hinzugefügt wurden, sowie Laufwerke, die nicht hinzugefügt wurden und verfügbar sind. 
---
= ListDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListDrives` Methode zum Auflisten der Laufwerke, die in den aktiven Knoten des Clusters vorhanden sind.  Diese Methode gibt Laufwerke zurück, die als Volume-Metadaten oder Blocklaufwerke hinzugefügt wurden, sowie Laufwerke, die nicht hinzugefügt wurden und verfügbar sind.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Laufwerke
 a| 
Liste der Laufwerke im Cluster.
 a| 
xref:reference_element_api_drive.adoc[fahren]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListDrives",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
     "drives" : [
       {
         "attributes" : {},
         "capacity" : 299917139968,
         "driveID" : 35,
         "nodeID" : 5,
         "serial" : "scsi-SATA_INTEL_SSDSA2CW6CVPR141502R3600FGN-part2",
         "slot" : 0,
         "status" : "active",
         "type" : "volume"
       },
       {
         "attributes" : {},
         "capacity" : 600127266816,
         "driveID" : 36,
         "nodeID" : 5,
         "serial" : "scsi-SATA_INTEL_SSDSA2CW6CVPR1415037R600FGN",
         "slot" : 6,
         "status" : "active",
         "type" : "block"
       }
     }
   ]
}
----


== Neu seit Version

9,6
