---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: Das clusterStats-Objekt enthält statistische Daten für einen Cluster.  Viele der im Objekt enthaltenen volumenbezogenen Statistiken sind über alle Volumina im Cluster gemittelt.  Sie können die Methode GetClusterStats verwenden, um diese Informationen für einen Cluster abzurufen. 
---
= Clusterstatistik
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das clusterStats-Objekt enthält statistische Daten für einen Cluster.  Viele der im Objekt enthaltenen volumenbezogenen Statistiken sind über alle Volumina im Cluster gemittelt.  Sie können die Methode GetClusterStats verwenden, um diese Informationen für einen Cluster abzurufen.



== Objektmitglieder

Dieses Objekt enthält die folgenden Elemente:

|===
| Name | Beschreibung | Berechnung | Typ 


 a| 
tatsächliche IOPS
 a| 
Aktuelle IOPS für den gesamten Cluster in den letzten 500 Millisekunden.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
durchschnittliche IOPS-Größe
 a| 
Durchschnittliche Größe der letzten E/A-Operationen an den Cluster in den letzten 500 Millisekunden in Bytes.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
Client-Warteschlangentiefe
 a| 
Die Anzahl der ausstehenden Lese- und Schreibvorgänge im Cluster.
 a| 
k. A.
 a| 
ganze Zahl



 a| 
Clusternutzung
 a| 
Der Prozentsatz der aktuell genutzten maximalen IOPS des Clusters.  Dies wird wie folgt berechnet: Clusterauslastung = normalisierte IOPS / maxIOPS (aus GetClusterCapacity).
 a| 
k. A.
 a| 
schweben



 a| 
Latenz in US-Sekunden
 a| 
Die durchschnittliche Zeit in Mikrosekunden, die für die Ausführung von Operationen an einem Cluster in den letzten 500 Millisekunden benötigt wurde.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
normalisierte IOPS
 a| 
Durchschnittliche Anzahl der IOPS für den gesamten Cluster in den letzten 500 Millisekunden.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
gelesene Bytes
 a| 
Die Gesamtzahl der seit der Erstellung des Clusters vom Cluster gelesenen Bytes.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
readBytesLastSample
 a| 
Die Gesamtzahl der Bytes, die während des letzten Abtastzeitraums vom Cluster gelesen wurden.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
LeselatenzUSec
 a| 
Die durchschnittliche Zeit in Mikrosekunden, die für Leseoperationen im Cluster in den letzten 500 Millisekunden benötigt wurde.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
LeselatenzUSecGesamt
 a| 
Die gesamte Zeit, die seit der Erstellung des Clusters für Leseoperationen aufgewendet wurde.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
Leseoperationen
 a| 
Die Gesamtzahl der kumulierten Leseoperationen im Cluster seit dessen Erstellung.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
readOpsLastSample
 a| 
Die Gesamtzahl der Lesevorgänge während des letzten Stichprobenzeitraums.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
samplePeriodMSec
 a| 
Die Länge der Abtastperiode in Millisekunden.
 a| 
k. A.
 a| 
ganze Zahl



 a| 
Anzahl der Dienste
 a| 
Die Anzahl der auf dem Cluster laufenden Dienste.  Wenn der Wert gleich servicesTotal ist, bedeutet dies, dass von allen Knoten gültige Statistiken erfasst wurden.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
Dienstleistungen Gesamt
 a| 
Die Gesamtzahl der erwarteten Dienste, die auf dem Cluster ausgeführt werden.
 a| 
k. A.
 a| 
ganze Zahl



 a| 
Zeitstempel
 a| 
Die aktuelle Uhrzeit im UTC+0-Format.
 a| 
k. A.
 a| 
ISO 8601 Datumszeichenfolge



 a| 
nicht ausgerichtete Lesevorgänge
 a| 
Die Gesamtzahl der kumulierten, nicht ausgerichteten Leseoperationen auf einen Cluster seit dessen Erstellung.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
unalignedWrites
 a| 
Die Gesamtzahl der kumulierten, nicht ausgerichteten Schreibvorgänge in einem Cluster seit dessen Erstellung.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
writeBytes
 a| 
Die Gesamtzahl der seit der Erstellung des Clusters auf den Cluster geschriebenen Bytes.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
writeBytesLastSample
 a| 
Die Gesamtzahl der Bytes, die während des letzten Abtastzeitraums in den Cluster geschrieben wurden.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
SchreiblatenzUSec
 a| 
Die durchschnittliche Zeit in Mikrosekunden, die zum Abschließen von Schreibvorgängen in einem Cluster in den letzten 500 Millisekunden benötigt wurde.
 a| 
Zeitpunkt
 a| 
ganze Zahl



 a| 
SchreiblatenzUSecTotal
 a| 
Die gesamte Zeit, die seit der Erstellung des Clusters für Schreibvorgänge aufgewendet wurde.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
Schreibvorgänge
 a| 
Die Gesamtzahl der Schreibvorgänge im Cluster seit dessen Erstellung.
 a| 
monoton steigend
 a| 
ganze Zahl



 a| 
writeOpsLastSample
 a| 
Die Gesamtzahl der Schreibvorgänge während des letzten Abtastzeitraums.
 a| 
Zeitpunkt
 a| 
ganze Zahl

|===


== Weitere Informationen

xref:reference_element_api_getclusterstats.adoc[GetClusterStats]
