---
permalink: api/reference_element_api_testremoteconnectivity.html 
sidebar: sidebar 
keywords: remote,connectivity,test,testing,testremoteconnectivity 
summary: Mit der Methode TestRemoteConnectivity können Sie jeden Knoten des Remote-Clusters anpingen und die Verbindung zur Remote-Ensemble-Datenbank überprüfen.  Um mit dieser Methode sinnvolle Ergebnisse zu erzielen, müssen Cluster paarweise zugeordnet werden.  Wenn die Verbindung zur Remote-Datenbank fehlschlägt, listet die Antwort des Systems die Ausnahmen auf. 
---
= TestRemoteConnectivity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verwenden `TestRemoteConnectivity` Methode zum Anpingen jedes Knotens des Remote-Clusters und zum Überprüfen der Remote-Ensemble-Datenbankverbindung.  Um mit dieser Methode sinnvolle Ergebnisse zu erzielen, müssen Cluster paarweise zugeordnet werden.  Wenn die Verbindung zur Remote-Datenbank fehlschlägt, listet die Antwort des Systems die Ausnahmen auf.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Details
 a| 
Individuelle Ping-Antwortzeiten für jeden Knoten.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "TestRemoteConnectivity",
    "params": {
      "force": "true"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": null,
  "result": {
    "details": {
      "1": {
        "details": {
          "10.26.86.17": {
            "individualResponseTimes": [
              "00:00:00.006868",
              "00:00:00.005933",
              "00:00:00.006655",
              "00:00:00.006584",
              "00:00:00.006334"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006475",
            "successful": true
          },
          "10.26.86.18": {
            "individualResponseTimes": [
              "00:00:00.006201",
              "00:00:00.006187",
              "00:00:00.005990",
              "00:00:00.006029",
              "00:00:00.005917"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006065",
            "successful": true
          },
          "10.26.86.19": {
            "individualResponseTimes": [
              "00:00:00.005988",
              "00:00:00.006948",
              "00:00:00.005981",
              "00:00:00.005964",
              "00:00:00.005942"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006165",
            "successful": true,
          },
          "10.26.86.20": {
            "individualResponseTimes": [
              "00:00:00.005926",
              "00:00:00.006072",
              "00:00:00.005675",
              "00:00:00.009904",
              "00:00:00.006225"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006760",
            "successful": true
          }
        },
          "successful": true
      }
    },
  "duration": "00:00:00.595982",
  "result": "Passed"
  }
}
----


== Neu seit Version

9,6
