---
permalink: api/reference_element_api_enablebmccoldreset.html 
sidebar: sidebar 
keywords: BMC cold reset,BMC reset,enable BMC 
summary: 'Mit der Methode EnableBmcColdReset können Sie eine Hintergrundaufgabe aktivieren, die den Baseboard Management Controller (BMC) für alle Knoten im Cluster regelmäßig zurücksetzt.' 
---
= EnableBmcColdReset
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `EnableBmcColdReset` Methode zur Aktivierung einer Hintergrundaufgabe, die den Baseboard Management Controller (BMC) für alle Knoten im Cluster periodisch zurücksetzt.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Time-out
 a| 
Die Zeit zwischen den BMC Reset-Vorgängen in Minuten.
 a| 
ganze Zahl
 a| 
20160 Minuten
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
cBmcResetDurationMinutes
 a| 
Gibt die Zeit zwischen den Rücksetzintervallen zurück.  Das Intervall sollte nach Abschluss des Befehls immer 0 sein.
 a| 
ganze Zahl

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "method": "EnableBmcColdReset",
    "params": {
                "timeout": 36000
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "cBmcResetDurationMinutes": 36000
    }
}
----


== Neu seit Version

12,0
