---
permalink: api/reference_element_api_restartnetworking.html 
sidebar: sidebar 
keywords: node,restarting,restart,networking,network,service,services,restartnetworking 
summary: Mit der Methode „RestartNetworking“ können Sie die Netzwerkdienste auf einem Knoten neu starten. 
---
= Netzwerk neu starten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `RestartNetworking` Methode zum Neustart der Netzwerkdienste auf einem Knoten.

VORSICHT:

Diese Methode startet alle Netzwerkdienste auf einem Knoten neu, was zu einem vorübergehenden Verlust der Netzwerkverbindung führt.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Gewalt
 a| 
Auf „true“ setzen, um die Netzwerkdienste auf einem Knoten neu zu starten.
 a| 
boolescher Wert
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "RestartNetworking",
   "params": {
              "force" : true
             },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{ "id" : 1,
  "result" : {}
}
----


== Neu seit Version

9,6
