---
permalink: api/reference_element_api_snapmirrorrelationship.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorRelationship 
summary: Das snapMirrorRelationship-Objekt enthält Informationen über eine SnapMirror -Beziehung zwischen einem Element-Volume und einem ONTAP -Volume. 
---
= Snap-Spiegelbeziehung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das snapMirrorRelationship-Objekt enthält Informationen über eine SnapMirror -Beziehung zwischen einem Element-Volume und einem ONTAP -Volume.



== Objektmitglieder

Dieses Objekt enthält die folgenden Elemente:

|===
| Name | Beschreibung | Typ 


 a| 
snapMirrorEndpointID
 a| 
Die ID des Ziel- ONTAP Systems.
 a| 
ganze Zahl



 a| 
snapMirrorRelationshipID
 a| 
Die eindeutige Kennung für jedes snapMirrorRelationship-Objekt in einem Array, wie sie in ListSnapMirrorRelationships zurückgegeben würde.  Diese UUID wird vom ONTAP -System erstellt und zurückgegeben.
 a| 
Schnur



 a| 
Quellvolumen
 a| 
Ein Objekt, das das Quellvolumen beschreibt.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]



 a| 
Zielvolumen
 a| 
Ein Objekt, das das Zielvolumen beschreibt.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]



 a| 
aktuelleMaximaleÜbertragungsrate
 a| 
Die aktuell maximale Übertragungsrate zwischen Quell- und Zielvolume in Kilobyte pro Sekunde.
 a| 
ganze Zahl



 a| 
ist gesund
 a| 
Unabhängig davon, ob die Beziehung gesund ist oder nicht. Mögliche Werte:

* Richtig: Die Beziehung ist gesund.
* Falsch: Die Beziehung ist ungesund.  Dies kann durch ein fehlgeschlagenes oder abgebrochenes manuelles oder geplantes Update oder durch eine Verzögerung des letzten geplanten Updates verursacht werden.

 a| 
boolescher Wert



 a| 
Verzögerung
 a| 
Die Zeitspanne in Sekunden, um die die Daten auf dem Zielvolume den Daten auf dem Quellvolume hinterherhinken.
 a| 
ganze Zahl



 a| 
letzteÜberweisungsdauer
 a| 
Die Zeitspanne in Sekunden, die für den Abschluss der letzten Übertragung benötigt wurde.
 a| 
ganze Zahl



 a| 
letzter Transferfehler
 a| 
Eine Meldung, die die Ursache des letzten Übertragungsfehlers beschreibt.
 a| 
Schnur



 a| 
letzte Transfergröße
 a| 
Die Gesamtzahl der bei der letzten Übertragung übertragenen Bytes.
 a| 
ganze Zahl



 a| 
letzterÜbertragungsendzeitstempel
 a| 
Der Zeitstempel des Endes der letzten Übertragung.
 a| 
ISO 8601 Datumszeichenfolge



 a| 
letzter Transfertyp
 a| 
Die Art der vorherigen Überweisung in der Beziehung.
 a| 
Schnur



 a| 
maxTransferRate
 a| 
Gibt die maximale Datenübertragungsrate zwischen den Volumes in Kilobyte pro Sekunde an.  Der Standardwert 0 bedeutet unbegrenzte Bandbreite und ermöglicht es der SnapMirror -Beziehung, die verfügbare Netzwerkbandbreite voll auszunutzen.
 a| 
ganze Zahl



 a| 
Spiegelzustand
 a| 
Der Spiegelzustand der SnapMirror -Beziehung. Mögliche Werte:

* Nicht initialisiert: Das Zielvolume wurde nicht initialisiert.
* snapmirrored: Das Zielvolume wurde initialisiert und ist bereit, SnapMirror -Updates zu empfangen.
* Abgebrochen: Das Zielvolume ist lesbar und beschreibbar, und es sind Snapshots vorhanden.

 a| 
Schnur



 a| 
neuestes Foto
 a| 
Der Name der neuesten Snapshot-Kopie auf dem Zielvolume.
 a| 
Schnur



 a| 
Richtlinienname
 a| 
Gibt den Namen der ONTAP SnapMirror -Richtlinie für die Beziehung an.  Eine Liste der verfügbaren Richtlinien kann mit ListSnapMirrorPolicies abgerufen werden.  Beispielwerte sind "`MirrorLatest`" und "`MirrorAndVault`".
 a| 
Schnur



 a| 
Richtlinientyp
 a| 
Der Typ der ONTAP SnapMirror -Richtlinie für die Beziehung.  Siehe ListSnapMirrorPolicies.  Beispiele sind: "`async_mirror`" oder "`mirror_vault`".
 a| 
Schnur



 a| 
Beziehungsfortschritt
 a| 
Die Gesamtzahl der Bytes, die bisher für die aktuelle Aktivität der Beziehung verarbeitet wurden, wie im Beziehungsstatus zurückgegeben.  Dieser Wert wird nur dann gesetzt, wenn das Element „relationshipStatus“ anzeigt, dass eine Aktivität im Gange ist.
 a| 
ganze Zahl



 a| 
Beziehungsstatus
 a| 
Der Status der SnapMirror -Beziehung. Mögliche Werte:

* Leerlauf
* Übertragung
* Überprüfung
* Ruhen
* Ruhe
* in der Warteschlange
* Vorbereitung
* Abschluss
* Abbruch
* brech

 a| 
Schnur



 a| 
Beziehungstyp
 a| 
Die Art der SnapMirror Beziehung.  Auf Speicherclustern, auf denen die Element-Software läuft, ist dieser Wert immer "`extended_data_protection`".
 a| 
Schnur



 a| 
Zeitplanname
 a| 
Der Name des bereits vorhandenen Cron-Zeitplans im ONTAP System, der zur Aktualisierung der SnapMirror Beziehung verwendet wird.  Eine Liste der verfügbaren Zeitpläne kann mit ListSnapMirrorSchedules abgerufen werden.
 a| 
Schnur



 a| 
ungesunder Grund
 a| 
Der Grund, warum die Beziehung ungesund ist.
 a| 
Schnur

|===