---
permalink: api/reference_element_api_listvolumestatsbyvirtualvolume.html 
sidebar: sidebar 
keywords: volumes,volume,virtual,stats,list,listing,listvolumestatsbyvirtualvolume,activity 
summary: Mit der Methode ListVolumeStatsByVirtualVolume können Sie die Volumenstatistiken für alle Volumen im System auflisten, die mit einem virtuellen Volumen verknüpft sind.  Die Statistiken werden seit der Erstellung des Bandes kumulativ erfasst. 
---
= ListVolumeStatsByVirtualVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVolumeStatsByVirtualVolume` Methode zum Auflisten von Volumenstatistiken für alle Volumen im System, die mit einem virtuellen Volumen verknüpft sind.  Die Statistiken werden seit der Erstellung des Bandes kumulativ erfasst.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
virtuelleVolumeIDs
 a| 
Eine Liste mit einer oder mehreren virtuellen Volume-IDs, für die Informationen abgerufen werden sollen.  Wenn Sie diesen Parameter angeben, gibt die Methode nur Informationen über diese virtuellen Volumes zurück.
 a| 
UUID-Zeichenkettenarray
 a| 
Nein
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
volumeStats
 a| 
Eine Liste von Objekten, die Aktivitätsinformationen für jedes virtuelle Volumen im System enthalten.
 a| 
xref:reference_element_api_volumestats.adoc[volumeStats]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVolumeStatsByVirtualVolume",
  "params": {},
  "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 17,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 1074265444,
        "burstIOPSCredit": 0,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            26
          ],
          "primary": 56
        },
        "nonZeroBlocks": 36,
        "readBytes": 18366464,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 156,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-10-10T17:46:35.914642Z",
        "unalignedReads": 156,
        "unalignedWrites": 185,
        "virtualVolumeID": "070ac0ba-f344-4f4c-b79c-142efa3642e8",
        "volumeAccessGroups": [],
        "volumeID": 12518,
        "volumeSize": 91271200768,
        "volumeUtilization": 0,
        "writeBytes": 23652213248,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 185,
        "writeOpsLastSample": 0,
        "zeroBlocks": 22282972
      }
    ]
  }
}
----


== Neu seit Version

9,6
