---
permalink: api/reference_element_api_getpendingoperation.html 
sidebar: sidebar 
keywords: get,getting,pending,operation,getpendingoperation 
summary: Mit der Methode GetPendingOperation können Sie erkennen, ob ein Vorgang auf einem Knoten gerade ausgeführt wird.  Diese Methode kann auch verwendet werden, um eine Rückmeldung zu geben, wenn ein Vorgang abgeschlossen ist. 
---
= GetPendingOperation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetPendingOperation` Methode zum Erkennen einer Operation auf einem Knoten, die gerade ausgeführt wird.  Diese Methode kann auch verwendet werden, um eine Rückmeldung zu geben, wenn ein Vorgang abgeschlossen ist.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
ausstehend
 a| 
Mögliche Werte:

* Richtig: Die Operation ist noch im Gange.
* FALSCH:
+
Die Operation ist nicht mehr im Gange.


 a| 
boolescher Wert



 a| 
Betrieb
 a| 
Name der laufenden oder abgeschlossenen Operation.
 a| 
Schnur

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "GetPendingOperation",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 1,
   "result" : {
      "pendingOperation" : {
         "pending" : "true",
         "operation" : "TestDrivesInternal",
      }
   }
}
----


== Neu seit Version

9,6
