---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: Mit der Methode ListVirtualVolumes können Sie die aktuell im System vorhandenen virtuellen Volumes auflisten.  Mit dieser Methode können Sie entweder alle virtuellen Volumes auflisten oder nur eine Teilmenge. 
---
= ListVirtualVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVirtualVolumes` Methode zum Auflisten der aktuell im System befindlichen virtuellen Volumes.  Mit dieser Methode können Sie entweder alle virtuellen Volumes auflisten oder nur eine Teilmenge.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Details
 a| 
Der Detaillierungsgrad der Antwort. Mögliche Werte:

* true: Fügen Sie der Antwort weitere Details zu jedem VVol hinzu.
* false: Geben Sie in der Antwort den Standard-Detailgrad für jedes VVol an.

 a| 
boolescher Wert
 a| 
FALSCH
 a| 
Nein



 a| 
Limit
 a| 
Die maximale Anzahl der aufzulistenden virtuellen Volumes.
 a| 
ganze Zahl
 a| 
10000
 a| 
Nein



 a| 
rekursiv
 a| 
Legt fest, ob Informationen über die untergeordneten Elemente jedes VVol in die Antwort aufgenommen werden sollen oder nicht. Mögliche Werte:

* true: Geben Sie in der Antwort Informationen über die Kinder jedes VVol an.
* falsch: Informationen über die Kinder jedes VVol sollen nicht in die Antwort aufgenommen werden.

 a| 
boolescher Wert
 a| 
FALSCH
 a| 
Nein



 a| 
startVirtualVolumeID
 a| 
Die ID des virtuellen Volumes, bei dem die Liste in der Antwort beginnen soll.
 a| 
UUIDType
 a| 
Keine
 a| 
Nein



 a| 
virtuelleVolumeIDs
 a| 
Eine Liste virtueller Volume-IDs, zu denen Informationen abgerufen werden können.  Wenn Sie diesen Parameter weglassen, gibt die Methode nur Informationen über diese virtuellen Volumes zurück.
 a| 
virtuellesVolumeID-UUID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===


| Name | Beschreibung | Typ 


 a| 
nextVirtualVolumeID
 a| 
Die ID des nächsten virtuellen Volumes in der Liste.
 a| 
UUID



 a| 
virtuelleVolumes
 a| 
Eine Liste von Objekten, die die aktuell im System vorhandenen virtuellen Volumes beschreiben.
 a| 
xref:reference_element_api_virtualvolume.adoc[virtuelles Volumen]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Neu seit Version

9,6
