---
permalink: api/reference_element_api_listgroupsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,group,list,listing,listgroupsnapshots 
summary: Mit der Methode ListGroupSnapshots können Sie Informationen über alle erstellten Gruppen-Snapshots abrufen. 
---
= ListGroupSnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verwenden `ListGroupSnapshots` Methode zur Rückgabe von Informationen über alle erstellten Gruppen-Snapshots.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Gruppen-Snapshot-ID
 a| 
Informationen zu einer einzelnen Gruppen-Snapshot-ID abrufen.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
Bände
 a| 
Ein Array eindeutiger Volume-IDs zur Abfrage.  Wenn Sie diesen Parameter nicht angeben, werden alle Gruppen-Snapshots im Cluster einbezogen.
 a| 
volumeID-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Gruppenfotos
 a| 
Eine Liste von Objekten, die Informationen zu jedem Gruppen-Snapshot enthalten.
 a| 
xref:reference_element_api_groupsnapshot.adoc[Gruppenfoto]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListGroupSnapshots",
  "params": {
  "volumes": [
     31,
     49
    ]
  },
  "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "groupSnapshots": [
      {
          "status": "Done",
          "remoteStatuses": [
              {
                "volumePairUUID": "abcdef-1234-5678-90ab-cdef0123",
                "remoteStatus": "Present"
              }
          ],
          "attributes": {},
          "groupSnapshotID": 1,
          "createTime": "2014-06-17T17:35:05Z",
          "members": [
              {
                "snapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "expirationReason": "None",
                "virtualVolumeID": "abcdef-1234-5678-90ab-cdef0123",
                "groupID": 1,
                "createTime": "2014-06-17T17:35:05Z",
                "totalSize": 1,
                "snapMirrorLabel": "test1",
                "volumeName": "test1",
                "instanceCreateTime": "2014-06-17T17:35:05Z",
                "volumeID": 1,
                "checksum": "0x0",
                "attributes": {},
                "instanceSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "snapshotID": 1,
                "status": "Done",
                "groupSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123",
                "expirationTime": "2014-06-17T17:35:05Z",
                "enableRemoteReplication": true,
                "name": "test1",
                "remoteStatuses": [
                      {
                        "volumePairUUID": "abcdef-1234-5678-90ab-cdef0123",
                        "remoteStatus": "Present"
                      }
                  ]
              }
          ],
          "enableRemoteReplication": true,
          "name": "test1",
          "groupSnapshotUUID": "abcdef-1234-5678-90ab-cdef0123"
      }
	]
}
----


== Neu seit Version

9,6
