---
permalink: api/reference_element_api_testconnectsvip.html 
sidebar: sidebar 
keywords: storage,connection,svip,test,testing,testconnectsvip 
summary: Mit der Methode TestConnectSvip können Sie die Speicherverbindung zum Speichercluster testen.  Der Test pingt den SVIP mit ICMP-Paketen an und stellt bei Erfolg eine Verbindung als iSCSI-Initiator her. 
---
= TestConnectSvip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `TestConnectSvip` Methode zum Testen der Speicherverbindung zum Speichercluster.  Der Test pingt den SVIP mit ICMP-Paketen an und stellt bei Erfolg eine Verbindung als iSCSI-Initiator her.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
VIP
 a| 
Sie können diesen Wert übergeben, um die Managementverbindung eines anderen SVIP zu testen.  Sie müssen diesen Wert nicht verwenden, wenn Sie die Verbindung zum Zielcluster testen.
 a| 
Schnur
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Details
 a| 
Informationen zum Testvorgang (JSON-Objekt):

* `connected`: Gibt an, ob der Test eine Verbindung zum SVIP herstellen konnte (boolescher Wert)
* `svip`: Der SVIP wurde gegen (Zeichenkette) getestet
* `pingBytes`Details zu den Ping-Tests mit 56 Bytes und 9000 Bytes (Objekt)
+
** `56`Ergebnisse des 56-Byte-Ping-Tests (JSON-Objekt):
+
*** `individualResponseTimes`: Liste der Antwortzeiten von jedem Ensemble-Knoten (Zeichenketten-Array)
*** `individualStatus`: Liste des Ping-Status von jedem Ensemble-Knoten (boolesches Array)
*** `responseTime`Durchschnittliche Ping-Antwortzeit (Zeichenkette)
*** `successful`: Gibt an, ob der Ping-Test erfolgreich war (boolescher Wert)


** `9000`Ergebnisse des 9000-Byte-Ping-Tests (JSON-Objekt):
+
*** `individualResponseTimes`: Liste der Antwortzeiten von jedem Ensemble-Knoten (Zeichenketten-Array)
*** `individualStatus`: Liste des Ping-Status von jedem Ensemble-Knoten (boolesches Array)
*** `responseTime`Durchschnittliche Ping-Antwortzeit (Zeichenkette)
*** `successful`: Gibt an, ob der Ping-Test erfolgreich war (boolescher Wert)


** `duration`: Dauer der Testausführung (Zeichenkette)
** `result`Gesamtergebnis des Tests (Zeichenkette)



 a| 
Schnur

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "TestConnectSvip",
   "params": {
      "svip" : "172.27.62.50"
      },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "pingBytes": {
           "56": {
               "individualResponseTimes": [
                   "00:00:00.000152",
                   "00:00:00.000132",
                   "00:00:00.000119",
                   "00:00:00.000114",
                   "00:00:00.000112"
              ],
              "individualStatus": [
                  true,
                  true,
                  true,
                  true,
                  true
              ],
              "responseTime": "00:00:00.000126",
              "successful": true
           },
          "9000": {
                "individualResponseTimes": [
                    "00:00:00.000295",
                    "00:00:00.000257",
                    "00:00:00.000172",
                    "00:00:00.000172",
                    "00:00:00.000267"
              ],
              "individualStatus": [
                  true,
                  true,
                  true,
                  true,
                  true
             ],
             "responseTime": "00:00:00.000233",
             "successful": true
           }
        },
        "svip": "172.27.62.50"
      },
      "duration": "00:00:00.421907",
      "result": "Passed"
   }
}
----


== Neu seit Version

9,6
