---
permalink: api/reference_element_api_getdrivehardwareinfo.html 
sidebar: sidebar 
keywords: drive,get,getting,hardware,info,getdrivehardwareinfo 
summary: Mit der Methode GetDriveHardwareInfo können Sie alle Hardwareinformationen für das jeweilige Laufwerk abrufen.  Dies umfasst im Allgemeinen Hersteller, Lieferanten, Versionen und andere zugehörige Hardware-Identifikationsinformationen. 
---
= GetDriveHardwareInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetDriveHardwareInfo` Methode zum Abrufen aller Hardwareinformationen für das jeweilige Laufwerk.  Dies umfasst im Allgemeinen Hersteller, Lieferanten, Versionen und andere zugehörige Hardware-Identifikationsinformationen.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Laufwerk-ID
 a| 
Laufwerks-ID für die Anfrage.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Ergebnis
 a| 
Die zurückgegebenen Hardwareinformationen für die angegebene Laufwerks-ID.
 a| 
xref:reference_element_api_hardwareinfo.adoc[Hardwareinformationen]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "GetDriveHardwareInfo",
   "params": {
     "driveID": 5
   },
   "id" : 100
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id" : 100,
   "result" : {
     "driveHardwareInfo" : {
       "description" : "ATA Drive",
       "dev" : "8:80",
       "devpath" : "/devices/pci0000:40/0000:40:01.0/0000:41:00.0/host6/port-6:0/expander-6:0/port-6:0:4/end_device-6:0:4/target6:0:4/6:0:4:0/block/sdf",
       "driveSecurityAtMaximum" : false,
       "driveSecurityFrozen" : false
       "driveSecurityLocked" : false,
       "logicalname" : "/dev/sdf",
       "product" : "INTEL SSDSA2CW300G3",
       "securityFeatureEnabled" : false,
       "securityFeatureSupported" : true,
       "serial" : "CVPR121400NT300EGN",
       "size" : "300069052416",
       "uuid" : "7e1fd5b9-5acc-8991-e2ac-c48f813a3884",
       "version" : "4PC10362"
     }
   }
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_listdrives.adoc[ListDrives]
