---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: Die Web-Benutzeroberfläche der Element-Software verwendet die Methode ResyncSnapMirrorRelationship, um eine Spiegelbeziehung zwischen einem Quell- und einem Zielendpunkt herzustellen oder wiederherzustellen.  Wenn Sie eine Beziehung neu synchronisieren, entfernt das System Snapshots auf dem Zielvolume, die neuer als die gemeinsame Snapshot-Kopie sind, und bindet dann das Zielvolume als Datensicherungsvolume ein, wobei die gemeinsame Snapshot-Kopie als exportierte Snapshot-Kopie dient. 
---
= ResyncSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Web-Benutzeroberfläche der Element-Software verwendet die `ResyncSnapMirrorRelationship` Methode zum Herstellen oder Wiederherstellen einer Spiegelbeziehung zwischen einem Quell- und einem Zielendpunkt.  Wenn Sie eine Beziehung neu synchronisieren, entfernt das System Snapshots auf dem Zielvolume, die neuer als die gemeinsame Snapshot-Kopie sind, und bindet dann das Zielvolume als Datensicherungsvolume ein, wobei die gemeinsame Snapshot-Kopie als exportierte Snapshot-Kopie dient.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
snapMirrorEndpointID
 a| 
Die Endpunkt-ID des entfernten ONTAP -Speichersystems, das mit dem Element-Speichercluster kommuniziert.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja



 a| 
Zielvolumen
 a| 
Das Zielvolumen in der SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Keine
 a| 
Ja



 a| 
maxTransferRate
 a| 
Gibt die maximale Datenübertragungsrate zwischen den Volumes in Kilobyte pro Sekunde an.  Der Standardwert 0 bedeutet unbegrenzte Bandbreite und ermöglicht es der SnapMirror -Beziehung, die verfügbare Netzwerkbandbreite voll auszunutzen.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
Quellvolumen
 a| 
Das Quellvolumen in der SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Snap-Spiegelbeziehung
 a| 
Ein Objekt, das Informationen über die resynchronisierte SnapMirror -Beziehung enthält.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[Snap-Spiegelbeziehung]

|===


== Neu seit Version

10,1
