---
permalink: api/reference_element_api_getaccountefficiency.html 
sidebar: sidebar 
keywords: accounts,account,efficiency,get,getting,GetAccountEfficiency 
summary: Mit GetAccountEfficiency erhalten Sie Effizienzstatistiken zu einem Volumenkonto.  Diese Methode liefert Effizienzinformationen nur für das Konto, das Sie als Parameter angeben. 
---
= GetAccountEfficiency
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verwenden `GetAccountEfficiency` um Effizienzstatistiken über ein Volumenkonto zu erhalten.  Diese Methode liefert Effizienzinformationen nur für das Konto, das Sie als Parameter angeben.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Konto-ID
 a| 
Gibt das Volumenkonto an, für das Effizienzstatistiken zurückgegeben werden.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Kompression
 a| 
Die durch Datenkomprimierung eingesparte Speicherplatzmenge für alle Volumes im Konto.  Angegeben als Verhältniswert, wobei ein Wert von „1“ bedeutet, dass die Daten unkomprimiert gespeichert wurden.
 a| 
schweben



 a| 
Deduplizierung
 a| 
Die durch den Verzicht auf die Datenduplizierung für alle Volumes im Konto eingesparte Speicherplatzmenge.  Als Verhältnis angegeben.
 a| 
schweben



 a| 
fehlende Bände
 a| 
Die Volumina, für die keine Effizienzdaten abgefragt werden konnten.  Fehlende Volumes können durch einen Garbage Collection (GC)-Zyklus verursacht werden, der weniger als eine Stunde zurückliegt, durch einen vorübergehenden Verlust der Netzwerkverbindung oder durch einen Neustart von Diensten seit dem GC-Zyklus.
 a| 
Ganzzahl-Array



 a| 
Thin Provisioning
 a| 
Das Verhältnis des genutzten Speicherplatzes zum für die Datenspeicherung vorgesehenen Speicherplatz.  Als Verhältnis angegeben.
 a| 
schweben



 a| 
Zeitstempel
 a| 
Die letzten Effizienzdaten wurden nach der Garbage Collection (GC) im UTC+0-Format erfasst.
 a| 
ISO 8601 Datumszeichenfolge

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "GetAccountEfficiency",
   "params": {
     "accountID": 3
   },
   "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.020468042933262,
       "deduplication": 2.042488619119879,
       "missingVolumes": [],
       "thinProvisioning": 1.010087163391013,
       "timestamp": "2014-03-10T14:06:02Z"
   }
}
----


== Neu seit Version

9,6
