---
permalink: api/reference_element_api_listclusterpairs.html 
sidebar: sidebar 
keywords: cluster,pair,pairs,paired,list,listing,listclusterpairs 
summary: 'Mit der Methode ListClusterPairs können Sie alle Cluster auflisten, die mit dem aktuellen Cluster gepaart sind.  Diese Methode liefert Informationen über aktive und ausstehende Clusterpaarungen, wie z. B. Statistiken über die aktuelle Paarung sowie die Konnektivität und Latenz (in Millisekunden) der Clusterpaarung.' 
---
= ListClusterPairs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListClusterPairs` Methode zum Auflisten aller Cluster, die mit dem aktuellen Cluster gepaart sind.  Diese Methode liefert Informationen über aktive und ausstehende Clusterpaarungen, wie z. B. Statistiken über die aktuelle Paarung sowie die Konnektivität und Latenz (in Millisekunden) der Clusterpaarung.



== Parameter

Diese Methode hat keinen Eingabeparameter:



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Clusterpaare
 a| 
Informationen zu jedem gepaarten Cluster.
 a| 
xref:reference_element_api_clusterpair.adoc[Clusterpaar]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListClusterPairs",
   "params": {
      },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
 "id": 1,
 "result": {
   "clusterPairs": [
     {
      "clusterName": "cluster2",
      "clusterPairID": 3,
      "clusterPairUUID": "9866fbeb-c2f8-4df3-beb9-58a5c4e49c9b",
      "clusterUUID": 5487,
      "latency": 1,
      "mvip": "172.1.1.5",
      "status": "Connected"
      "version": "8.0.0.1361"
     },
     {
      "clusterName": "cluster3",
      "clusterPairID": 2,
      "clusterPairUUID": "8132a699-ce82-41e0-b406-fb914f976042",
      "clusterUUID": 1383,
      "latency": 1,
      "mvip": "172.1.1.6",
      "status": "Connected"
      "version": "8.0.0.1361"
     }
   ]
 }
----


== Neu seit Version

9,6
