---
permalink: api/reference_element_api_startclusterpairing.html 
sidebar: sidebar 
keywords: cluster,pair,pairing,start,starting,startclusterpairing 
summary: Mit der Methode StartClusterPairing können Sie einen codierten Schlüssel aus einem Cluster erstellen, der zum Pairing mit einem anderen Cluster verwendet wird.  Der mit dieser API-Methode erzeugte Schlüssel wird in der CompleteClusterPairing-Methode verwendet, um eine Cluster-Paarung herzustellen.  Ein Cluster kann mit maximal vier anderen Clustern gekoppelt werden. 
---
= Clusterpaarung starten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `StartClusterPairing` Methode zur Erstellung eines codierten Schlüssels aus einem Cluster, der zur Kopplung mit einem anderen Cluster verwendet wird.  Der mit dieser API-Methode erzeugte Schlüssel wird verwendet in der `CompleteClusterPairing` Methode zur Ermittlung einer Clusterpaarung.  Ein Cluster kann mit maximal vier anderen Clustern gekoppelt werden.



== Parameter

Diese Methode hat keinen Eingabeparameter.



== Rückgabewerte

Diese Methode hat die folgenden Rückgabewerte:

|===
| Name | Beschreibung | Typ 


 a| 
Clusterpaarungsschlüssel
 a| 
Eine Zeichenkette, die von derxref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing] API-Methode.
 a| 
Schnur



 a| 
Clusterpaar-ID
 a| 
Eindeutige Kennung für das Clusterpaar.
 a| 
ganze Zahl

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "StartClusterPairing",
   "params": {
      },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
   "id": 1,
   "result": {
     "clusterPairID": 1,
     "clusterPairingKey": "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
   }
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing]
