---
permalink: api/reference_element_api_resetdrives.html 
sidebar: sidebar 
keywords: drive,drives,remove,removing,data,reset,resetting,resetdrives,erase 
summary: Mit der ResetDrives-Methode können Sie Laufwerke proaktiv initialisieren und alle aktuell auf einem Laufwerk vorhandenen Daten entfernen.  Das Laufwerk kann dann in einem bestehenden Knoten wiederverwendet oder in einem aufgerüsteten Knoten eingesetzt werden. 
---
= ResetDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ResetDrives` Methode zum proaktiven Initialisieren von Laufwerken und Entfernen aller aktuell auf einem Laufwerk befindlichen Daten.  Das Laufwerk kann dann in einem bestehenden Knoten wiederverwendet oder in einem aufgerüsteten Knoten eingesetzt werden.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Laufwerke
 a| 
Liste der zurückzusetzenden Gerätenamen (nicht Laufwerks-IDs).
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Gewalt
 a| 
Auf „true“ setzen, um das Laufwerk zurückzusetzen.
 a| 
boolescher Wert
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Details
 a| 
Details zu den Laufwerken, die zurückgesetzt werden.
 a| 
JSON-Objektarray

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ResetDrives",
   "params": {
      "drives" : "slot3",
      "force" : true
   },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
   "details": {
    "drives": [
    {
      "drive": "slot3",
      "returnCode": 0,
      "stderr": " * Unlocking /dev/slot9 .[ ok ]\ * Setting master password /dev/slot9 .[ ok ]\ * Secure erasing /dev/slot9 (hdparm) [tries=0/1] ...........................[ ok ]",
      "stdout": ""
    }
   ]
  },
  "duration": "00:00:28.501269",
  "result": "Passed"
  }
}
----


== Neu seit Version

9,6
