---
permalink: api/reference_element_api_listvirtualnetworks.html 
sidebar: sidebar 
keywords: virtual,network,networks,listing,list,listvirtualnetworks 
summary: Mit der Methode ListVirtualNetworks können Sie alle für den Cluster konfigurierten virtuellen Netzwerke auflisten. 
---
= ListVirtualNetworks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListVirtualNetworks` Methode zum Auflisten aller konfigurierten virtuellen Netzwerke für den Cluster.

Mit dieser Methode können Sie die Einstellungen des virtuellen Netzwerks im Cluster überprüfen.  Für diese Methode sind keine Parameter erforderlich.  Um die Ergebnisse zu filtern, können Sie jedoch einen oder mehrere virtualNetworkID- oder virtualNetworkTag-Werte angeben.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
virtuelle Netzwerk-ID
 a| 
Netzwerk-ID zum Filtern der Liste nach einem einzelnen virtuellen Netzwerk.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
virtuelles Netzwerk-Tag
 a| 
Netzwerk-Tag zum Filtern der Liste nach einem einzelnen virtuellen Netzwerk.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
virtuelleNetzwerk-IDs
 a| 
Netzwerk-IDs, die in die Liste aufgenommen werden sollen.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein



 a| 
virtuelleNetzwerktags
 a| 
Netzwerk-Tag, das in die Liste aufgenommen werden soll.
 a| 
Ganzzahl-Array
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
virtuelle Netzwerke
 a| 
Objekt, das virtuelle Netzwerk-IP-Adressen enthält.
 a| 
xref:reference_element_api_virtualnetwork.adoc[virtuelles Netzwerk]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "ListVirtualNetworks",
  "params": {
     "virtualNetworkIDs": [5,6]
   },
"id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "virtualNetworks": [
   {
    "addressBlocks": [
   {
    "available": "11000000",
    "size": 8,
    "start": "10.26.250.207"
   }
 ],
    "attributes": null,
    "gateway": "10.26.250.254",
    "name": "2250",
    "namespace": false,
    "netmask": "255.255.255.0",
    "svip": "10.26.250.200",
    "virtualNetworkID": 2250
   },
   {
     "addressBlocks": [
   {
     "available": "11000000",
     "size": 8,
     "start": "10.26.241.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.241.254",
     "name": "2241",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.241.200",
     "virtualNetworkID": 2241
   },
  {
     "addressBlocks": [
  {
     "available": "11000000",
     "size": 8,
     "start": "10.26.240.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.240.254",
     "name": "2240",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.240.200",
     "virtualNetworkID": 2240
    },
   {
  }
 ]
}
----


== Neu seit Version

9,6
