---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: Mit ModifySnapMirrorRelationship können Sie die Intervalle ändern, in denen ein geplanter Snapshot erstellt wird.  Mit dieser Methode können Sie einen Zeitplan auch löschen oder pausieren. 
---
= ModifySnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verwenden `ModifySnapMirrorRelationship` die Intervalle zu ändern, in denen ein geplanter Snapshot erstellt wird.  Mit dieser Methode können Sie einen Zeitplan auch löschen oder pausieren.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===


| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Zielvolumen
 a| 
Das Zielvolumen in der SnapMirror Beziehung.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Keine
 a| 
Ja



 a| 
maxTransferRate
 a| 
Gibt die maximale Datenübertragungsrate zwischen den Volumes in Kilobyte pro Sekunde an.  Der Standardwert 0 bedeutet unbegrenzte Bandbreite und ermöglicht es der SnapMirror -Beziehung, die verfügbare Netzwerkbandbreite voll auszunutzen.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
Richtlinienname
 a| 
Gibt den Namen der ONTAP SnapMirror -Richtlinie für die Beziehung an.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Zeitplanname
 a| 
Der Name des bereits vorhandenen Cron-Zeitplans im ONTAP System, der zur Aktualisierung der SnapMirror Beziehung verwendet wird.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
snapMirrorEndpointID
 a| 
Die Endpunkt-ID des entfernten ONTAP -Speichersystems, das mit dem Element-Speichercluster kommuniziert.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Snap-Spiegelbeziehung
 a| 
Ein Objekt, das die geänderten SnapMirror Beziehungsattribute enthält.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[Snap-Spiegelbeziehung]

|===


== Neu seit Version

10,1
