---
permalink: api/reference_element_api_getprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,retrieve protection domains 
summary: Mit der Methode GetProtectionDomainLayout können Sie alle Informationen zur Schutzdomäne eines Clusters abrufen, einschließlich des Chassis und der benutzerdefinierten Schutzdomäne, in der sich jeder Knoten befindet. 
---
= GetProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetProtectionDomainLayout` Methode zur Rückgabe aller Schutzdomäneninformationen für einen Cluster, einschließlich des Chassis und der benutzerdefinierten Schutzdomäne, in der sich jeder Knoten befindet.



== Parameter

Diese Methode benötigt keine Eingabeparameter.



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Schutzdomänenlayout
 a| 
Liste der Knoten, jeweils mit den zugehörigen Schutzdomänen.
 a| 
JSON-Liste vonlink:reference_element_api_nodeprotectiondomains.html["Knotenschutzdomänen"] Objekte.

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "GetProtectionDomainLayout",
  "params": {},
  "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Neu seit Version

12,0
