---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: Mit der Methode ListAuthSessionsByUsername können Sie alle Authentifizierungssitzungen für den angegebenen Benutzer auflisten.  Ein Anrufer, der nicht über die Zugriffsgruppe ClusterAdmins / Administratorrechte verfügt, darf nur seine eigenen Sitzungen auflisten.  Ein Aufrufer mit ClusterAdmins-/Administratorrechten kann Sitzungen beliebiger Benutzer auflisten. 
---
= ListAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListAuthSessionsByUsername` Methode zum Auflisten aller Authentifizierungssitzungen für den angegebenen Benutzer.  Ein Anrufer, der nicht über die Zugriffsgruppe ClusterAdmins / Administratorrechte verfügt, darf nur seine eigenen Sitzungen auflisten.  Ein Aufrufer mit ClusterAdmins-/Administratorrechten kann Sitzungen beliebiger Benutzer auflisten.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Authentifizierungsmethode
 a| 
Die aufzulistenden Authentifizierungsmethoden der Benutzersitzungen.  Nur ein Aufrufer in der Zugriffsgruppe ClusterAdmins/Administrator kann diesen Parameter angeben.  Mögliche Werte sind:

* *authMethod=Cluster* gibt den Benutzernamen des ClusterAdmins an.
* *authMethod=Ldap* gibt den LDAP-DN des Benutzers an.
* *authMethod=Idp* gibt entweder die IdP-UUID oder die NameID des Benutzers an.  Wenn der IdP nicht so konfiguriert ist, dass er eine der beiden Optionen zurückgibt, wird hier eine zufällige UUID angegeben, die beim Erstellen der Sitzung vergeben wurde.

 a| 
Authentifizierungsmethode
 a| 
Keine
 a| 
Ja



 a| 
Benutzername
 a| 
Eindeutige Kennung für den Benutzer.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Sitzungen
 a| 
Liste der Sitzungsinformationen für die Authentifizierungssitzungen.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Neu seit Version

12,0
