---
permalink: api/reference_element_api_gethardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,gethardwareinfo 
summary: Mit der Methode GetHardwareInfo können Sie Hardwareinformationen und den Status eines einzelnen Knotens abrufen.  Hardwareinformationen umfassen im Allgemeinen Hersteller, Lieferanten, Versionen, Laufwerke und andere zugehörige Identifikationsinformationen. 
---
= Hardwareinformationen abrufen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `GetHardwareInfo` Methode zum Abrufen von Live-Hardwareinformationen und -Status für einen einzelnen Knoten.  Hardwareinformationen umfassen im Allgemeinen Hersteller, Lieferanten, Versionen, Laufwerke und andere zugehörige Identifikationsinformationen.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Gewalt
 a| 
Setzen Sie diesen "force"-Parameter auf true, um das Skript auf allen Knoten im Cluster auszuführen.
 a| 
boolescher Wert
 a| 
FALSCH
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
Hardwareinformationen
 a| 
Hardwareinformationen für den Knoten.
 a| 
xref:reference_element_api_hardwareinfo.adoc[Hardwareinformationen]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "GetHardwareInfo",
   "params": {
   },
"id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "hardwareInfo": {
      "bus": {
        "core_DMI:0200": {
          "description": "Motherboard",
          "physid": "0",
          "product": "0A47AA",
          "serial": "..AB123456C12354.",
          "version": "C07"
        }
      },
      "driveHardware": [
        {
          "canonicalName": "sdh",
          "connected": true,
          "dev": 2160,
          "devPath": "/dev/disk/by-path/pci-0000:41:00.0-sas-0x500056b37789abf0-lun-0",
          "driveEncryptionCapability": "fips",
          "driveType": "Block",
          "lifeRemainingPercent": 92,
          "lifetimeReadBytes": 175436696911872,
          "lifetimeWriteBytes": 81941097349120,
          "name": "scsi-SATA_INTEL_SSDSC2BB3BTWL12345686300AAA",
          "path": "/dev/sdh",
          "pathLink": "/dev/disk/by-path/pci-0000:41:00.0-sas-0x500056b37789abf0-lun-0",
          "powerOnHours": 17246,
          "product": "INTEL SSDAA2AA300A4",
          "reallocatedSectors": 0,
          "reserveCapacityPercent": 100,
          "scsiCompatId": "scsi-SATA_INTEL_SSDSC2BB3BTWL12345686300AAA",
          "scsiState": "Running",
          "securityAtMaximum": false,
          "securityEnabled": false,
          "securityFrozen": false,
          "securityLocked": false,
          "securitySupported": true,
          "serial": "AAAA33710886300AAA",
          "size": 300069052416,
          "slot": 1,
          "smartSsdWriteCapable": false,
          "uuid": "aea178b9-c336-6bab-a61d-87b615e8120c",
          "vendor": "Intel",
          "version": "D2010370"
        },
      ...
      ]
    }
  }
}
----


== Neu seit Version

9,6
