---
permalink: api/reference_element_api_listpendingnodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,nodes,node,listpendingnodes 
summary: Mit der Methode ListPendingNodes können Sie die im System vorhandenen, noch ausstehenden Speicherknoten auflisten.  Bei ausstehenden Knoten handelt es sich um Speicherknoten, die ausgeführt werden und für den Beitritt zum Speichercluster konfiguriert sind, aber noch nicht mit der AddNodes-API-Methode hinzugefügt wurden. 
---
= Liste der ausstehenden Knoten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `ListPendingNodes` Methode zum Auflisten der ausstehenden Speicherknoten im System.  Bei ausstehenden Knoten handelt es sich um Speicherknoten, die ausgeführt werden und für den Beitritt zum Speichercluster konfiguriert sind, aber noch nicht mit der AddNodes-API-Methode hinzugefügt wurden.



== IPv4- und IPv6-Verwaltungsadressen

Beachten Sie, dass `ListPendingNodes` listet keine ausstehenden Knoten auf, die unterschiedliche Adresstypen für die Management-IP-Adresse (MIP) und die virtuelle Management-IP-Adresse (MVIP) aufweisen.  Wenn beispielsweise ein ausstehender Knoten über eine IPv6-MVIP und eine IPv4-MIP verfügt, `ListPendingNodes` wird den Knoten nicht in das Ergebnis aufnehmen.



== Parameter

Diese Methode hat keine Eingabeparameter.



== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===
| Name | Beschreibung | Typ 


 a| 
ausstehende Knoten
 a| 
Liste der ausstehenden Knoten im Cluster.
 a| 
xref:reference_element_api_pendingnode.adoc[ausstehender Knoten]Array

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "ListPendingNodes",
   "params": {},
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 3,
  "result": {
    "pendingNodes": [
      {
        "assignedNodeID": 0,
        "cip": "10.26.65.101",
        "cipi": "Bond10G",
        "compatible": true,
        "mip": "172.26.65.101",
        "mipi": "Bond1G",
        "name": "VWC-EN101",
        "pendingNodeID": 1,
        "platformInfo": {
          "chassisType": "R620",
          "cpuModel": "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
          "nodeMemoryGB": 72,
          "nodeType": "SF3010"
        },
        "sip": "10.26.65.101",
        "sipi": "Bond10G",
        "softwareVersion": "9.0.0.1554",
        "uuid": "4C4C4544-0048-4410-8056-C7C04F395931"
      }
    ]
  }
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_addnodes.adoc[AddNodes]
