---
permalink: api/reference_element_api_deleteauthsession.html 
sidebar: sidebar 
keywords: authentication sessions,delete 
summary: Mit der Methode DeleteAuthSession können Sie eine einzelne Authentifizierungssitzung löschen.  Wenn der aufrufende Benutzer nicht Mitglied der ClusterAdmins / Administrator AccessGroup ist, kann nur die Authentifizierungssitzung des aufrufenden Benutzers gelöscht werden. 
---
= DeleteAuthSession
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `DeleteAuthSession` Methode zum Löschen einer einzelnen Benutzerauthentifizierungssitzung.  Wenn der aufrufende Benutzer nicht Mitglied der ClusterAdmins / Administrator AccessGroup ist, kann nur die Authentifizierungssitzung des aufrufenden Benutzers gelöscht werden.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Sitzungs-ID
 a| 
Eindeutige Kennung für die zu löschende Authentifizierungssitzung.
 a| 
UUID
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Sitzung
 a| 
Sitzungsinformationen für die Löschauthentifizierungssitzung.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "method": "DeleteAuthSession",
    "params": {
        "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713"
    },
    "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
    "id": 1,
    "result": {
        "session": {
            "accessGroupList": [
                "administrator"
            ],
            "authMethod": "Cluster",
            "clusterAdminIDs": [
                1
            ],
            "finalTimeout": "2020-04-09T17:51:30Z",
            "idpConfigVersion": 0,
            "lastAccessTimeout": "2020-04-06T18:21:33Z",
            "sessionCreationTime": "2020-04-06T17:51:30Z",
            "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713",
            "username": "admin"
        }
    }
}
----


== Neu seit Version

12,0
