---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: Mit der TestPing-Methode können Sie die Netzwerkverbindung zu allen Knoten im Cluster sowohl auf 1G- als auch auf 10G-Schnittstellen mithilfe von ICMP-Paketen testen.  Der Test verwendet für jedes Paket die passende MTU-Größe basierend auf den MTU-Einstellungen in der Netzwerkkonfiguration.  TestPing erstellt keine temporäre VLAN-Schnittstelle. 
---
= TestPing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `TestPing` Methode zum Testen der Netzwerkverbindung zu allen Knoten im Cluster über 1G- und 10G-Schnittstellen mittels ICMP-Paketen.  Der Test verwendet für jedes Paket die passende MTU-Größe basierend auf den MTU-Einstellungen in der Netzwerkkonfiguration. `TestPing` Es wird keine temporäre VLAN-Schnittstelle erstellt.



== Parameter

Diese Methode hat folgende Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Versuche
 a| 
Gibt an, wie oft das System den Test-Ping wiederholen soll.
 a| 
ganze Zahl
 a| 
5
 a| 
Nein



 a| 
Gastgeber
 a| 
Gibt eine durch Kommas getrennte Liste von Adressen oder Hostnamen von Geräten an, die angepingt werden sollen.  Wenn keine Hosts angegeben sind, pingt die Methode die Hosts im Speichercluster an.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Schnittstelle
 a| 
Die bestehende (Basis-)Schnittstelle, von der die Pings gesendet werden sollen. Mögliche Werte:

* `Bond10G`: Sende Pings von der Bond10G-Schnittstelle.
* `Bond1G`: Sende Pings von der Bond1G-Schnittstelle.

 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Paketgröße
 a| 
Gibt die Anzahl der Bytes an, die im ICMP-Paket gesendet werden sollen, das an jede IP-Adresse gesendet wird.  Die Anzahl der Bytes muss kleiner sein als die in der Netzwerkkonfiguration angegebene maximale MTU.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein



 a| 
pingTimeoutMsec
 a| 
Gibt die Anzahl der Millisekunden an, die auf jede einzelne Ping-Antwort gewartet werden soll.
 a| 
ganze Zahl
 a| 
500 Millisekunden
 a| 
Nein



 a| 
verbieten Fragmentierung
 a| 
Aktiviert das DF-Flag (Do not Fragment) für ICMP-Pakete.
 a| 
boolescher Wert
 a| 
FALSCH
 a| 
Nein



 a| 
sourceAddressV4
 a| 
Die Quell-IPv4-Adresse, die in den ICMP-Ping-Paketen verwendet werden soll.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
sourceAddressV6
 a| 
Die Quell-IPv6-Adresse, die in den ICMP-Ping-Paketen verwendet werden soll.
 a| 
Schnur
 a| 
Keine
 a| 
Nein



 a| 
Gesamtzeitüberschreitung in Sekunden
 a| 
Gibt die Zeit in Sekunden an, die der Ping auf eine Systemantwort warten soll, bevor der nächste Ping-Versuch gestartet oder der Prozess beendet wird.
 a| 
ganze Zahl
 a| 
5
 a| 
Nein



 a| 
virtuelles Netzwerk-Tag
 a| 
Die VLAN-ID, die beim Senden der Ping-Pakete verwendet werden soll.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Nein

|===


== Rückgabewert

Diese Methode hat folgenden Rückgabewert:

|===


| Name | Beschreibung | Typ 


 a| 
Details
 a| 
Liste aller IP-Adressen, mit denen der Knoten kommunizieren konnte, sowie Statistiken zur Ping-Antwort.
 a| 
JSON-Objekt

|===


== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== Neu seit Version

5,0
