---
permalink: api/reference_element_api_volume_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: volume,pairing,order,operations,volumes,pairing,pair,pairs 
summary: Bevor Volumes gepaart werden können, muss ein Clusterpaar zwischen zwei entsprechenden Clustern erstellt werden. 
---
= Reihenfolge der Volumenpaarung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Volumes gepaart werden können, muss ein Clusterpaar zwischen zwei entsprechenden Clustern erstellt werden.

Verwenden Sie die folgenden API-Methoden, um eine Clusterverbindung herzustellen:

* xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]:
+
Diese API-Methode erstellt und gibt einen Volume-Pairing-Schlüssel zurück, der zum Erstellen eines Volume-Paares verwendet wird.  Der Schlüssel enthält Informationen, die zur Herstellung von Kommunikationsverbindungen zwischen den Volumes verwendet werden.

* xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]:
+
Diese Methode verwendet den mit dem erstellten Kopplungsschlüssel.xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing] API-Methode zum Erstellen eines Volumenpaares.  Stellen Sie diexref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API-Methode mit den Parametern volumeID und volumePairingKey zum Zielvolume.



Nur eines der beiden gepaarten Volumes kann als Replikationszielvolume identifiziert werden.  Verwenden Sie diexref:reference_element_api_modifyvolumepair.adoc[ModifyVolumePair] API-Methode zur Festlegung der Richtung der Datenreplikation des Volumes durch Identifizierung des Ziel-Volumes.  Die Daten werden vom Quellvolume auf das Zielvolume repliziert.



== Weitere Informationen

* xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
* xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
* xref:reference_element_api_modifyvolumepair.adoc[ModifyVolumePair]

