---
permalink: api/reference_element_api_createcluster.html 
sidebar: sidebar 
keywords: CreateCluster,cluster,create,creating,initialize,initializing 
summary: 'Mit der CreateCluster-Methode können Sie den Knoten in einem Cluster initialisieren, der die Adressen "mvip" und "svip" besitzt.  Jeder neue Cluster wird mit der Management-IP (MIP) des ersten Knotens im Cluster initialisiert.  Diese Methode fügt außerdem automatisch alle konfigurierten Knoten dem Cluster hinzu.  Diese Methode muss nur einmal pro Initialisierung eines neuen Clusters angewendet werden.' 
---
= CreateCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die `CreateCluster` Methode zur Initialisierung des Knotens in einem Cluster, der die Adressen "mvip" und "svip" besitzt.  Jeder neue Cluster wird mit der Management-IP (MIP) des ersten Knotens im Cluster initialisiert.  Diese Methode fügt außerdem automatisch alle konfigurierten Knoten dem Cluster hinzu.  Diese Methode muss nur einmal pro Initialisierung eines neuen Clusters angewendet werden.


NOTE: Nachdem Sie sich am Masterknoten des Clusters angemeldet und den Befehl ausgeführt haben,xref:reference_element_api_getbootstrapconfig.adoc[GetBootStrapConfig] Um die IP-Adressen für die restlichen Knoten zu erhalten, die Sie in den Cluster aufnehmen möchten, können Sie die CreateCluster-Methode auf dem Master-Knoten des Clusters ausführen.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
acceptEula
 a| 
Bitte bestätigen Sie Ihre Zustimmung zur Endbenutzer-Lizenzvereinbarung bei der Erstellung dieses Clusters.  Um die EULA zu akzeptieren, setzen Sie diesen Parameter auf „true“.
 a| 
boolescher Wert
 a| 
Keine
 a| 
Ja



 a| 
Attribute
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt
 a| 
Keine
 a| 
Nein



 a| 
enableSoftwareEncryptionAtRest
 a| 
Aktivieren Sie diesen Parameter, um softwarebasierte Verschlüsselung ruhender Daten zu verwenden.  Standardmäßig auf allen Clustern auf „false“ gesetzt.  Sobald die Softwareverschlüsselung ruhender Daten aktiviert ist, kann sie auf dem Cluster nicht mehr deaktiviert werden.
 a| 
boolescher Wert
 a| 
true
 a| 
Nein



 a| 
MVIP
 a| 
Floating (virtuelle) IP-Adresse für den Cluster im Management-Netzwerk.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Knoten
 a| 
CIP/SIP-Adressen der ersten Knoten, aus denen der Cluster besteht.  Die IP-Adresse dieses Knotens muss in der Liste enthalten sein.
 a| 
Zeichenketten-Array
 a| 
Keine
 a| 
Ja



 a| 
Bestellnummer
 a| 
Alphanumerische Auftragsnummer.  Auf softwarebasierten Plattformen erforderlich.
 a| 
Schnur
 a| 
Keine
 a| 
Nein (hardwarebasierte Plattformen)

Ja (softwarebasierte Plattformen)



 a| 
Passwort
 a| 
Anfangspasswort für das Cluster-Administratorkonto.
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Seriennummer
 a| 
Neunstellige alphanumerische Seriennummer.  Kann auf softwarebasierten Plattformen erforderlich sein.
 a| 
Schnur
 a| 
Keine
 a| 
Nein (hardwarebasierte Plattformen)

Ja (softwarebasierte Plattformen)



 a| 
VIP
 a| 
Floating (virtuelle) IP-Adresse für den Cluster im Speichernetzwerk (iSCSI).
 a| 
Schnur
 a| 
Keine
 a| 
Ja



 a| 
Benutzername
 a| 
Benutzername für den Cluster-Administrator.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewerte

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
  "method": "CreateCluster",
  "params": {
    "acceptEula": true,
    "mvip": "10.0.3.1",
    "svip": "10.0.4.1",
    "username": "Admin1",
    "password": "9R7ka4rEPa2uREtE",
    "attributes": {
      "clusteraccountnumber": "axdf323456"
    },
    "nodes": [
      "10.0.2.1",
      "10.0.2.2",
      "10.0.2.3",
      "10.0.2.4"
    ]
  },
  "id": 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"id" : 1,
"result" : {}
}
----


== Neu seit Version

9,6

[discrete]
== Weitere Informationen

* link:reference_element_api_getbootstrapconfig.html["GetBootstrapConfig"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire und Element-Softwaredokumentation"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Dokumentation für frühere Versionen der NetApp SolidFire und Element-Produkte"^]

