---
permalink: api/reference_element_api_completevolumepairing.html 
sidebar: sidebar 
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing 
summary: Mit CompleteVolumePairing können Sie die Kopplung zweier Volumes abschließen. 
---
= CompleteVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können verwenden `CompleteVolumePairing` um die beiden Bände zusammenzuführen.



== Parameter

Diese Methode hat die folgenden Eingabeparameter:

|===
| Name | Beschreibung | Typ | Standardwert | Erforderlich 


 a| 
Volume-ID
 a| 
Die ID des Datenträgers, der das Datenträgerpaar vervollständigt.
 a| 
ganze Zahl
 a| 
Keine
 a| 
Ja



 a| 
Lautstärke-Kopplungstaste
 a| 
Der Schlüssel wurde von derxref:reference_element_api_startvolumepairing.adoc[StartVolumePairing] API-Methode.
 a| 
Schnur
 a| 
Keine
 a| 
Ja

|===


== Rückgabewert

Diese Methode hat keinen Rückgabewert.



== Anforderungsbeispiel

Anfragen für diese Methode ähneln dem folgenden Beispiel:

[listing]
----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----


== Antwortbeispiel

Diese Methode liefert eine Antwort, die dem folgenden Beispiel ähnelt:

[listing]
----
{
"id": 1,
"result": {}
}
----


== Neu seit Version

9,6



== Weitere Informationen

xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
