---
permalink: api/reference_element_api_groupsnapshot.html 
sidebar: sidebar 
keywords: object,objects,groupSnapshot 
summary: Das groupSnapshot-Objekt enthält Informationen über einen Snapshot für eine Gruppe von Volumes.  Sie können die ListGroupSnapshots-API-Methode verwenden, um Gruppen-Snapshot-Informationen abzurufen. 
---
= Gruppenfoto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das groupSnapshot-Objekt enthält Informationen über einen Snapshot für eine Gruppe von Volumes.  Sie können die `ListGroupSnapshots` API-Methode zum Abrufen von Gruppen-Snapshot-Informationen.



== Objektmitglieder

Dieses Objekt enthält die folgenden Elemente:

|===
| Name | Beschreibung | Typ 


 a| 
Attribute
 a| 
Liste von Name-Wert-Paaren im JSON-Objektformat.
 a| 
JSON-Objekt



 a| 
Erstellungszeit
 a| 
Datum und Uhrzeit im UTC+0-Format, an dem der Gruppen-Snapshot erstellt wurde.
 a| 
ISO 8601 Datumszeichenfolge



 a| 
Remote-Replikation aktivieren
 a| 
Gibt an, ob der Snapshot für die Remote-Replikation aktiviert ist.
 a| 
boolescher Wert



 a| 
Gruppen-Snapshot-ID
 a| 
Die eindeutige ID des Gruppen-Snapshots.
 a| 
ganze Zahl



 a| 
groupSnapshotUUID
 a| 
Die UUID des Gruppen-Snapshots.
 a| 
Schnur



 a| 
Mitglieder
 a| 
Ein Array von Objekten, das Informationen über jedes Mitglied des Gruppen-Snapshots enthält.
 a| 
xref:reference_element_api_snapshot.adoc[Schnappschuss]Array



 a| 
Name
 a| 
Der Name des Gruppen-Snapshots oder, falls kein Name angegeben wurde, der im UTC-Format angegebene Tag und die Uhrzeit, an der der Snapshot erstellt wurde.
 a| 
Zeichenkette oder ISO 8601-Datumszeichenkette



 a| 
Remote-Status
 a| 
Ein Array, das die universelle Kennung und den Replikationsstatus jedes Remote-Snapshots auf dem Zielcluster aus Sicht des Quellclusters enthält.
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[remoteClusterSnapshotStatus]Array



 a| 
Status
 a| 
Aktueller Status des Snapshots. Mögliche Werte:

* Unbekannt: Beim Abrufen des Status des Snapshots ist ein Fehler aufgetreten.
* Vorbereitung: Dieser Snapshot wird für die Verwendung vorbereitet und ist noch nicht beschreibbar.
* RemoteSyncing: Dieser Snapshot wird von einem Remote-Cluster repliziert.
* Fertig: Dieser Snapshot wurde vollständig vorbereitet bzw. repliziert und ist nun verwendbar.
* Aktiv: Dieser Snapshot ist der aktive Branch.
* Klonen: Dieser Snapshot ist Teil eines CopyVolume-Vorgangs.

 a| 
Schnur

|===


== Weitere Informationen

xref:reference_element_api_listgroupsnapshots.adoc[ListGroupSnapshots]
